// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: rust/sp-analytics/proto/analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventsRequest) Reset() {
	*x = IngestEventsRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventsRequest) ProtoMessage() {}

func (x *IngestEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventsRequest.ProtoReflect.Descriptor instead.
func (*IngestEventsRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      uint32                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventsResponse) Reset() {
	*x = IngestEventsResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventsResponse) ProtoMessage() {}

func (x *IngestEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventsResponse.ProtoReflect.Descriptor instead.
func (*IngestEventsResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestEventsResponse) GetRejected() uint32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestEventsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DeviceId       string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Did            *string                `protobuf:"bytes,4,opt,name=did,proto3,oneof" json:"did,omitempty"`
	SessionId      string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TimestampMs    int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	StreamerDid    string                 `protobuf:"bytes,7,opt,name=streamer_did,json=streamerDid,proto3" json:"streamer_did,omitempty"`
	StreamId       *string                `protobuf:"bytes,8,opt,name=stream_id,json=streamId,proto3,oneof" json:"stream_id,omitempty"`
	PropertiesJson string                 `protobuf:"bytes,9,opt,name=properties_json,json=propertiesJson,proto3" json:"properties_json,omitempty"`
	SchemaVersion  uint32                 `protobuf:"varint,10,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ClientVersion  string                 `protobuf:"bytes,11,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Platform       string                 `protobuf:"bytes,12,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event) GetDid() string {
	if x != nil && x.Did != nil {
		return *x.Did
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Event) GetStreamerDid() string {
	if x != nil {
		return x.StreamerDid
	}
	return ""
}

func (x *Event) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

func (x *Event) GetPropertiesJson() string {
	if x != nil {
		return x.PropertiesJson
	}
	return ""
}

func (x *Event) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Event) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Event) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type StreamerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamerDid   string                 `protobuf:"bytes,1,opt,name=streamer_did,json=streamerDid,proto3" json:"streamer_did,omitempty"`
	StartTimeMs   *int64                 `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs,proto3,oneof" json:"start_time_ms,omitempty"`
	EndTimeMs     *int64                 `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs,proto3,oneof" json:"end_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamerStatsRequest) Reset() {
	*x = StreamerStatsRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamerStatsRequest) ProtoMessage() {}

func (x *StreamerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamerStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamerStatsRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *StreamerStatsRequest) GetStreamerDid() string {
	if x != nil {
		return x.StreamerDid
	}
	return ""
}

func (x *StreamerStatsRequest) GetStartTimeMs() int64 {
	if x != nil && x.StartTimeMs != nil {
		return *x.StartTimeMs
	}
	return 0
}

func (x *StreamerStatsRequest) GetEndTimeMs() int64 {
	if x != nil && x.EndTimeMs != nil {
		return *x.EndTimeMs
	}
	return 0
}

type StreamerStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StreamerDid      string                 `protobuf:"bytes,1,opt,name=streamer_did,json=streamerDid,proto3" json:"streamer_did,omitempty"`
	TotalViews       uint64                 `protobuf:"varint,2,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalWatchTimeMs uint64                 `protobuf:"varint,3,opt,name=total_watch_time_ms,json=totalWatchTimeMs,proto3" json:"total_watch_time_ms,omitempty"`
	UniqueViewers    uint64                 `protobuf:"varint,4,opt,name=unique_viewers,json=uniqueViewers,proto3" json:"unique_viewers,omitempty"`
	DailyStats       []*DailyStats          `protobuf:"bytes,5,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamerStatsResponse) Reset() {
	*x = StreamerStatsResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamerStatsResponse) ProtoMessage() {}

func (x *StreamerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamerStatsResponse.ProtoReflect.Descriptor instead.
func (*StreamerStatsResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *StreamerStatsResponse) GetStreamerDid() string {
	if x != nil {
		return x.StreamerDid
	}
	return ""
}

func (x *StreamerStatsResponse) GetTotalViews() uint64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *StreamerStatsResponse) GetTotalWatchTimeMs() uint64 {
	if x != nil {
		return x.TotalWatchTimeMs
	}
	return 0
}

func (x *StreamerStatsResponse) GetUniqueViewers() uint64 {
	if x != nil {
		return x.UniqueViewers
	}
	return 0
}

func (x *StreamerStatsResponse) GetDailyStats() []*DailyStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type DailyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Views         uint64                 `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	WatchTimeMs   uint64                 `protobuf:"varint,3,opt,name=watch_time_ms,json=watchTimeMs,proto3" json:"watch_time_ms,omitempty"`
	UniqueViewers uint64                 `protobuf:"varint,4,opt,name=unique_viewers,json=uniqueViewers,proto3" json:"unique_viewers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *DailyStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStats) GetViews() uint64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *DailyStats) GetWatchTimeMs() uint64 {
	if x != nil {
		return x.WatchTimeMs
	}
	return 0
}

func (x *DailyStats) GetUniqueViewers() uint64 {
	if x != nil {
		return x.UniqueViewers
	}
	return 0
}

type ViewerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	StartTimeMs   *int64                 `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs,proto3,oneof" json:"start_time_ms,omitempty"`
	EndTimeMs     *int64                 `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs,proto3,oneof" json:"end_time_ms,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerHistoryRequest) Reset() {
	*x = ViewerHistoryRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerHistoryRequest) ProtoMessage() {}

func (x *ViewerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerHistoryRequest.ProtoReflect.Descriptor instead.
func (*ViewerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *ViewerHistoryRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ViewerHistoryRequest) GetStartTimeMs() int64 {
	if x != nil && x.StartTimeMs != nil {
		return *x.StartTimeMs
	}
	return 0
}

func (x *ViewerHistoryRequest) GetEndTimeMs() int64 {
	if x != nil && x.EndTimeMs != nil {
		return *x.EndTimeMs
	}
	return 0
}

func (x *ViewerHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ViewerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*WatchSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerHistoryResponse) Reset() {
	*x = ViewerHistoryResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerHistoryResponse) ProtoMessage() {}

func (x *ViewerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerHistoryResponse.ProtoReflect.Descriptor instead.
func (*ViewerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ViewerHistoryResponse) GetSessions() []*WatchSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WatchSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamerDid   string                 `protobuf:"bytes,2,opt,name=streamer_did,json=streamerDid,proto3" json:"streamer_did,omitempty"`
	StreamId      *string                `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3,oneof" json:"stream_id,omitempty"`
	StartTimeMs   int64                  `protobuf:"varint,4,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs     int64                  `protobuf:"varint,5,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	DurationMs    uint64                 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSession) Reset() {
	*x = WatchSession{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSession) ProtoMessage() {}

func (x *WatchSession) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSession.ProtoReflect.Descriptor instead.
func (*WatchSession) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *WatchSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchSession) GetStreamerDid() string {
	if x != nil {
		return x.StreamerDid
	}
	return ""
}

func (x *WatchSession) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

func (x *WatchSession) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *WatchSession) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *WatchSession) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RealtimeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamerDid   *string                `protobuf:"bytes,1,opt,name=streamer_did,json=streamerDid,proto3,oneof" json:"streamer_did,omitempty"`
	WindowMinutes uint32                 `protobuf:"varint,2,opt,name=window_minutes,json=windowMinutes,proto3" json:"window_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeStatsRequest) Reset() {
	*x = RealtimeStatsRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeStatsRequest) ProtoMessage() {}

func (x *RealtimeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeStatsRequest.ProtoReflect.Descriptor instead.
func (*RealtimeStatsRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *RealtimeStatsRequest) GetStreamerDid() string {
	if x != nil && x.StreamerDid != nil {
		return *x.StreamerDid
	}
	return ""
}

func (x *RealtimeStatsRequest) GetWindowMinutes() uint32 {
	if x != nil {
		return x.WindowMinutes
	}
	return 0
}

type RealtimeStatsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Streamers     []*StreamerRealtimeStats `protobuf:"bytes,1,rep,name=streamers,proto3" json:"streamers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeStatsResponse) Reset() {
	*x = RealtimeStatsResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeStatsResponse) ProtoMessage() {}

func (x *RealtimeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeStatsResponse.ProtoReflect.Descriptor instead.
func (*RealtimeStatsResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *RealtimeStatsResponse) GetStreamers() []*StreamerRealtimeStats {
	if x != nil {
		return x.Streamers
	}
	return nil
}

type StreamerRealtimeStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StreamerDid      string                 `protobuf:"bytes,1,opt,name=streamer_did,json=streamerDid,proto3" json:"streamer_did,omitempty"`
	CurrentViewers   uint64                 `protobuf:"varint,2,opt,name=current_viewers,json=currentViewers,proto3" json:"current_viewers,omitempty"`
	TotalWatchTimeMs uint64                 `protobuf:"varint,3,opt,name=total_watch_time_ms,json=totalWatchTimeMs,proto3" json:"total_watch_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamerRealtimeStats) Reset() {
	*x = StreamerRealtimeStats{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamerRealtimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamerRealtimeStats) ProtoMessage() {}

func (x *StreamerRealtimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamerRealtimeStats.ProtoReflect.Descriptor instead.
func (*StreamerRealtimeStats) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *StreamerRealtimeStats) GetStreamerDid() string {
	if x != nil {
		return x.StreamerDid
	}
	return ""
}

func (x *StreamerRealtimeStats) GetCurrentViewers() uint64 {
	if x != nil {
		return x.CurrentViewers
	}
	return 0
}

func (x *StreamerRealtimeStats) GetTotalWatchTimeMs() uint64 {
	if x != nil {
		return x.TotalWatchTimeMs
	}
	return 0
}

type DeleteUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataRequest) Reset() {
	*x = DeleteUserDataRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataRequest) ProtoMessage() {}

func (x *DeleteUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserDataRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserDataRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type DeleteUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataResponse) Reset() {
	*x = DeleteUserDataResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataResponse) ProtoMessage() {}

func (x *DeleteUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserDataResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserDataResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteUserDataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDeletionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeletionStatusRequest) Reset() {
	*x = GetDeletionStatusRequest{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeletionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeletionStatusRequest) ProtoMessage() {}

func (x *GetDeletionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeletionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeletionStatusRequest) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetDeletionStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeletionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	RequestedAtMs *int64                 `protobuf:"varint,4,opt,name=requested_at_ms,json=requestedAtMs,proto3,oneof" json:"requested_at_ms,omitempty"`
	CompletedAtMs *int64                 `protobuf:"varint,5,opt,name=completed_at_ms,json=completedAtMs,proto3,oneof" json:"completed_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionStatusResponse) Reset() {
	*x = DeletionStatusResponse{}
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionStatusResponse) ProtoMessage() {}

func (x *DeletionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rust_sp_analytics_proto_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionStatusResponse.ProtoReflect.Descriptor instead.
func (*DeletionStatusResponse) Descriptor() ([]byte, []int) {
	return file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *DeletionStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeletionStatusResponse) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *DeletionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeletionStatusResponse) GetRequestedAtMs() int64 {
	if x != nil && x.RequestedAtMs != nil {
		return *x.RequestedAtMs
	}
	return 0
}

func (x *DeletionStatusResponse) GetCompletedAtMs() int64 {
	if x != nil && x.CompletedAtMs != nil {
		return *x.CompletedAtMs
	}
	return 0
}

var File_rust_sp_analytics_proto_analytics_proto protoreflect.FileDescriptor

const file_rust_sp_analytics_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"'rust/sp-analytics/proto/analytics.proto\x12\tanalytics\"?\n" +
	"\x13IngestEventsRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.analytics.EventR\x06events\"f\n" +
	"\x14IngestEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\rR\brejected\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\xa5\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x03did\x18\x04 \x01(\tH\x00R\x03did\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12!\n" +
	"\fstreamer_did\x18\a \x01(\tR\vstreamerDid\x12 \n" +
	"\tstream_id\x18\b \x01(\tH\x01R\bstreamId\x88\x01\x01\x12'\n" +
	"\x0fproperties_json\x18\t \x01(\tR\x0epropertiesJson\x12%\n" +
	"\x0eschema_version\x18\n" +
	" \x01(\rR\rschemaVersion\x12%\n" +
	"\x0eclient_version\x18\v \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\f \x01(\tR\bplatformB\x06\n" +
	"\x04_didB\f\n" +
	"\n" +
	"_stream_id\"\xa9\x01\n" +
	"\x14StreamerStatsRequest\x12!\n" +
	"\fstreamer_did\x18\x01 \x01(\tR\vstreamerDid\x12'\n" +
	"\rstart_time_ms\x18\x02 \x01(\x03H\x00R\vstartTimeMs\x88\x01\x01\x12#\n" +
	"\vend_time_ms\x18\x03 \x01(\x03H\x01R\tendTimeMs\x88\x01\x01B\x10\n" +
	"\x0e_start_time_msB\x0e\n" +
	"\f_end_time_ms\"\xe9\x01\n" +
	"\x15StreamerStatsResponse\x12!\n" +
	"\fstreamer_did\x18\x01 \x01(\tR\vstreamerDid\x12\x1f\n" +
	"\vtotal_views\x18\x02 \x01(\x04R\n" +
	"totalViews\x12-\n" +
	"\x13total_watch_time_ms\x18\x03 \x01(\x04R\x10totalWatchTimeMs\x12%\n" +
	"\x0eunique_viewers\x18\x04 \x01(\x04R\runiqueViewers\x126\n" +
	"\vdaily_stats\x18\x05 \x03(\v2\x15.analytics.DailyStatsR\n" +
	"dailyStats\"\x81\x01\n" +
	"\n" +
	"DailyStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05views\x18\x02 \x01(\x04R\x05views\x12\"\n" +
	"\rwatch_time_ms\x18\x03 \x01(\x04R\vwatchTimeMs\x12%\n" +
	"\x0eunique_viewers\x18\x04 \x01(\x04R\runiqueViewers\"\xae\x01\n" +
	"\x14ViewerHistoryRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12'\n" +
	"\rstart_time_ms\x18\x02 \x01(\x03H\x00R\vstartTimeMs\x88\x01\x01\x12#\n" +
	"\vend_time_ms\x18\x03 \x01(\x03H\x01R\tendTimeMs\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limitB\x10\n" +
	"\x0e_start_time_msB\x0e\n" +
	"\f_end_time_ms\"L\n" +
	"\x15ViewerHistoryResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.analytics.WatchSessionR\bsessions\"\xe5\x01\n" +
	"\fWatchSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fstreamer_did\x18\x02 \x01(\tR\vstreamerDid\x12 \n" +
	"\tstream_id\x18\x03 \x01(\tH\x00R\bstreamId\x88\x01\x01\x12\"\n" +
	"\rstart_time_ms\x18\x04 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x05 \x01(\x03R\tendTimeMs\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x04R\n" +
	"durationMsB\f\n" +
	"\n" +
	"_stream_id\"v\n" +
	"\x14RealtimeStatsRequest\x12&\n" +
	"\fstreamer_did\x18\x01 \x01(\tH\x00R\vstreamerDid\x88\x01\x01\x12%\n" +
	"\x0ewindow_minutes\x18\x02 \x01(\rR\rwindowMinutesB\x0f\n" +
	"\r_streamer_did\"W\n" +
	"\x15RealtimeStatsResponse\x12>\n" +
	"\tstreamers\x18\x01 \x03(\v2 .analytics.StreamerRealtimeStatsR\tstreamers\"\x92\x01\n" +
	"\x15StreamerRealtimeStats\x12!\n" +
	"\fstreamer_did\x18\x01 \x01(\tR\vstreamerDid\x12'\n" +
	"\x0fcurrent_viewers\x18\x02 \x01(\x04R\x0ecurrentViewers\x12-\n" +
	"\x13total_watch_time_ms\x18\x03 \x01(\x04R\x10totalWatchTimeMs\")\n" +
	"\x15DeleteUserDataRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"O\n" +
	"\x16DeleteUserDataResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"9\n" +
	"\x18GetDeletionStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xe3\x01\n" +
	"\x16DeletionStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x0frequested_at_ms\x18\x04 \x01(\x03H\x00R\rrequestedAtMs\x88\x01\x01\x12+\n" +
	"\x0fcompleted_at_ms\x18\x05 \x01(\x03H\x01R\rcompletedAtMs\x88\x01\x01B\x12\n" +
	"\x10_requested_at_msB\x12\n" +
	"\x10_completed_at_ms2\x95\x04\n" +
	"\tAnalytics\x12O\n" +
	"\fIngestEvents\x12\x1e.analytics.IngestEventsRequest\x1a\x1f.analytics.IngestEventsResponse\x12U\n" +
	"\x10GetStreamerStats\x12\x1f.analytics.StreamerStatsRequest\x1a .analytics.StreamerStatsResponse\x12U\n" +
	"\x10GetViewerHistory\x12\x1f.analytics.ViewerHistoryRequest\x1a .analytics.ViewerHistoryResponse\x12U\n" +
	"\x10GetRealtimeStats\x12\x1f.analytics.RealtimeStatsRequest\x1a .analytics.RealtimeStatsResponse\x12U\n" +
	"\x0eDeleteUserData\x12 .analytics.DeleteUserDataRequest\x1a!.analytics.DeleteUserDataResponse\x12[\n" +
	"\x11GetDeletionStatus\x12#.analytics.GetDeletionStatusRequest\x1a!.analytics.DeletionStatusResponseB!Z\x1fstreamplace/pkg/analytics/pb;pbb\x06proto3"

var (
	file_rust_sp_analytics_proto_analytics_proto_rawDescOnce sync.Once
	file_rust_sp_analytics_proto_analytics_proto_rawDescData []byte
)

func file_rust_sp_analytics_proto_analytics_proto_rawDescGZIP() []byte {
	file_rust_sp_analytics_proto_analytics_proto_rawDescOnce.Do(func() {
		file_rust_sp_analytics_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rust_sp_analytics_proto_analytics_proto_rawDesc), len(file_rust_sp_analytics_proto_analytics_proto_rawDesc)))
	})
	return file_rust_sp_analytics_proto_analytics_proto_rawDescData
}

var file_rust_sp_analytics_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rust_sp_analytics_proto_analytics_proto_goTypes = []any{
	(*IngestEventsRequest)(nil),      // 0: analytics.IngestEventsRequest
	(*IngestEventsResponse)(nil),     // 1: analytics.IngestEventsResponse
	(*Event)(nil),                    // 2: analytics.Event
	(*StreamerStatsRequest)(nil),     // 3: analytics.StreamerStatsRequest
	(*StreamerStatsResponse)(nil),    // 4: analytics.StreamerStatsResponse
	(*DailyStats)(nil),               // 5: analytics.DailyStats
	(*ViewerHistoryRequest)(nil),     // 6: analytics.ViewerHistoryRequest
	(*ViewerHistoryResponse)(nil),    // 7: analytics.ViewerHistoryResponse
	(*WatchSession)(nil),             // 8: analytics.WatchSession
	(*RealtimeStatsRequest)(nil),     // 9: analytics.RealtimeStatsRequest
	(*RealtimeStatsResponse)(nil),    // 10: analytics.RealtimeStatsResponse
	(*StreamerRealtimeStats)(nil),    // 11: analytics.StreamerRealtimeStats
	(*DeleteUserDataRequest)(nil),    // 12: analytics.DeleteUserDataRequest
	(*DeleteUserDataResponse)(nil),   // 13: analytics.DeleteUserDataResponse
	(*GetDeletionStatusRequest)(nil), // 14: analytics.GetDeletionStatusRequest
	(*DeletionStatusResponse)(nil),   // 15: analytics.DeletionStatusResponse
}
var file_rust_sp_analytics_proto_analytics_proto_depIdxs = []int32{
	2,  // 0: analytics.IngestEventsRequest.events:type_name -> analytics.Event
	5,  // 1: analytics.StreamerStatsResponse.daily_stats:type_name -> analytics.DailyStats
	8,  // 2: analytics.ViewerHistoryResponse.sessions:type_name -> analytics.WatchSession
	11, // 3: analytics.RealtimeStatsResponse.streamers:type_name -> analytics.StreamerRealtimeStats
	0,  // 4: analytics.Analytics.IngestEvents:input_type -> analytics.IngestEventsRequest
	3,  // 5: analytics.Analytics.GetStreamerStats:input_type -> analytics.StreamerStatsRequest
	6,  // 6: analytics.Analytics.GetViewerHistory:input_type -> analytics.ViewerHistoryRequest
	9,  // 7: analytics.Analytics.GetRealtimeStats:input_type -> analytics.RealtimeStatsRequest
	12, // 8: analytics.Analytics.DeleteUserData:input_type -> analytics.DeleteUserDataRequest
	14, // 9: analytics.Analytics.GetDeletionStatus:input_type -> analytics.GetDeletionStatusRequest
	1,  // 10: analytics.Analytics.IngestEvents:output_type -> analytics.IngestEventsResponse
	4,  // 11: analytics.Analytics.GetStreamerStats:output_type -> analytics.StreamerStatsResponse
	7,  // 12: analytics.Analytics.GetViewerHistory:output_type -> analytics.ViewerHistoryResponse
	10, // 13: analytics.Analytics.GetRealtimeStats:output_type -> analytics.RealtimeStatsResponse
	13, // 14: analytics.Analytics.DeleteUserData:output_type -> analytics.DeleteUserDataResponse
	15, // 15: analytics.Analytics.GetDeletionStatus:output_type -> analytics.DeletionStatusResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rust_sp_analytics_proto_analytics_proto_init() }
func file_rust_sp_analytics_proto_analytics_proto_init() {
	if File_rust_sp_analytics_proto_analytics_proto != nil {
		return
	}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[2].OneofWrappers = []any{}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[3].OneofWrappers = []any{}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[6].OneofWrappers = []any{}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[8].OneofWrappers = []any{}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[9].OneofWrappers = []any{}
	file_rust_sp_analytics_proto_analytics_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rust_sp_analytics_proto_analytics_proto_rawDesc), len(file_rust_sp_analytics_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rust_sp_analytics_proto_analytics_proto_goTypes,
		DependencyIndexes: file_rust_sp_analytics_proto_analytics_proto_depIdxs,
		MessageInfos:      file_rust_sp_analytics_proto_analytics_proto_msgTypes,
	}.Build()
	File_rust_sp_analytics_proto_analytics_proto = out.File
	file_rust_sp_analytics_proto_analytics_proto_goTypes = nil
	file_rust_sp_analytics_proto_analytics_proto_depIdxs = nil
}
