[package]
name = "muxl-wasm"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "muxl-wasm"
path = "src/main.rs"

[dependencies]
muxl-sign = { git = "https://github.com/streamplace/muxl.git", rev = "79ac2324310f2b546cab59bbeeeae6835777bd2e", package = "muxl-sign" }
# muxl-sign = { path = "../../../muxl/crates/muxl-sign" }
