// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.admin.getAccountInfo

package comatproto

import (
	"context"

	glexrt "github.com/streamplace/glex/runtime"
)

// AdminGetAccountInfo calls the XRPC method "com.atproto.admin.getAccountInfo".
//
// Get details about an account.
func AdminGetAccountInfo(ctx context.Context, c glexrt.LexClient, did string) (*AdminDefs_AccountView, error) {
	var out AdminDefs_AccountView

	params := map[string]interface{}{}
	params["did"] = did

	if err := c.LexDo(ctx, glexrt.Query, "", "com.atproto.admin.getAccountInfo", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
