// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.admin.deleteAccount

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type AdminDeleteAccount_Input struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
}

func (t *AdminDeleteAccount_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.admin.deleteAccount#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AdminDeleteAccount_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AdminDeleteAccount calls the XRPC method "com.atproto.admin.deleteAccount".
//
// Delete a user account as an administrator.
func AdminDeleteAccount(ctx context.Context, c glexrt.LexClient, input *AdminDeleteAccount_Input) error {

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "com.atproto.admin.deleteAccount", nil, input, nil); err != nil {
		return err
	}
	return nil
}
