// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.identity.defs

package comatproto

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

// IdentityDefs_IdentityInfo is a "identityInfo" in the com.atproto.identity.defs schema.
type IdentityDefs_IdentityInfo struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
	// didDoc: The complete DID document for the identity.
	DidDoc *glexrt.LexiconTypeDecoder `json:"didDoc"`
	// handle: The validated handle of the account; or 'handle.invalid' if the handle did not bi-directionally match the DID document.
	Handle string `json:"handle"`
}

func (t *IdentityDefs_IdentityInfo) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.identity.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *IdentityDefs_IdentityInfo) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
