// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.identity.resolveIdentity

package comatproto

import (
	"context"

	glexrt "github.com/streamplace/glex/runtime"
)

// IdentityResolveIdentity calls the XRPC method "com.atproto.identity.resolveIdentity".
//
// Resolves an identity (DID or Handle) to a full identity (DID document and verified handle).
//
// identifier: Handle or DID to resolve.
func IdentityResolveIdentity(ctx context.Context, c glexrt.LexClient, identifier string) (*IdentityDefs_IdentityInfo, error) {
	var out IdentityDefs_IdentityInfo

	params := map[string]interface{}{}
	params["identifier"] = identifier

	if err := c.LexDo(ctx, glexrt.Query, "", "com.atproto.identity.resolveIdentity", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
