// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.identity.refreshIdentity

package comatproto

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type IdentityRefreshIdentity_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Identifier    string `json:"identifier"`
}

// RecordTypeID implements glex.Record.
func (t *IdentityRefreshIdentity_Input) RecordTypeID() string {
	return "com.atproto.identity.refreshIdentity"
}

func (t *IdentityRefreshIdentity_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.identity.refreshIdentity"
	return glex.MarshalCBOR(w, t)
}

func (t *IdentityRefreshIdentity_Input) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// IdentityRefreshIdentity calls the XRPC method "com.atproto.identity.refreshIdentity".
//
// Request that the server re-resolve an identity (DID and handle). The server may ignore this request, or require authentication, depending on the role, implementation, and policy of the server.
func IdentityRefreshIdentity(ctx context.Context, c glex.LexClient, input *IdentityRefreshIdentity_Input) (*IdentityDefs_IdentityInfo, error) {
	var out IdentityDefs_IdentityInfo

	if err := c.LexDo(ctx, glex.Procedure, "application/json", "com.atproto.identity.refreshIdentity", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
