// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.repo.importRepo

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
)

// RepoImportRepo calls the XRPC method "com.atproto.repo.importRepo".
//
// Import a repo in the form of a CAR file. Requires Content-Length HTTP header to be set.
func RepoImportRepo(ctx context.Context, c glexrt.LexClient, input io.Reader) error {

	if err := c.LexDo(ctx, glexrt.Procedure, "application/vnd.ipld.car", "com.atproto.repo.importRepo", nil, input, nil); err != nil {
		return err
	}
	return nil
}
