// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.server.refreshSession

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ServerRefreshSession_Output struct {
	LexiconTypeID string                     `json:"$type"`
	AccessJwt     string                     `json:"accessJwt"`
	Active        *bool                      `json:"active,omitempty"`
	Did           string                     `json:"did"`
	DidDoc        *glexrt.LexiconTypeDecoder `json:"didDoc,omitempty"`
	Handle        string                     `json:"handle"`
	RefreshJwt    string                     `json:"refreshJwt"`
	// status: Hosting status of the account. If not specified, then assume 'active'.
	Status *string `json:"status,omitempty"`
}

func (t *ServerRefreshSession_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.server.refreshSession#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ServerRefreshSession_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ServerRefreshSession calls the XRPC method "com.atproto.server.refreshSession".
//
// Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
func ServerRefreshSession(ctx context.Context, c glexrt.LexClient) (*ServerRefreshSession_Output, error) {
	var out ServerRefreshSession_Output

	if err := c.LexDo(ctx, glexrt.Procedure, "", "com.atproto.server.refreshSession", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
