// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.server.requestAccountDelete

package comatproto

import (
	"context"

	glexrt "github.com/streamplace/glex/runtime"
)

// ServerRequestAccountDelete calls the XRPC method "com.atproto.server.requestAccountDelete".
//
// Initiate a user account deletion via email.
func ServerRequestAccountDelete(ctx context.Context, c glexrt.LexClient) error {

	if err := c.LexDo(ctx, glexrt.Procedure, "", "com.atproto.server.requestAccountDelete", nil, nil, nil); err != nil {
		return err
	}
	return nil
}
