// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.server.getSession

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ServerGetSession_Output struct {
	LexiconTypeID   string                     `json:"$type"`
	Active          *bool                      `json:"active,omitempty"`
	Did             string                     `json:"did"`
	DidDoc          *glexrt.LexiconTypeDecoder `json:"didDoc,omitempty"`
	Email           *string                    `json:"email,omitempty"`
	EmailAuthFactor *bool                      `json:"emailAuthFactor,omitempty"`
	EmailConfirmed  *bool                      `json:"emailConfirmed,omitempty"`
	Handle          string                     `json:"handle"`
	// status: If active=false, this optional field indicates a possible reason for why the account is not active. If active=false and no status is supplied, then the host makes no claim for why the repository is no longer being hosted.
	Status *string `json:"status,omitempty"`
}

func (t *ServerGetSession_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.server.getSession#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ServerGetSession_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ServerGetSession calls the XRPC method "com.atproto.server.getSession".
//
// Get information about the current auth session. Requires auth.
func ServerGetSession(ctx context.Context, c glexrt.LexClient) (*ServerGetSession_Output, error) {
	var out ServerGetSession_Output

	if err := c.LexDo(ctx, glexrt.Query, "", "com.atproto.server.getSession", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
