// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.server.checkAccountStatus

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ServerCheckAccountStatus_Output struct {
	LexiconTypeID      string `json:"$type"`
	Activated          bool   `json:"activated"`
	ExpectedBlobs      int64  `json:"expectedBlobs"`
	ImportedBlobs      int64  `json:"importedBlobs"`
	IndexedRecords     int64  `json:"indexedRecords"`
	PrivateStateValues int64  `json:"privateStateValues"`
	RepoBlocks         int64  `json:"repoBlocks"`
	RepoCommit         string `json:"repoCommit"`
	RepoRev            string `json:"repoRev"`
	ValidDid           bool   `json:"validDid"`
}

func (t *ServerCheckAccountStatus_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.server.checkAccountStatus#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ServerCheckAccountStatus_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ServerCheckAccountStatus calls the XRPC method "com.atproto.server.checkAccountStatus".
//
// Returns the status of an account, especially as pertaining to import or recovery. Can be called many times over the course of an account migration. Requires auth and can only be called pertaining to oneself.
func ServerCheckAccountStatus(ctx context.Context, c glexrt.LexClient) (*ServerCheckAccountStatus_Output, error) {
	var out ServerCheckAccountStatus_Output

	if err := c.LexDo(ctx, glexrt.Query, "", "com.atproto.server.checkAccountStatus", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
