// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.atproto.temp.checkSignupQueue

package comatproto

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type TempCheckSignupQueue_Output struct {
	LexiconTypeID   string `json:"$type"`
	Activated       bool   `json:"activated"`
	EstimatedTimeMs *int64 `json:"estimatedTimeMs,omitempty"`
	PlaceInQueue    *int64 `json:"placeInQueue,omitempty"`
}

func (t *TempCheckSignupQueue_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.atproto.temp.checkSignupQueue#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *TempCheckSignupQueue_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// TempCheckSignupQueue calls the XRPC method "com.atproto.temp.checkSignupQueue".
//
// Check accounts location in signup queue.
func TempCheckSignupQueue(ctx context.Context, c glexrt.LexClient) (*TempCheckSignupQueue_Output, error) {
	var out TempCheckSignupQueue_Output

	if err := c.LexDo(ctx, glexrt.Query, "", "com.atproto.temp.checkSignupQueue", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
