version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - -QF1003 # "could use tagged switch"
        - -ST1003 # "should not use underscores in Go names" - indigo's code gen makes some
        - -SA5008 # "unknown JSON option" doesn't care for the const stuff
  disable:
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  exclusions:
    generated: lax
