packages:
  - js/*
onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - bufferutil
  - cbor-extract
  - detox
  - dtrace-provider
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - keccak
  - macos-alias
  - nx
  - protobufjs
  - quietjs-bundle
  - sharp
  - utf-8-validate
patchedDependencies:
  expo-dev-client: patches/expo-dev-client.patch
