packages:
  - js/*
onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - bufferutil
  - cbor-extract
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - keccak
  - macos-alias
  - nx
  - protobufjs
  - quietjs-bundle
  - sharp
  - utf-8-validate
