name = "streamplace-docs"
compatibility_date = "2025-04-01"

[assets]
directory = "./js/docs/dist/"
not_found_handling = "404-page"

[build]
command = "pnpm install --filter=streamplace-docs... --filter=@streamplace/brand && pnpm --filter @streamplace/brand generate && cd js/docs && astro build --outDir ./dist/docs && cp ./_redirects ./dist/_redirects && cp ../desktop/assets/images/streamplace-logo.ico ./dist/favicon.ico"
