name = "streamplace-docs"
compatibility_date = "2025-04-01"

[assets]
directory = "./js/docs/dist/"
not_found_handling = "404-page"

[build]
command = "pnpm install --filter=streamplace-docs... && cd js/docs && astro build --outDir ./dist/docs && cp ./_redirects ./dist/_redirects && cp ./src/assets/cube.png ./dist/favicon.ico"
