
export const STARTUP = "STARTUP";

export const TERMINAL_COMMAND = "TERMINAL_COMMAND";

export const WATCHER_READY = "WATCHER_READY";
export const WATCHER_ADD = "WATCHER_ADD";
export const WATCHER_CHANGE = "WATCHER_CHANGE";
export const WATCHER_UNLINK = "WATCHER_UNLINK";
export const WATCHER_LOAD_FILE = "WATCHER_LOAD_FILE";
export const WATCHER_LOAD_FILE_SUCCESS = "WATCHER_LOAD_FILE_SUCCESS";
export const WATCHER_LOAD_FILE_ERROR = "WATCHER_LOAD_FILE_ERROR";
export const WATCHER_WATCH = "WATCHER_WATCH";
