//go:build !static

// Code generated by hack/gen-cgo-flags.sh (make dev-cgo); DO NOT EDIT.
// Regenerate and commit when the meson dependency set changes.

// Link flags for dynamic dev builds, expanded from what used to be
// `#cgo pkg-config: streamplacedeps` so that no pkg-config invocation or
// environment variable is needed. Paths are ${SRCDIR}-relative so the same
// checkout works on the host and mounted at /app in the dev containers. The
// machine-specific rpath lives in the generated, gitignored
// zz_local_cgoflags.go; without it (containers, CI) LD_LIBRARY_PATH still
// works as before.

package streamplacedeps

// #cgo LDFLAGS: -L${SRCDIR}/../../build-linux-amd64/lib -liroh_streamplace -lavfilter -lavformat -lavcodec -lgio-2.0 -lgstcontroller-1.0 -lgstapp-1.0 -lgstpbutils-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lffi -lglib-2.0 -lintl
import "C"
