// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: com.atproto.moderation.defs

package comatproto

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)
