// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.access.getStatus

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type AccessGetStatus_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// chatVerified: Whether the authenticated caller is verified by one of the node's trusted verifiers.
	ChatVerified *bool `json:"chatVerified,omitempty"`
	// chatVerifiedOnly: Whether chat is restricted to users verified by the node's trusted verifiers (branding key chatVerifiedOnly).
	ChatVerifiedOnly *bool `json:"chatVerifiedOnly,omitempty"`
	// did: The authenticated caller, when there is one.
	Did    *string               `json:"did,omitempty"`
	Policy AccessDefs_PolicyView `json:"policy"`
	// roles: Every role the caller effectively holds.
	Roles []string `json:"roles"`
	// space: The node's access-control space: at://{authority}/space/place.stream.access.control/self (A space URI; not validated as a classic at-uri because the space form is newer than that grammar.)
	Space string `json:"space"`
}

// RecordTypeID implements glex.Record.
func (t *AccessGetStatus_Output) RecordTypeID() string { return "place.stream.access.getStatus" }

func (t *AccessGetStatus_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.access.getStatus"
	return glex.MarshalCBOR(w, &cp)
}

func (t *AccessGetStatus_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// AccessGetStatus calls the XRPC method "place.stream.access.getStatus".
//
// Report the caller's roles on this node and the node's access policy. Works unauthenticated (roles then reflect what an anonymous visitor holds). This is the one place.stream method a node always answers, even to accounts locked out by a private viewer policy, so clients can render the right wall.
//
// subject: For an anonymous caller (a client holding a session this node can't attribute), the account whose chat verification to report in chatVerified. Ignored when the caller is authenticated.
func AccessGetStatus(ctx context.Context, c glex.LexClient, subject string) (*AccessGetStatus_Output, error) {
	var out AccessGetStatus_Output

	params := map[string]interface{}{}
	if subject != "" {
		params["subject"] = subject
	}

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.access.getStatus", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
