// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.badge.def

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glexrt.RegisterType("place.stream.badge.def", &BadgeDef{})
}

// Defines a badge's visual appearance and type. Created by the issuer and referenced by issuance records.
type BadgeDef struct {
	LexiconTypeID string `json:"$type"`
	// badgeType: The category of this badge, used for scope and display rules.
	BadgeType string `json:"badgeType"`
	CreatedAt string `json:"createdAt"`
	// description: Optional description of the badge.
	Description *string `json:"description,omitempty"`
	// image: Badge icon image.
	Image *glexrt.Blob `json:"image,omitempty"`
	// name: Display name for this badge.
	Name string `json:"name"`
}

func (t *BadgeDef) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.badge.def"
	return glexrt.MarshalCBOR(w, t)
}

func (t *BadgeDef) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
