// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.branding.deleteBlob

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type BrandingDeleteBlob_Input struct {
	LexiconTypeID string `json:"$type"`
	// broadcaster: DID of the broadcaster. If not provided, uses the server's default broadcaster.
	Broadcaster *string `json:"broadcaster,omitempty"`
	// key: Branding asset key (mainLogo, favicon, siteTitle, etc.)
	Key string `json:"key"`
}

func (t *BrandingDeleteBlob_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.branding.deleteBlob#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *BrandingDeleteBlob_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type BrandingDeleteBlob_Output struct {
	LexiconTypeID string `json:"$type"`
	Success       bool   `json:"success"`
}

func (t *BrandingDeleteBlob_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.branding.deleteBlob#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *BrandingDeleteBlob_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// BrandingDeleteBlob calls the XRPC method "place.stream.branding.deleteBlob".
//
// Delete a branding asset blob. Requires admin authorization.
func BrandingDeleteBlob(ctx context.Context, c glexrt.LexClient, input *BrandingDeleteBlob_Input) (*BrandingDeleteBlob_Output, error) {
	var out BrandingDeleteBlob_Output

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "place.stream.branding.deleteBlob", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
