// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.branding.importBundle

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type BrandingImportBundle_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// applied: False for a dry run.
	Applied  bool                          `json:"applied"`
	Changes  []BrandingImportBundle_Change `json:"changes"`
	Warnings []string                      `json:"warnings,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *BrandingImportBundle_Output) RecordTypeID() string {
	return "place.stream.branding.importBundle"
}

func (t *BrandingImportBundle_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.branding.importBundle"
	return glex.MarshalCBOR(w, &cp)
}

func (t *BrandingImportBundle_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// BrandingImportBundle calls the XRPC method "place.stream.branding.importBundle".
//
// Apply a branding bundle (see exportBundle). By default the bundle replaces the node's branding: keys it does not mention are removed. Every value is validated like updateBlob. Requires admin authorization.
//
// broadcaster: DID of the broadcaster. Defaults to this node's.
// dryRun: Report what would change without writing anything.
// merge: Keep keys the bundle does not mention instead of removing them.
func BrandingImportBundle(ctx context.Context, c glex.LexClient, broadcaster string, dryRun *bool, merge *bool, input io.Reader) (*BrandingImportBundle_Output, error) {
	var out BrandingImportBundle_Output

	params := map[string]interface{}{}
	if broadcaster != "" {
		params["broadcaster"] = broadcaster
	}
	if dryRun != nil {
		params["dryRun"] = *dryRun
	}
	if merge != nil {
		params["merge"] = *merge
	}

	if err := c.LexDo(ctx, glex.Procedure, "application/zip", "place.stream.branding.importBundle", params, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// BrandingImportBundle_Change is a "change" in the place.stream.branding.importBundle schema.
type BrandingImportBundle_Change struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Action        string `json:"action"`
	// detail: The new text value, or the image's type and size.
	Detail *string `json:"detail,omitempty"`
	Key    string  `json:"key"`
}

// RecordTypeID implements glex.Record.
func (t *BrandingImportBundle_Change) RecordTypeID() string {
	return "place.stream.branding.importBundle#change"
}

func (t *BrandingImportBundle_Change) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.branding.importBundle#change"
	return glex.MarshalCBOR(w, &cp)
}

func (t *BrandingImportBundle_Change) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
