// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.branding.getBlob

package placestream

import (
	"bytes"
	"context"

	glex "github.com/streamplace/glex/runtime"
)

// BrandingGetBlob calls the XRPC method "place.stream.branding.getBlob".
//
// Get a specific branding asset blob by key.
//
// broadcaster: DID of the broadcaster. If not provided, uses the server's default broadcaster.
// key: Branding asset key (mainLogo, favicon, siteTitle, etc.)
func BrandingGetBlob(ctx context.Context, c glex.LexClient, broadcaster string, key string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if broadcaster != "" {
		params["broadcaster"] = broadcaster
	}
	params["key"] = key

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.branding.getBlob", params, nil, buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
