// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.caption.getCaptions

package placestream

import (
	"bytes"
	"context"

	glex "github.com/streamplace/glex/runtime"
)

// CaptionGetCaptions calls the XRPC method "place.stream.caption.getCaptions".
//
// Download one caption track as WebVTT, SRT, or JSON cues. For live streams this returns the captions in the node's current window, with times counted from the window's epoch (the start of the first segment the node holds; JSON carries it as `epoch`). For videos times count from the video start. `start`, `end`, and `mpegts` make a response usable as an HLS WebVTT subtitle segment.
//
// end: End of the cue range in milliseconds. Videos only.
// mpegts: Adds an X-TIMESTAMP-MAP header (MPEGTS:<value>,LOCAL:00:00:00.000) to a WebVTT response: the 90kHz media timestamp that cue time zero plays at. Used by HLS subtitle playlists.
// start: Only cues overlapping [start, end), in milliseconds from the video start. Videos only.
// streamer: DID or handle of a live streamer. Mutually exclusive with video.
// track: Track id from listTracks.
func CaptionGetCaptions(ctx context.Context, c glex.LexClient, end *int64, format string, mpegts *int64, start *int64, streamer string, track string, video string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if end != nil {
		params["end"] = *end
	}
	if format != "" {
		params["format"] = format
	}
	if mpegts != nil {
		params["mpegts"] = *mpegts
	}
	if start != nil {
		params["start"] = *start
	}
	if streamer != "" {
		params["streamer"] = streamer
	}
	if video != "" {
		params["video"] = video
	}
	params["track"] = track

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.caption.getCaptions", params, nil, buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
