// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.chat.profile

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	comatproto "stream.place/streamplace/pkg/comatproto"
)

func init() {
	glexrt.RegisterType("place.stream.chat.profile", &ChatProfile{})
}

// Record containing customizations for a user's chat profile.
type ChatProfile struct {
	LexiconTypeID string `json:"$type"`
	// badges: Badge selections for display in chat.
	Badges *ChatProfile_BadgeSelections `json:"badges,omitempty"`
	Color  *ChatProfile_Color           `json:"color,omitempty"`
	// selfLabels: Self-applied labels for this profile, e.g. 'bot'.
	SelfLabels []string `json:"selfLabels,omitempty"`
}

func (t *ChatProfile) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.chat.profile"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ChatProfile) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ChatProfile_BadgeSelections is a "badgeSelections" in the place.stream.chat.profile schema.
//
// Selected badges for display in chat, organized by slot.
type ChatProfile_BadgeSelections struct {
	LexiconTypeID string `json:"$type"`
	// global: Selected globally-issued badge (e.g. event badge).
	Global *comatproto.RepoStrongRef `json:"global,omitempty"`
	// streamer: Selected streamer-issued badges, one per streamer channel.
	Streamer []ChatProfile_StreamerBadgeSelection `json:"streamer,omitempty"`
}

func (t *ChatProfile_BadgeSelections) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.chat.profile"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ChatProfile_BadgeSelections) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ChatProfile_Color is a "color" in the place.stream.chat.profile schema.
//
// Customizations for the color of a user's name in chat
type ChatProfile_Color struct {
	LexiconTypeID string `json:"$type"`
	Blue          int64  `json:"blue"`
	Green         int64  `json:"green"`
	Red           int64  `json:"red"`
}

func (t *ChatProfile_Color) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.chat.profile"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ChatProfile_Color) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ChatProfile_StreamerBadgeSelection is a "streamerBadgeSelection" in the place.stream.chat.profile schema.
//
// A selected badge for a specific streamer's channel.
type ChatProfile_StreamerBadgeSelection struct {
	LexiconTypeID string `json:"$type"`
	// badge: Strong reference to the selected place.stream.badge.issuance record.
	Badge comatproto.RepoStrongRef `json:"badge"`
	// streamer: DID of the streamer whose channel this selection applies to.
	Streamer string `json:"streamer"`
}

func (t *ChatProfile_StreamerBadgeSelection) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.chat.profile"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ChatProfile_StreamerBadgeSelection) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
