// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.clip.gate

package placestream

import (
	"encoding/json"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	comatproto "stream.place/streamplace/pkg/comatproto"
)

func init() {
	glex.RegisterType("place.stream.clip.gate", &ClipGate{})
}

// Record defining a gated (hidden) clip. Created in the streamer's repository by a moderator with the 'clip.hide' permission. When present, the referenced clip is hidden from display on this node.
type ClipGate struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// hiddenClip: The place.stream.clip.entry record being hidden.
	HiddenClip comatproto.RepoStrongRef `json:"hiddenClip"`
}

// RecordTypeID implements glex.Record.
func (t *ClipGate) RecordTypeID() string { return "place.stream.clip.gate" }

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// ClipGate and *ClipGate marshal with $type.
func (t ClipGate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "place.stream.clip.gate"
	type alias ClipGate
	return json.Marshal((alias)(t))
}

func (t *ClipGate) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.clip.gate"
	return glex.MarshalCBOR(w, &cp)
}

func (t *ClipGate) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
