// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.clip.create

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ClipCreate_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// durationMs: Duration of content to grab from the buffer, in milliseconds. Defaults to 60 seconds. Maximum is the buffer window (120 seconds).
	DurationMs *int64 `json:"durationMs,omitempty"`
	// streamer: The DID of the streamer whose live broadcast is being clipped.
	Streamer string `json:"streamer"`
}

// RecordTypeID implements glex.Record.
func (t *ClipCreate_Input) RecordTypeID() string { return "place.stream.clip.create" }

func (t *ClipCreate_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.clip.create"
	return glex.MarshalCBOR(w, &cp)
}

func (t *ClipCreate_Input) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type ClipCreate_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// clipId: ID of the created ephemeral clip. Pass to place.stream.clip.publish within 10 minutes.
	ClipId string `json:"clipId"`
	// durationMs: Actual duration of the muxed content, in milliseconds. May be less than requested if the buffer had fewer segments.
	DurationMs int64 `json:"durationMs"`
	// expiresAt: When the ephemeral clip file and draft will be deleted. Always 10 minutes from creation.
	ExpiresAt string `json:"expiresAt"`
	// previewUrl: URL to the ephemeral MP4 for preview in the clip editor. Valid until expiresAt.
	PreviewUrl string `json:"previewUrl"`
}

// RecordTypeID implements glex.Record.
func (t *ClipCreate_Output) RecordTypeID() string { return "place.stream.clip.create" }

func (t *ClipCreate_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.clip.create"
	return glex.MarshalCBOR(w, &cp)
}

func (t *ClipCreate_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// ClipCreate calls the XRPC method "place.stream.clip.create".
//
// Create an ephemeral clip from a streamer's live broadcast. Grabs the last N milliseconds from the streamer's moderation buffer, muxes it into a temporary MP4, and creates a VOD draft pre-filled with the muxed content. The clipper has 10 minutes to edit and publish before the ephemeral file is deleted. Requires the streamer to have clipping enabled (livestreamClipping setting). Rate-limited per viewer and per stream.
func ClipCreate(ctx context.Context, c glex.LexClient, input *ClipCreate_Input) (*ClipCreate_Output, error) {
	var out ClipCreate_Output

	if err := c.LexDo(ctx, glex.Procedure, "application/json", "place.stream.clip.create", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
