// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.defs

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	appbsky "stream.place/streamplace/pkg/appbsky"
)

// Defs_ActivityGame is a "activityGame" in the place.stream.defs schema.
//
// A game from the gamesgamesgamesgames catalog, identified by its AT URI.
type Defs_ActivityGame struct {
	LexiconTypeID string `json:"$type"`
	// name: Cached display name of the game.
	Name *string `json:"name,omitempty"`
	Uri  string  `json:"uri"`
}

func (t *Defs_ActivityGame) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Defs_ActivityGame) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// Defs_ActivityLabel is a "activityLabel" in the place.stream.defs schema.
//
// A non-game activity with a well-known label.
type Defs_ActivityLabel struct {
	LexiconTypeID string `json:"$type"`
	Label         string `json:"label"`
}

func (t *Defs_ActivityLabel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Defs_ActivityLabel) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// Defs_BlockView is a "blockView" in the place.stream.defs schema.
type Defs_BlockView struct {
	LexiconTypeID string                             `json:"$type"`
	Blocker       appbsky.ActorDefs_ProfileViewBasic `json:"blocker"`
	Cid           string                             `json:"cid"`
	IndexedAt     string                             `json:"indexedAt"`
	Record        appbsky.GraphBlock                 `json:"record"`
	Uri           string                             `json:"uri"`
}

func (t *Defs_BlockView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Defs_BlockView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// Defs_Rendition is a "rendition" in the place.stream.defs schema.
type Defs_Rendition struct {
	LexiconTypeID string `json:"$type"`
	Name          string `json:"name"`
}

func (t *Defs_Rendition) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Defs_Rendition) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// Defs_Renditions is a "renditions" in the place.stream.defs schema.
type Defs_Renditions struct {
	LexiconTypeID string           `json:"$type"`
	Renditions    []Defs_Rendition `json:"renditions"`
}

func (t *Defs_Renditions) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Defs_Renditions) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
