// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.game.getGame

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type GameGetGame_Output struct {
	LexiconTypeID string   `json:"$type"`
	CoverUrl      *string  `json:"coverUrl,omitempty"`
	Genres        []string `json:"genres,omitempty"`
	Name          string   `json:"name"`
	Summary       *string  `json:"summary,omitempty"`
	Uri           string   `json:"uri"`
}

func (t *GameGetGame_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.game.getGame#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GameGetGame_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// GameGetGame calls the XRPC method "place.stream.game.getGame".
func GameGetGame(ctx context.Context, c glexrt.LexClient, uri string) (*GameGetGame_Output, error) {
	var out GameGetGame_Output

	params := map[string]interface{}{}
	params["uri"] = uri

	if err := c.LexDo(ctx, glexrt.Query, "", "place.stream.game.getGame", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
