// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.live.searchActorsTypeahead

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type LiveSearchActorsTypeahead_Output struct {
	LexiconTypeID string                            `json:"$type"`
	Actors        []LiveSearchActorsTypeahead_Actor `json:"actors"`
}

func (t *LiveSearchActorsTypeahead_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.live.searchActorsTypeahead#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *LiveSearchActorsTypeahead_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// LiveSearchActorsTypeahead calls the XRPC method "place.stream.live.searchActorsTypeahead".
//
// Find actor suggestions for a prefix search term. Expected use is for auto-completion during text field entry.
//
// q: Search query prefix; not a full query string.
func LiveSearchActorsTypeahead(ctx context.Context, c glexrt.LexClient, limit *int64, q string) (*LiveSearchActorsTypeahead_Output, error) {
	var out LiveSearchActorsTypeahead_Output

	params := map[string]interface{}{}
	if limit != nil {
		params["limit"] = *limit
	}
	if q != "" {
		params["q"] = q
	}

	if err := c.LexDo(ctx, glexrt.Query, "", "place.stream.live.searchActorsTypeahead", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// LiveSearchActorsTypeahead_Actor is a "actor" in the place.stream.live.searchActorsTypeahead schema.
type LiveSearchActorsTypeahead_Actor struct {
	LexiconTypeID string `json:"$type"`
	// did: The actor's DID
	Did string `json:"did"`
	// handle: The actor's handle
	Handle string `json:"handle"`
}

func (t *LiveSearchActorsTypeahead_Actor) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.live.searchActorsTypeahead"
	return glexrt.MarshalCBOR(w, t)
}

func (t *LiveSearchActorsTypeahead_Actor) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
