// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.live.denyTeleport

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type LiveDenyTeleport_Input struct {
	LexiconTypeID string `json:"$type"`
	// uri: The URI of the teleport record to deny.
	Uri string `json:"uri"`
}

func (t *LiveDenyTeleport_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.live.denyTeleport#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *LiveDenyTeleport_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type LiveDenyTeleport_Output struct {
	LexiconTypeID string `json:"$type"`
	// success: Whether the teleport was successfully denied.
	Success bool `json:"success"`
}

func (t *LiveDenyTeleport_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.live.denyTeleport#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *LiveDenyTeleport_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// LiveDenyTeleport calls the XRPC method "place.stream.live.denyTeleport".
//
// Deny an incoming teleport request.
func LiveDenyTeleport(ctx context.Context, c glexrt.LexClient, input *LiveDenyTeleport_Input) (*LiveDenyTeleport_Output, error) {
	var out LiveDenyTeleport_Output

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "place.stream.live.denyTeleport", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
