// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.live.getProfileCard

package placestream

import (
	"bytes"
	"context"

	glex "github.com/streamplace/glex/runtime"
)

// LiveGetProfileCard calls the XRPC method "place.stream.live.getProfileCard".
//
// Get an OG image associated with a given account.
//
// id: The DID or handle of the account.
func LiveGetProfileCard(ctx context.Context, c glex.LexClient, id string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	params["id"] = id

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.live.getProfileCard", params, nil, buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
