// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.livestream

package placestream

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	appbsky "stream.place/streamplace/pkg/appbsky"
	comatproto "stream.place/streamplace/pkg/comatproto"
)

func init() {
	glex.RegisterType("place.stream.livestream", &Livestream{})
}

// Record announcing a livestream is happening
type Livestream struct {
	LexiconTypeID string `json:"$type"`
	// activity: The game or activity being streamed.
	Activity *Livestream_Activity `json:"activity,omitempty"`
	// agent: The source of the livestream, if available, in a User Agent format: `<product> / <product-version> <comment>` e.g. Streamplace/0.7.5 iOS
	Agent *string `json:"agent,omitempty"`
	// canonicalUrl: The primary URL where this livestream can be viewed, if available.
	CanonicalUrl *string `json:"canonicalUrl,omitempty"`
	// createdAt: Client-declared timestamp when this livestream started.
	CreatedAt string `json:"createdAt"`
	// endedAt: Client-declared timestamp when this livestream ended. Ended livestreams are not supposed to start up again.
	EndedAt *string `json:"endedAt,omitempty"`
	// idleTimeoutSeconds: Time in seconds after which this livestream should be automatically ended if idle. Zero means no timeout.
	IdleTimeoutSeconds *int64 `json:"idleTimeoutSeconds,omitempty"`
	// lastSeenAt: Client-declared timestamp when this livestream was last seen by the Streamplace station.
	LastSeenAt           *string                          `json:"lastSeenAt,omitempty"`
	NotificationSettings *Livestream_NotificationSettings `json:"notificationSettings,omitempty"`
	// post: The post that announced this livestream.
	Post *comatproto.RepoStrongRef `json:"post,omitempty"`
	// tags: Freeform tags for this stream. Each tag must be alphanumeric (a-z, A-Z, 0-9) plus colon. Tags with colons indicate a specific tag group (e.g. 'lang:en' indicates the stream's primary language).
	Tags  []string   `json:"tags,omitempty"`
	Thumb *glex.Blob `json:"thumb,omitempty"`
	// title: The title of the livestream, as it will be announced to followers.
	Title string `json:"title"`
	// url: The URL where this stream can be found. This is primarily a hint for other Streamplace nodes to locate and replicate the stream.
	Url *string `json:"url,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream) RecordTypeID() string { return "place.stream.livestream" }

func (t *Livestream) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// The game or activity being streamed.
type Livestream_Activity struct {
	Defs_ActivityGame  *Defs_ActivityGame
	Defs_ActivityLabel *Defs_ActivityLabel
}

func (t *Livestream_Activity) MarshalJSON() ([]byte, error) {
	if t.Defs_ActivityGame != nil {
		t.Defs_ActivityGame.LexiconTypeID = "place.stream.defs#activityGame"
		return json.Marshal(t.Defs_ActivityGame)
	}
	if t.Defs_ActivityLabel != nil {
		t.Defs_ActivityLabel.LexiconTypeID = "place.stream.defs#activityLabel"
		return json.Marshal(t.Defs_ActivityLabel)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *Livestream_Activity) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.defs#activityGame":
		t.Defs_ActivityGame = new(Defs_ActivityGame)
		return json.Unmarshal(b, t.Defs_ActivityGame)
	case "place.stream.defs#activityLabel":
		t.Defs_ActivityLabel = new(Defs_ActivityLabel)
		return json.Unmarshal(b, t.Defs_ActivityLabel)
	default:
		return nil
	}
}

func (t *Livestream_Activity) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.Defs_ActivityGame != nil {
		return t.Defs_ActivityGame.MarshalCBOR(w)
	}
	if t.Defs_ActivityLabel != nil {
		return t.Defs_ActivityLabel.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *Livestream_Activity) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glex.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.defs#activityGame":
		t.Defs_ActivityGame = new(Defs_ActivityGame)
		return t.Defs_ActivityGame.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.defs#activityLabel":
		t.Defs_ActivityLabel = new(Defs_ActivityLabel)
		return t.Defs_ActivityLabel.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// Livestream_LivestreamView is a "livestreamView" in the place.stream.livestream schema.
type Livestream_LivestreamView struct {
	LexiconTypeID string                             `json:"$type"`
	Author        appbsky.ActorDefs_ProfileViewBasic `json:"author"`
	Cid           string                             `json:"cid"`
	IndexedAt     string                             `json:"indexedAt"`
	Record        *glex.LexiconTypeDecoder           `json:"record"`
	Uri           string                             `json:"uri"`
	// viewerCount: The number of viewers watching this livestream. Use when you can't reasonably use #viewerCount directly.
	ViewerCount *Livestream_ViewerCount `json:"viewerCount,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_LivestreamView) RecordTypeID() string {
	return "place.stream.livestream#livestreamView"
}

func (t *Livestream_LivestreamView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#livestreamView"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_LivestreamView) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// Livestream_NotificationSettings is a "notificationSettings" in the place.stream.livestream schema.
type Livestream_NotificationSettings struct {
	LexiconTypeID string `json:"$type"`
	// pushNotification: Whether this livestream should trigger a push notification to followers.
	PushNotification *bool `json:"pushNotification,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_NotificationSettings) RecordTypeID() string {
	return "place.stream.livestream#notificationSettings"
}

func (t *Livestream_NotificationSettings) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#notificationSettings"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_NotificationSettings) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// Livestream_StreamplaceAnything is a "streamplaceAnything" in the place.stream.livestream schema.
type Livestream_StreamplaceAnything struct {
	LexiconTypeID string                                    `json:"$type"`
	Livestream    Livestream_StreamplaceAnything_Livestream `json:"livestream"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_StreamplaceAnything) RecordTypeID() string {
	return "place.stream.livestream#streamplaceAnything"
}

func (t *Livestream_StreamplaceAnything) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#streamplaceAnything"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_StreamplaceAnything) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type Livestream_StreamplaceAnything_Livestream struct {
	ChatDefs_MessageView        *ChatDefs_MessageView
	ChatDefs_PinnedRecordView   *ChatDefs_PinnedRecordView
	Defs_BlockView              *Defs_BlockView
	Defs_Rendition              *Defs_Rendition
	Defs_Renditions             *Defs_Renditions
	Livestream_LivestreamView   *Livestream_LivestreamView
	Livestream_TeleportArrival  *Livestream_TeleportArrival
	Livestream_TeleportCanceled *Livestream_TeleportCanceled
	Livestream_ViewerCount      *Livestream_ViewerCount
}

func (t *Livestream_StreamplaceAnything_Livestream) MarshalJSON() ([]byte, error) {
	if t.ChatDefs_MessageView != nil {
		t.ChatDefs_MessageView.LexiconTypeID = "place.stream.chat.defs#messageView"
		return json.Marshal(t.ChatDefs_MessageView)
	}
	if t.ChatDefs_PinnedRecordView != nil {
		t.ChatDefs_PinnedRecordView.LexiconTypeID = "place.stream.chat.defs#pinnedRecordView"
		return json.Marshal(t.ChatDefs_PinnedRecordView)
	}
	if t.Defs_BlockView != nil {
		t.Defs_BlockView.LexiconTypeID = "place.stream.defs#blockView"
		return json.Marshal(t.Defs_BlockView)
	}
	if t.Defs_Rendition != nil {
		t.Defs_Rendition.LexiconTypeID = "place.stream.defs#rendition"
		return json.Marshal(t.Defs_Rendition)
	}
	if t.Defs_Renditions != nil {
		t.Defs_Renditions.LexiconTypeID = "place.stream.defs#renditions"
		return json.Marshal(t.Defs_Renditions)
	}
	if t.Livestream_LivestreamView != nil {
		t.Livestream_LivestreamView.LexiconTypeID = "place.stream.livestream#livestreamView"
		return json.Marshal(t.Livestream_LivestreamView)
	}
	if t.Livestream_TeleportArrival != nil {
		t.Livestream_TeleportArrival.LexiconTypeID = "place.stream.livestream#teleportArrival"
		return json.Marshal(t.Livestream_TeleportArrival)
	}
	if t.Livestream_TeleportCanceled != nil {
		t.Livestream_TeleportCanceled.LexiconTypeID = "place.stream.livestream#teleportCanceled"
		return json.Marshal(t.Livestream_TeleportCanceled)
	}
	if t.Livestream_ViewerCount != nil {
		t.Livestream_ViewerCount.LexiconTypeID = "place.stream.livestream#viewerCount"
		return json.Marshal(t.Livestream_ViewerCount)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *Livestream_StreamplaceAnything_Livestream) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.chat.defs#messageView":
		t.ChatDefs_MessageView = new(ChatDefs_MessageView)
		return json.Unmarshal(b, t.ChatDefs_MessageView)
	case "place.stream.chat.defs#pinnedRecordView":
		t.ChatDefs_PinnedRecordView = new(ChatDefs_PinnedRecordView)
		return json.Unmarshal(b, t.ChatDefs_PinnedRecordView)
	case "place.stream.defs#blockView":
		t.Defs_BlockView = new(Defs_BlockView)
		return json.Unmarshal(b, t.Defs_BlockView)
	case "place.stream.defs#rendition":
		t.Defs_Rendition = new(Defs_Rendition)
		return json.Unmarshal(b, t.Defs_Rendition)
	case "place.stream.defs#renditions":
		t.Defs_Renditions = new(Defs_Renditions)
		return json.Unmarshal(b, t.Defs_Renditions)
	case "place.stream.livestream#livestreamView":
		t.Livestream_LivestreamView = new(Livestream_LivestreamView)
		return json.Unmarshal(b, t.Livestream_LivestreamView)
	case "place.stream.livestream#teleportArrival":
		t.Livestream_TeleportArrival = new(Livestream_TeleportArrival)
		return json.Unmarshal(b, t.Livestream_TeleportArrival)
	case "place.stream.livestream#teleportCanceled":
		t.Livestream_TeleportCanceled = new(Livestream_TeleportCanceled)
		return json.Unmarshal(b, t.Livestream_TeleportCanceled)
	case "place.stream.livestream#viewerCount":
		t.Livestream_ViewerCount = new(Livestream_ViewerCount)
		return json.Unmarshal(b, t.Livestream_ViewerCount)
	default:
		return nil
	}
}

func (t *Livestream_StreamplaceAnything_Livestream) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.ChatDefs_MessageView != nil {
		return t.ChatDefs_MessageView.MarshalCBOR(w)
	}
	if t.ChatDefs_PinnedRecordView != nil {
		return t.ChatDefs_PinnedRecordView.MarshalCBOR(w)
	}
	if t.Defs_BlockView != nil {
		return t.Defs_BlockView.MarshalCBOR(w)
	}
	if t.Defs_Rendition != nil {
		return t.Defs_Rendition.MarshalCBOR(w)
	}
	if t.Defs_Renditions != nil {
		return t.Defs_Renditions.MarshalCBOR(w)
	}
	if t.Livestream_LivestreamView != nil {
		return t.Livestream_LivestreamView.MarshalCBOR(w)
	}
	if t.Livestream_TeleportArrival != nil {
		return t.Livestream_TeleportArrival.MarshalCBOR(w)
	}
	if t.Livestream_TeleportCanceled != nil {
		return t.Livestream_TeleportCanceled.MarshalCBOR(w)
	}
	if t.Livestream_ViewerCount != nil {
		return t.Livestream_ViewerCount.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *Livestream_StreamplaceAnything_Livestream) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glex.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.chat.defs#messageView":
		t.ChatDefs_MessageView = new(ChatDefs_MessageView)
		return t.ChatDefs_MessageView.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.chat.defs#pinnedRecordView":
		t.ChatDefs_PinnedRecordView = new(ChatDefs_PinnedRecordView)
		return t.ChatDefs_PinnedRecordView.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.defs#blockView":
		t.Defs_BlockView = new(Defs_BlockView)
		return t.Defs_BlockView.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.defs#rendition":
		t.Defs_Rendition = new(Defs_Rendition)
		return t.Defs_Rendition.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.defs#renditions":
		t.Defs_Renditions = new(Defs_Renditions)
		return t.Defs_Renditions.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.livestream#livestreamView":
		t.Livestream_LivestreamView = new(Livestream_LivestreamView)
		return t.Livestream_LivestreamView.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.livestream#teleportArrival":
		t.Livestream_TeleportArrival = new(Livestream_TeleportArrival)
		return t.Livestream_TeleportArrival.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.livestream#teleportCanceled":
		t.Livestream_TeleportCanceled = new(Livestream_TeleportCanceled)
		return t.Livestream_TeleportCanceled.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.livestream#viewerCount":
		t.Livestream_ViewerCount = new(Livestream_ViewerCount)
		return t.Livestream_ViewerCount.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// Livestream_TeleportArrival is a "teleportArrival" in the place.stream.livestream schema.
type Livestream_TeleportArrival struct {
	LexiconTypeID string `json:"$type"`
	// chatProfile: The chat profile of the source streamer
	ChatProfile *ChatProfile `json:"chatProfile,omitempty"`
	// source: The streamer who is teleporting their viewers here
	Source appbsky.ActorDefs_ProfileViewBasic `json:"source"`
	// startsAt: When this teleport started
	StartsAt string `json:"startsAt"`
	// teleportUri: The URI of the teleport record
	TeleportUri string `json:"teleportUri"`
	// viewerCount: How many viewers are arriving from this teleport
	ViewerCount int64 `json:"viewerCount"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_TeleportArrival) RecordTypeID() string {
	return "place.stream.livestream#teleportArrival"
}

func (t *Livestream_TeleportArrival) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#teleportArrival"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_TeleportArrival) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// Livestream_TeleportCanceled is a "teleportCanceled" in the place.stream.livestream schema.
type Livestream_TeleportCanceled struct {
	LexiconTypeID string `json:"$type"`
	// reason: Why this teleport was canceled
	Reason string `json:"reason"`
	// teleportUri: The URI of the teleport record that was canceled
	TeleportUri string `json:"teleportUri"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_TeleportCanceled) RecordTypeID() string {
	return "place.stream.livestream#teleportCanceled"
}

func (t *Livestream_TeleportCanceled) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#teleportCanceled"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_TeleportCanceled) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// Livestream_ViewerCount is a "viewerCount" in the place.stream.livestream schema.
type Livestream_ViewerCount struct {
	LexiconTypeID string `json:"$type"`
	Count         int64  `json:"count"`
}

// RecordTypeID implements glex.Record.
func (t *Livestream_ViewerCount) RecordTypeID() string { return "place.stream.livestream#viewerCount" }

func (t *Livestream_ViewerCount) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.livestream#viewerCount"
	return glex.MarshalCBOR(w, t)
}

func (t *Livestream_ViewerCount) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
