// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.media.getVideoList

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type MediaGetVideoList_Output struct {
	LexiconTypeID string `json:"$type"`
	// cursor: Pagination cursor for the next page, if any.
	Cursor *string                   `json:"cursor,omitempty"`
	Videos []MediaGetVideo_VideoView `json:"videos"`
}

func (t *MediaGetVideoList_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.media.getVideoList#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *MediaGetVideoList_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// MediaGetVideoList calls the XRPC method "place.stream.media.getVideoList".
//
// List videos newest first. Scoped to a single repo when `repo` is supplied; otherwise lists videos across every indexed repo. Returns hydrated video views with author info and view counts.
//
// cursor: Pagination cursor from a previous response.
// limit: Maximum number of videos to return.
// repo: DID or handle of the repo whose videos to list. Omit to list videos globally across all repos.
func MediaGetVideoList(ctx context.Context, c glexrt.LexClient, cursor string, limit *int64, repo string) (*MediaGetVideoList_Output, error) {
	var out MediaGetVideoList_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	if repo != "" {
		params["repo"] = repo
	}

	if err := c.LexDo(ctx, glexrt.Query, "", "place.stream.media.getVideoList", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
