// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.media.deleteVideo

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type MediaDeleteVideo_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// tracks: Also delete the video's track records.
	Tracks *bool  `json:"tracks,omitempty"`
	Uri    string `json:"uri"`
}

// RecordTypeID implements glex.Record.
func (t *MediaDeleteVideo_Input) RecordTypeID() string { return "place.stream.media.deleteVideo" }

func (t *MediaDeleteVideo_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.media.deleteVideo"
	return glex.MarshalCBOR(w, &cp)
}

func (t *MediaDeleteVideo_Input) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type MediaDeleteVideo_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// deleted: Every record deleted, the video first.
	Deleted []string `json:"deleted"`
}

// RecordTypeID implements glex.Record.
func (t *MediaDeleteVideo_Output) RecordTypeID() string { return "place.stream.media.deleteVideo" }

func (t *MediaDeleteVideo_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.media.deleteVideo"
	return glex.MarshalCBOR(w, &cp)
}

func (t *MediaDeleteVideo_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// MediaDeleteVideo calls the XRPC method "place.stream.media.deleteVideo".
//
// Delete a place.stream.video record and, on request, the track records its source points at. The content blob and the upload stay, so the record can be published again from the same upload. The caller must be the record's owner or hold livestream.manage from them; the records are deleted with the owner's session.
func MediaDeleteVideo(ctx context.Context, c glex.LexClient, input *MediaDeleteVideo_Input) (*MediaDeleteVideo_Output, error) {
	var out MediaDeleteVideo_Output

	if err := c.LexDo(ctx, glex.Procedure, "application/json", "place.stream.media.deleteVideo", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
