// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.metadata.captionPolicy

package placestream

import (
	"encoding/json"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("place.stream.metadata.captionPolicy#main", &MetadataCaptionPolicy{})
}

// Captioning preferences for a streamer's content. Travels with the metadata configuration into every minted segment, so relays see the same policy as the origin.
type MetadataCaptionPolicy struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// allowNodeCaptions: Whether nodes may generate and distribute their own captions for accessibility when the canonical stream has none. Absent means allowed.
	AllowNodeCaptions *bool `json:"allowNodeCaptions,omitempty"`
	// canonical: How the canonical caption track is produced. auto (the default when absent): the origin node transcribes speech and masters a caption track into the canonical stream. ingest: the streamer supplies canonical captions at ingest (CEA-608/708 embedded in the video, or place.stream.caption.pushCaptions) and nodes do not transcribe. off: the canonical stream carries no captions.
	Canonical *string `json:"canonical,omitempty"`
	// languages: Spoken languages of the content, most prominent first. A hint for speech recognition; absent means detect automatically.
	Languages []string `json:"languages,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *MetadataCaptionPolicy) RecordTypeID() string { return "place.stream.metadata.captionPolicy" }

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// MetadataCaptionPolicy and *MetadataCaptionPolicy marshal with $type.
func (t MetadataCaptionPolicy) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "place.stream.metadata.captionPolicy"
	type alias MetadataCaptionPolicy
	return json.Marshal((alias)(t))
}

func (t *MetadataCaptionPolicy) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.metadata.captionPolicy"
	return glex.MarshalCBOR(w, &cp)
}

func (t *MetadataCaptionPolicy) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
