// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.metadata.distributionPolicy

package placestream

import (
	"encoding/json"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("place.stream.metadata.distributionPolicy#main", &MetadataDistributionPolicy{})
}

// Distribution and rebroadcast policy.
type MetadataDistributionPolicy struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// allowGenAiTraining: Whether this content may be used as training data for generative AI models. Absent means undeclared; Streamplace treats undeclared as false and stamps an explicit value into every minted segment. Covers generative AI only — non-generative machine learning (e.g. moderation, accessibility, speech models) is not governed by this flag.
	AllowGenAiTraining *bool `json:"allowGenAiTraining,omitempty"`
	// allowedBroadcasters: List of did:webs of the broadcasters you want to allow to distribute your content. "*" allows anyone. Starting a line with a "!" bans that broadcaster.
	AllowedBroadcasters []string `json:"allowedBroadcasters,omitempty"`
	// deleteAfter: Duration in seconds after which segments should be deleted. Each segment will expire N seconds after its creation time. -1 to allow indefinite archival.
	DeleteAfter *int64 `json:"deleteAfter,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *MetadataDistributionPolicy) RecordTypeID() string {
	return "place.stream.metadata.distributionPolicy"
}

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// MetadataDistributionPolicy and *MetadataDistributionPolicy marshal with $type.
func (t MetadataDistributionPolicy) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "place.stream.metadata.distributionPolicy"
	type alias MetadataDistributionPolicy
	return json.Marshal((alias)(t))
}

func (t *MetadataDistributionPolicy) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.metadata.distributionPolicy"
	return glex.MarshalCBOR(w, &cp)
}

func (t *MetadataDistributionPolicy) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
