// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.metadata.contentRights

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glexrt.RegisterType("place.stream.metadata.contentRights#main", &MetadataContentRights{})
}

// Content rights and attribution information.
type MetadataContentRights struct {
	LexiconTypeID string `json:"$type"`
	// copyrightNotice: Copyright notice for the work.
	CopyrightNotice *string `json:"copyrightNotice,omitempty"`
	// copyrightYear: Year of creation or publication.
	CopyrightYear *int64 `json:"copyrightYear,omitempty"`
	// creator: Name of the creator of the work.
	Creator *string `json:"creator,omitempty"`
	// creditLine: Credit line for the work.
	CreditLine *string `json:"creditLine,omitempty"`
	// license: License URL or identifier.
	License *string `json:"license,omitempty"`
}

func (t *MetadataContentRights) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.metadata.contentRights"
	return glexrt.MarshalCBOR(w, t)
}

func (t *MetadataContentRights) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
