// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.multistream.defs

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

// MultistreamDefs_Event is a "event" in the place.stream.multistream.defs schema.
type MultistreamDefs_Event struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt"`
	Message       string `json:"message"`
	Status        string `json:"status"`
}

func (t *MultistreamDefs_Event) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.multistream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *MultistreamDefs_Event) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// MultistreamDefs_TargetView is a "targetView" in the place.stream.multistream.defs schema.
type MultistreamDefs_TargetView struct {
	LexiconTypeID string                     `json:"$type"`
	Cid           string                     `json:"cid"`
	LatestEvent   *MultistreamDefs_Event     `json:"latestEvent,omitempty"`
	Record        *glexrt.LexiconTypeDecoder `json:"record"`
	Uri           string                     `json:"uri"`
}

func (t *MultistreamDefs_TargetView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.multistream.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *MultistreamDefs_TargetView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
