// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.playback.getPlaybackServer

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type PlaybackGetPlaybackServer_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// servers: List of available playback server addresses
	Servers []string `json:"servers"`
}

// RecordTypeID implements glex.Record.
func (t *PlaybackGetPlaybackServer_Output) RecordTypeID() string {
	return "place.stream.playback.getPlaybackServer"
}

func (t *PlaybackGetPlaybackServer_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.playback.getPlaybackServer"
	return glex.MarshalCBOR(w, &cp)
}

func (t *PlaybackGetPlaybackServer_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// PlaybackGetPlaybackServer calls the XRPC method "place.stream.playback.getPlaybackServer".
//
// Get available playback servers for a livestream.
//
// stream: Identifier of the stream to get playback servers for
func PlaybackGetPlaybackServer(ctx context.Context, c glex.LexClient, stream string) (*PlaybackGetPlaybackServer_Output, error) {
	var out PlaybackGetPlaybackServer_Output

	params := map[string]interface{}{}
	params["stream"] = stream

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.playback.getPlaybackServer", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
