// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.playback.getPlaybackServer

package placestream

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type PlaybackGetPlaybackServer_Output struct {
	LexiconTypeID string `json:"$type"`
	// servers: List of available playback server addresses
	Servers []string `json:"servers"`
}

func (t *PlaybackGetPlaybackServer_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.playback.getPlaybackServer#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *PlaybackGetPlaybackServer_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// PlaybackGetPlaybackServer calls the XRPC method "place.stream.playback.getPlaybackServer".
//
// Get available playback servers for a livestream.
//
// stream: Identifier of the stream to get playback servers for
func PlaybackGetPlaybackServer(ctx context.Context, c glexrt.LexClient, stream string) (*PlaybackGetPlaybackServer_Output, error) {
	var out PlaybackGetPlaybackServer_Output

	params := map[string]interface{}{}
	params["stream"] = stream

	if err := c.LexDo(ctx, glexrt.Query, "", "place.stream.playback.getPlaybackServer", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
