// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.server.getPreferences

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ServerGetPreferences_Output struct {
	LexiconTypeID string                 `json:"$type,omitempty"`
	Preferences   ServerDefs_Preferences `json:"preferences"`
}

// RecordTypeID implements glex.Record.
func (t *ServerGetPreferences_Output) RecordTypeID() string {
	return "place.stream.server.getPreferences"
}

func (t *ServerGetPreferences_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "place.stream.server.getPreferences"
	return glex.MarshalCBOR(w, &cp)
}

func (t *ServerGetPreferences_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// ServerGetPreferences calls the XRPC method "place.stream.server.getPreferences".
//
// Get the authenticated user's private preferences on this node.
func ServerGetPreferences(ctx context.Context, c glex.LexClient) (*ServerGetPreferences_Output, error) {
	var out ServerGetPreferences_Output

	if err := c.LexDo(ctx, glex.Query, "", "place.stream.server.getPreferences", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
