// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.server.deleteStorage

package placestream

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ServerDeleteStorage_Output struct {
	LexiconTypeID string `json:"$type"`
	Success       bool   `json:"success"`
}

// RecordTypeID implements glex.Record.
func (t *ServerDeleteStorage_Output) RecordTypeID() string {
	return "place.stream.server.deleteStorage"
}

func (t *ServerDeleteStorage_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.server.deleteStorage"
	return glex.MarshalCBOR(w, t)
}

func (t *ServerDeleteStorage_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// ServerDeleteStorage calls the XRPC method "place.stream.server.deleteStorage".
//
// Delete S3 storage configuration.
func ServerDeleteStorage(ctx context.Context, c glex.LexClient) (*ServerDeleteStorage_Output, error) {
	var out ServerDeleteStorage_Output

	if err := c.LexDo(ctx, glex.Procedure, "", "place.stream.server.deleteStorage", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
