// Code generated by glex; DO NOT EDIT.

// Lexicon schema: place.stream.server.settings

package placestream

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glexrt.RegisterType("place.stream.server.settings", &ServerSettings{})
}

// Record containing user settings for a particular Streamplace node
type ServerSettings struct {
	LexiconTypeID string `json:"$type"`
	// debugRecording: Whether this node may archive your livestream for improving the service
	DebugRecording *bool `json:"debugRecording,omitempty"`
	// livestreamRecording: Whether this node should record your livestreams into VODs that you can publish
	LivestreamRecording *bool `json:"livestreamRecording,omitempty"`
}

func (t *ServerSettings) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.server.settings"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ServerSettings) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
