// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.badge.def

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Defines a badge's visual appearance and type. Created by the issuer and referenced by issuance records.
type BadgeDef struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.badge.def"`
	// badgeType: The category of this badge, used for scope and display rules.
	BadgeType string `json:"badgeType" cborgen:"badgeType"`
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// description: Optional description of the badge.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// image: Badge icon image.
	Image *lexutil.LexBlob `json:"image,omitempty" cborgen:"image,omitempty"`
	// name: Display name for this badge.
	Name string `json:"name" cborgen:"name"`
}
