// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.broadcast.defs

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// BroadcastDefs_BroadcastOriginView is a "broadcastOriginView" in the place.stream.broadcast.defs schema.
type BroadcastDefs_BroadcastOriginView struct {
	LexiconTypeID string                             `json:"$type,omitempty" cborgen:"$type,const=place.stream.broadcast.defs#broadcastOriginView,omitempty"`
	Author        appbsky.ActorDefs_ProfileViewBasic `json:"author" cborgen:"author"`
	Cid           string                             `json:"cid" cborgen:"cid"`
	Record        map[string]any                     `json:"record" cborgen:"record"`
	Uri           string                             `json:"uri" cborgen:"uri"`
}
