// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.broadcast.syndication

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Record created by a Streamplace broadcaster to indicate that they will be replicating a livestream. NYI
type BroadcastSyndication struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.broadcast.syndication"`
	// broadcaster: DID of the Streamplace broadcaster that will be replicating the livestream
	Broadcaster string `json:"broadcaster" cborgen:"broadcaster"`
	// createdAt: Client-declared timestamp when this syndication was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// streamer: DID of the streamer whose livestream is being replicated
	Streamer string `json:"streamer" cborgen:"streamer"`
}
