// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.chat.profile

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Record containing customizations for a user's chat profile.
type ChatProfile struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.chat.profile"`
	// badges: Badge selections for display in chat.
	Badges *ChatProfile_BadgeSelections `json:"badges,omitempty" cborgen:"badges,omitempty"`
	Color  *ChatProfile_Color           `json:"color,omitempty" cborgen:"color,omitempty"`
	// selfLabels: Self-applied labels for this profile, e.g. 'bot'.
	SelfLabels []string `json:"selfLabels,omitempty" cborgen:"selfLabels,omitempty"`
}

// ChatProfile_BadgeSelections is a "badgeSelections" in the place.stream.chat.profile schema.
//
// Selected badges for display in chat, organized by slot.
type ChatProfile_BadgeSelections struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=place.stream.chat.profile#badgeSelections,omitempty"`
	// global: Selected globally-issued badge (e.g. event badge).
	Global *comatproto.RepoStrongRef `json:"global,omitempty" cborgen:"global,omitempty"`
	// streamer: Selected streamer-issued badges, one per streamer channel.
	Streamer []ChatProfile_StreamerBadgeSelection `json:"streamer,omitempty" cborgen:"streamer,omitempty"`
}

// ChatProfile_Color is a "color" in the place.stream.chat.profile schema.
//
// Customizations for the color of a user's name in chat
type ChatProfile_Color struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=place.stream.chat.profile#color,omitempty"`
	Blue          int64  `json:"blue" cborgen:"blue"`
	Green         int64  `json:"green" cborgen:"green"`
	Red           int64  `json:"red" cborgen:"red"`
}

// ChatProfile_StreamerBadgeSelection is a "streamerBadgeSelection" in the place.stream.chat.profile schema.
//
// A selected badge for a specific streamer's channel.
type ChatProfile_StreamerBadgeSelection struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=place.stream.chat.profile#streamerBadgeSelection,omitempty"`
	// badge: Strong reference to the selected place.stream.badge.issuance record.
	Badge comatproto.RepoStrongRef `json:"badge" cborgen:"badge"`
	// streamer: DID of the streamer whose channel this selection applies to.
	Streamer string `json:"streamer" cborgen:"streamer"`
}
