// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.metadata.distributionPolicy

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Distribution and rebroadcast policy.
type MetadataDistributionPolicy struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=place.stream.metadata.distributionPolicy,omitempty"`
	// allowedBroadcasters: List of did:webs of the broadcasters you want to allow to distribute your content. "*" allows anyone. Starting a line with a "!" bans that broadcaster.
	AllowedBroadcasters []string `json:"allowedBroadcasters,omitempty" cborgen:"allowedBroadcasters,omitempty"`
	// deleteAfter: Duration in seconds after which segments should be deleted. Each segment will expire N seconds after its creation time. -1 to allow indefinite archival.
	DeleteAfter *int64 `json:"deleteAfter,omitempty" cborgen:"deleteAfter,omitempty"`
}
