// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.moderation.deletePin

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// ModerationDeletePin_Input is the input argument to a place.stream.moderation.deletePin call.
type ModerationDeletePin_Input struct {
	// pinUri: The AT-URI of the pinned record to delete.
	PinUri string `json:"pinUri" cborgen:"pinUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
}

// ModerationDeletePin_Output is the output of a place.stream.moderation.deletePin call.
type ModerationDeletePin_Output struct {
}

// ModerationDeletePin calls the XRPC method "place.stream.moderation.deletePin".
//
// Unpin a pinned chat message on behalf of a streamer. Requires 'message.pin' permission. Deletes the place.stream.chat.pinnedRecord from the streamer's repo.
func ModerationDeletePin(ctx context.Context, c lexutil.LexClient, input *ModerationDeletePin_Input) (*ModerationDeletePin_Output, error) {
	var out ModerationDeletePin_Output

	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.deletePin", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
