// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.server.upsertStorage

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// ServerUpsertStorage_Input is the input argument to a place.stream.server.upsertStorage call.
type ServerUpsertStorage_Input struct {
	// isActive: Whether backup storage is currently active.
	IsActive *bool `json:"isActive,omitempty" cborgen:"isActive,omitempty"`
	// url: S3 storage URL in format: s3+https://ACCESS_KEY:SECRET_KEY@endpoint/bucket
	Url *string `json:"url,omitempty" cborgen:"url,omitempty"`
}

// ServerUpsertStorage_Output is the output of a place.stream.server.upsertStorage call.
type ServerUpsertStorage_Output struct {
	Storage ServerDefs_Storage `json:"storage" cborgen:"storage"`
}

// ServerUpsertStorage calls the XRPC method "place.stream.server.upsertStorage".
//
// Create or update S3 storage configuration for backups.
func ServerUpsertStorage(ctx context.Context, c lexutil.LexClient, input *ServerUpsertStorage_Input) (*ServerUpsertStorage_Output, error) {
	var out ServerUpsertStorage_Output

	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.server.upsertStorage", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
