// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: place.stream.server.settings

package placestream

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Record containing user settings for a particular Streamplace node
type ServerSettings struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.server.settings"`
	// debugRecording: Whether this node may archive your livestream for improving the service
	DebugRecording *bool `json:"debugRecording,omitempty" cborgen:"debugRecording,omitempty"`
}
