[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-ar'
strip = 'aarch64-linux-gnu-strip'
exe_wrapper = 'qemu-aarch64-static'
rust = ['rustc', '--target', 'aarch64-unknown-linux-gnu']

[properties]
GOOS = 'linux'
GOARCH = 'arm64'
exe_wrapper = 'qemu-aarch64-static'
RUST_TRIPLE = 'aarch64-unknown-linux-gnu'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

; Working clang version should we need it:
; [binaries]
; c = 'clang'
; cpp = 'clang++'
; ; ar = 'llvm-ar'
; ; strip = 'llvm-strip'
; c_ld = 'lld'
; cpp_ld = 'lld'

; [built-in options]
; c_args = ['--target=aarch64-gnu-linux']
; c_link_args = ['--target=aarch64-gnu-linux']
; cpp_args = ['--target=aarch64-gnu-linux']
; cpp_link_args = ['--target=aarch64-gnu-linux']