[binaries]
c = 'x86_64-apple-darwin24.4-clang'
cpp = 'x86_64-apple-darwin24.4-clang++'
objc = 'x86_64-apple-darwin24.4-clang'
objcpp = 'x86_64-apple-darwin24.4-clang'
ld = 'x86_64-apple-darwin24.4-ld'
; ar = 'llvm-ar'
; strip = 'llvm-strip'

[built-in options]
c_args = ['--target=x86_64-apple-darwin']
c_link_args = ['--target=x86_64-apple-darwin', '--ld-path=/osxcross/target/bin/x86_64-apple-darwin24.4-ld']
cpp_args = ['--target=x86_64-apple-darwin']
cpp_link_args = ['--target=x86_64-apple-darwin', '--ld-path=/osxcross/target/bin/x86_64-apple-darwin24.4-ld']
objc_args = ['--target=x86_64-apple-darwin']
objc_link_args = ['--target=x86_64-apple-darwin', '--ld-path=/osxcross/target/bin/x86_64-apple-darwin24.4-ld']
objcpp_args = ['-arch', 'x86_64']
objcpp_link_args = ['-arch', 'x86_64']

[host_machine]
system = 'darwin'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
GOOS = 'darwin'
GOARCH = 'amd64'
RUST_TRIPLE = 'x86_64-apple-darwin'
