[binaries]
c = 'aarch64-apple-darwin24.4-clang'
cpp = 'aarch64-apple-darwin24.4-clang++'
objc = 'aarch64-apple-darwin24.4-clang'
objcpp = 'aarch64-apple-darwin24.4-clang'
ld = 'aarch64-apple-darwin24.4-ld'
; ar = 'llvm-ar'
; strip = 'llvm-strip'

[built-in options]
c_args = ['--target=aarch64-apple-darwin']
c_link_args = ['--target=aarch64-apple-darwin', '--ld-path=/osxcross/target/bin/aarch64-apple-darwin24.4-ld']
cpp_args = ['--target=aarch64-apple-darwin']
cpp_link_args = ['--target=aarch64-apple-darwin', '--ld-path=/osxcross/target/bin/aarch64-apple-darwin24.4-ld']
objc_args = ['--target=aarch64-apple-darwin']
objc_link_args = ['--target=aarch64-apple-darwin', '--ld-path=/osxcross/target/bin/aarch64-apple-darwin24.4-ld']
objcpp_args = ['-arch', 'arm64']
objcpp_link_args = ['-arch', 'arm64']

[host_machine]
system = 'darwin'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
GOOS = 'darwin'
GOARCH = 'arm64'
RUST_TRIPLE = 'aarch64-apple-darwin'
