// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: games.gamesgamesgamesgames.defs

package gamesgamesgamesgames

import (
	"io"

	appbsky "github.com/bluesky-social/indigo/api/bsky"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// Defs_ActorCreditView is a "actorCreditView" in the games.gamesgamesgamesgames.defs schema.
type Defs_ActorCreditView struct {
	LexiconTypeID string              `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	ActorUri      *string             `json:"actorUri,omitempty" cborgen:"actorUri,omitempty"`
	Credits       []*Defs_CreditEntry `json:"credits" cborgen:"credits"`
	DisplayName   *string             `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Uri           string              `json:"uri" cborgen:"uri"`
}

func (t *Defs_ActorCreditView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ActorCreditView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ActorProfileDetailView is a "actorProfileDetailView" in the games.gamesgamesgamesgames.defs schema.
type Defs_ActorProfileDetailView struct {
	LexiconTypeID     string                   `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Avatar            *lex.Blob                `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	CreatedAt         *string                  `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Description       *string                  `json:"description,omitempty" cborgen:"description,omitempty"`
	DescriptionFacets []*appbsky.RichtextFacet `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	Did               string                   `json:"did" cborgen:"did"`
	DisplayName       *string                  `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Pronouns          *string                  `json:"pronouns,omitempty" cborgen:"pronouns,omitempty"`
	Uri               string                   `json:"uri" cborgen:"uri"`
	Websites          []*Defs_Website          `json:"websites,omitempty" cborgen:"websites,omitempty"`
}

func (t *Defs_ActorProfileDetailView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ActorProfileDetailView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ActorProfileSummaryView is a "actorProfileSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_ActorProfileSummaryView struct {
	LexiconTypeID string    `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Avatar        *lex.Blob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	Did           string    `json:"did" cborgen:"did"`
	DisplayName   *string   `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Uri           string    `json:"uri" cborgen:"uri"`
}

func (t *Defs_ActorProfileSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ActorProfileSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_AgeRating is a "ageRating" in the games.gamesgamesgamesgames.defs schema.
type Defs_AgeRating struct {
	LexiconTypeID      string   `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	ContentDescriptors []string `json:"contentDescriptors,omitempty" cborgen:"contentDescriptors,omitempty"`
	Organization       string   `json:"organization" cborgen:"organization"`
	Rating             string   `json:"rating" cborgen:"rating"`
}

func (t *Defs_AgeRating) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_AgeRating) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_AlternativeName is a "alternativeName" in the games.gamesgamesgamesgames.defs schema.
type Defs_AlternativeName struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Comment       *string `json:"comment,omitempty" cborgen:"comment,omitempty"`
	Locale        *string `json:"locale,omitempty" cborgen:"locale,omitempty"`
	Name          string  `json:"name" cborgen:"name"`
}

func (t *Defs_AlternativeName) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_AlternativeName) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_CollectionSummaryView is a "collectionSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_CollectionSummaryView struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Name          string  `json:"name" cborgen:"name"`
	Slug          *string `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Type          *string `json:"type,omitempty" cborgen:"type,omitempty"`
	Uri           string  `json:"uri" cborgen:"uri"`
}

func (t *Defs_CollectionSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_CollectionSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_CreditEntry is a "creditEntry" in the games.gamesgamesgamesgames.defs schema.
type Defs_CreditEntry struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Department    *string `json:"department,omitempty" cborgen:"department,omitempty"`
	Role          *string `json:"role" cborgen:"role"`
}

func (t *Defs_CreditEntry) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_CreditEntry) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_EngineSummaryView is a "engineSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_EngineSummaryView struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Name          string  `json:"name" cborgen:"name"`
	Slug          *string `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Uri           string  `json:"uri" cborgen:"uri"`
}

func (t *Defs_EngineSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_EngineSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ExternalIds is a "externalIds" in the games.gamesgamesgamesgames.defs schema.
type Defs_ExternalIds struct {
	LexiconTypeID string         `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	AppleAppStore *string        `json:"appleAppStore,omitempty" cborgen:"appleAppStore,omitempty"`
	EpicGames     *string        `json:"epicGames,omitempty" cborgen:"epicGames,omitempty"`
	Gog           *string        `json:"gog,omitempty" cborgen:"gog,omitempty"`
	GooglePlay    *string        `json:"googlePlay,omitempty" cborgen:"googlePlay,omitempty"`
	HumbleBundle  *string        `json:"humbleBundle,omitempty" cborgen:"humbleBundle,omitempty"`
	Igdb          *string        `json:"igdb,omitempty" cborgen:"igdb,omitempty"`
	ItchIo        *Defs_ItchIoId `json:"itchIo,omitempty" cborgen:"itchIo,omitempty"`
	NintendoEshop *string        `json:"nintendoEshop,omitempty" cborgen:"nintendoEshop,omitempty"`
	PlayStation   *string        `json:"playStation,omitempty" cborgen:"playStation,omitempty"`
	Steam         *string        `json:"steam,omitempty" cborgen:"steam,omitempty"`
	Twitch        *string        `json:"twitch,omitempty" cborgen:"twitch,omitempty"`
	Xbox          *string        `json:"xbox,omitempty" cborgen:"xbox,omitempty"`
}

func (t *Defs_ExternalIds) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ExternalIds) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ExternalVideo is a "externalVideo" in the games.gamesgamesgamesgames.defs schema.
type Defs_ExternalVideo struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Platform      string  `json:"platform" cborgen:"platform"`
	Title         *string `json:"title,omitempty" cborgen:"title,omitempty"`
	VideoId       string  `json:"videoId" cborgen:"videoId"`
}

func (t *Defs_ExternalVideo) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ExternalVideo) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_GameDetailView is a "gameDetailView" in the games.gamesgamesgamesgames.defs schema.
type Defs_GameDetailView struct {
	LexiconTypeID      string                  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	ActorCredits       []*Defs_ActorCreditView `json:"actorCredits,omitempty" cborgen:"actorCredits,omitempty"`
	AgeRatings         []*Defs_AgeRating       `json:"ageRatings,omitempty" cborgen:"ageRatings,omitempty"`
	AlternativeNames   []*Defs_AlternativeName `json:"alternativeNames,omitempty" cborgen:"alternativeNames,omitempty"`
	ApplicationType    *string                 `json:"applicationType,omitempty" cborgen:"applicationType,omitempty"`
	Collections        []string                `json:"collections,omitempty" cborgen:"collections,omitempty"`
	CreatedAt          string                  `json:"createdAt" cborgen:"createdAt"`
	Engines            []string                `json:"engines,omitempty" cborgen:"engines,omitempty"`
	ExternalIds        *Defs_ExternalIds       `json:"externalIds,omitempty" cborgen:"externalIds,omitempty"`
	Genres             []*string               `json:"genres,omitempty" cborgen:"genres,omitempty"`
	Keywords           []string                `json:"keywords,omitempty" cborgen:"keywords,omitempty"`
	LanguageSupports   []*Defs_LanguageSupport `json:"languageSupports,omitempty" cborgen:"languageSupports,omitempty"`
	Media              []*Defs_MediaItem       `json:"media,omitempty" cborgen:"media,omitempty"`
	Modes              []*string               `json:"modes,omitempty" cborgen:"modes,omitempty"`
	MultiplayerModes   []*Defs_MultiplayerMode `json:"multiplayerModes,omitempty" cborgen:"multiplayerModes,omitempty"`
	Name               string                  `json:"name" cborgen:"name"`
	OrgCredits         []*Defs_OrgCreditView   `json:"orgCredits,omitempty" cborgen:"orgCredits,omitempty"`
	Parent             *string                 `json:"parent,omitempty" cborgen:"parent,omitempty"`
	PlayerPerspectives []*string               `json:"playerPerspectives,omitempty" cborgen:"playerPerspectives,omitempty"`
	PublishedAt        *string                 `json:"publishedAt,omitempty" cborgen:"publishedAt,omitempty"`
	Releases           []*Defs_Release         `json:"releases,omitempty" cborgen:"releases,omitempty"`
	Slug               *string                 `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Storyline          *string                 `json:"storyline,omitempty" cborgen:"storyline,omitempty"`
	Summary            *string                 `json:"summary,omitempty" cborgen:"summary,omitempty"`
	Themes             []*string               `json:"themes,omitempty" cborgen:"themes,omitempty"`
	TimeToBeat         *Defs_TimeToBeat        `json:"timeToBeat,omitempty" cborgen:"timeToBeat,omitempty"`
	Uri                string                  `json:"uri" cborgen:"uri"`
	Videos             []*Defs_ExternalVideo   `json:"videos,omitempty" cborgen:"videos,omitempty"`
	Websites           []*Defs_Website         `json:"websites,omitempty" cborgen:"websites,omitempty"`
}

func (t *Defs_GameDetailView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_GameDetailView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_GameFeedViewItem is a "gameFeedViewItem" in the games.gamesgamesgamesgames.defs schema.
type Defs_GameFeedViewItem struct {
	LexiconTypeID string         `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	FeedContext   *string        `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	Game          *Defs_GameView `json:"game" cborgen:"game"`
}

func (t *Defs_GameFeedViewItem) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_GameFeedViewItem) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_GameSummaryView is a "gameSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_GameSummaryView struct {
	LexiconTypeID   string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	ApplicationType *string `json:"applicationType,omitempty" cborgen:"applicationType,omitempty"`
	// firstReleaseDate: Earliest release date as YYYYMMDD integer.
	FirstReleaseDate *int64            `json:"firstReleaseDate,omitempty" cborgen:"firstReleaseDate,omitempty"`
	Genres           []*string         `json:"genres,omitempty" cborgen:"genres,omitempty"`
	Media            []*Defs_MediaItem `json:"media,omitempty" cborgen:"media,omitempty"`
	Name             string            `json:"name" cborgen:"name"`
	Slug             *string           `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Summary          *string           `json:"summary,omitempty" cborgen:"summary,omitempty"`
	Uri              string            `json:"uri" cborgen:"uri"`
}

func (t *Defs_GameSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_GameSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_GameView is a "gameView" in the games.gamesgamesgamesgames.defs schema.
type Defs_GameView struct {
	LexiconTypeID   string            `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	ApplicationType *string           `json:"applicationType" cborgen:"applicationType"`
	Genres          []*string         `json:"genres,omitempty" cborgen:"genres,omitempty"`
	LikeCount       *int64            `json:"likeCount,omitempty" cborgen:"likeCount,omitempty"`
	Media           []*Defs_MediaItem `json:"media,omitempty" cborgen:"media,omitempty"`
	Name            string            `json:"name" cborgen:"name"`
	Releases        []*Defs_Release   `json:"releases,omitempty" cborgen:"releases,omitempty"`
	Slug            *string           `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Summary         *string           `json:"summary,omitempty" cborgen:"summary,omitempty"`
	Themes          []*string         `json:"themes,omitempty" cborgen:"themes,omitempty"`
	Uri             string            `json:"uri" cborgen:"uri"`
	Viewer          *Defs_ViewerState `json:"viewer,omitempty" cborgen:"viewer,omitempty"`
}

func (t *Defs_GameView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_GameView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ItchIoId is a "itchIoId" in the games.gamesgamesgamesgames.defs schema.
type Defs_ItchIoId struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Developer     string `json:"developer" cborgen:"developer"`
	Game          string `json:"game" cborgen:"game"`
}

func (t *Defs_ItchIoId) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ItchIoId) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_LanguageSupport is a "languageSupport" in the games.gamesgamesgamesgames.defs schema.
type Defs_LanguageSupport struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Audio         *bool  `json:"audio,omitempty" cborgen:"audio,omitempty"`
	Interface     *bool  `json:"interface,omitempty" cborgen:"interface,omitempty"`
	Language      string `json:"language" cborgen:"language"`
	Subtitles     *bool  `json:"subtitles,omitempty" cborgen:"subtitles,omitempty"`
}

func (t *Defs_LanguageSupport) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_LanguageSupport) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_MediaItem is a "mediaItem" in the games.gamesgamesgamesgames.defs schema.
type Defs_MediaItem struct {
	LexiconTypeID string    `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Blob          *lex.Blob `json:"blob,omitempty" cborgen:"blob,omitempty"`
	Description   *string   `json:"description,omitempty" cborgen:"description,omitempty"`
	Height        *int64    `json:"height,omitempty" cborgen:"height,omitempty"`
	Locale        *string   `json:"locale,omitempty" cborgen:"locale,omitempty"`
	MediaType     *string   `json:"mediaType,omitempty" cborgen:"mediaType,omitempty"`
	Title         *string   `json:"title,omitempty" cborgen:"title,omitempty"`
	Width         *int64    `json:"width,omitempty" cborgen:"width,omitempty"`
}

func (t *Defs_MediaItem) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_MediaItem) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_MultiplayerMode is a "multiplayerMode" in the games.gamesgamesgamesgames.defs schema.
type Defs_MultiplayerMode struct {
	LexiconTypeID        string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	HasCampaignCoop      *bool   `json:"hasCampaignCoop,omitempty" cborgen:"hasCampaignCoop,omitempty"`
	HasDropIn            *bool   `json:"hasDropIn,omitempty" cborgen:"hasDropIn,omitempty"`
	HasLanCoop           *bool   `json:"hasLanCoop,omitempty" cborgen:"hasLanCoop,omitempty"`
	HasSplitscreen       *bool   `json:"hasSplitscreen,omitempty" cborgen:"hasSplitscreen,omitempty"`
	HasSplitscreenOnline *bool   `json:"hasSplitscreenOnline,omitempty" cborgen:"hasSplitscreenOnline,omitempty"`
	OfflineCoopMax       *int64  `json:"offlineCoopMax,omitempty" cborgen:"offlineCoopMax,omitempty"`
	OfflineMax           *int64  `json:"offlineMax,omitempty" cborgen:"offlineMax,omitempty"`
	OnlineCoopMax        *int64  `json:"onlineCoopMax,omitempty" cborgen:"onlineCoopMax,omitempty"`
	OnlineMax            *int64  `json:"onlineMax,omitempty" cborgen:"onlineMax,omitempty"`
	Platform             *string `json:"platform,omitempty" cborgen:"platform,omitempty"`
}

func (t *Defs_MultiplayerMode) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_MultiplayerMode) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_OrgCreditView is a "orgCreditView" in the games.gamesgamesgamesgames.defs schema.
type Defs_OrgCreditView struct {
	LexiconTypeID string    `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	DisplayName   *string   `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	OrgUri        *string   `json:"orgUri,omitempty" cborgen:"orgUri,omitempty"`
	Roles         []*string `json:"roles" cborgen:"roles"`
	Uri           string    `json:"uri" cborgen:"uri"`
}

func (t *Defs_OrgCreditView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_OrgCreditView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_OrgProfileDetailView is a "orgProfileDetailView" in the games.gamesgamesgamesgames.defs schema.
type Defs_OrgProfileDetailView struct {
	LexiconTypeID     string                   `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Avatar            *lex.Blob                `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	Country           *string                  `json:"country,omitempty" cborgen:"country,omitempty"`
	CreatedAt         *string                  `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Description       *string                  `json:"description,omitempty" cborgen:"description,omitempty"`
	DescriptionFacets []*appbsky.RichtextFacet `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	Did               string                   `json:"did" cborgen:"did"`
	DisplayName       *string                  `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	FoundedAt         *string                  `json:"foundedAt,omitempty" cborgen:"foundedAt,omitempty"`
	Media             []*Defs_MediaItem        `json:"media,omitempty" cborgen:"media,omitempty"`
	Parent            *string                  `json:"parent,omitempty" cborgen:"parent,omitempty"`
	Status            *string                  `json:"status,omitempty" cborgen:"status,omitempty"`
	Uri               string                   `json:"uri" cborgen:"uri"`
	Websites          []*Defs_Website          `json:"websites,omitempty" cborgen:"websites,omitempty"`
}

func (t *Defs_OrgProfileDetailView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_OrgProfileDetailView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_OrgProfileSummaryView is a "orgProfileSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_OrgProfileSummaryView struct {
	LexiconTypeID string    `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Avatar        *lex.Blob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	Did           string    `json:"did" cborgen:"did"`
	DisplayName   *string   `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Uri           string    `json:"uri" cborgen:"uri"`
}

func (t *Defs_OrgProfileSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_OrgProfileSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_PlatformFeatures is a "platformFeatures" in the games.gamesgamesgamesgames.defs schema.
//
// Features supported by a game on a specific storefront/platform.
type Defs_PlatformFeatures struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Features      []string `json:"features" cborgen:"features"`
	Platform      string   `json:"platform" cborgen:"platform"`
}

func (t *Defs_PlatformFeatures) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_PlatformFeatures) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_PlatformSummaryView is a "platformSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_PlatformSummaryView struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Abbreviation  *string `json:"abbreviation,omitempty" cborgen:"abbreviation,omitempty"`
	Category      *string `json:"category,omitempty" cborgen:"category,omitempty"`
	Name          string  `json:"name" cborgen:"name"`
	Slug          *string `json:"slug,omitempty" cborgen:"slug,omitempty"`
	Uri           string  `json:"uri" cborgen:"uri"`
}

func (t *Defs_PlatformSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_PlatformSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_PlatformVersion is a "platformVersion" in the games.gamesgamesgamesgames.defs schema.
type Defs_PlatformVersion struct {
	LexiconTypeID string            `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Connectivity  *string           `json:"connectivity,omitempty" cborgen:"connectivity,omitempty"`
	Cpu           *string           `json:"cpu,omitempty" cborgen:"cpu,omitempty"`
	Gpu           *string           `json:"gpu,omitempty" cborgen:"gpu,omitempty"`
	MaxResolution *string           `json:"maxResolution,omitempty" cborgen:"maxResolution,omitempty"`
	Media         []*Defs_MediaItem `json:"media,omitempty" cborgen:"media,omitempty"`
	Memory        *string           `json:"memory,omitempty" cborgen:"memory,omitempty"`
	Name          string            `json:"name" cborgen:"name"`
	Os            *string           `json:"os,omitempty" cborgen:"os,omitempty"`
	Output        *string           `json:"output,omitempty" cborgen:"output,omitempty"`
	Storage       *string           `json:"storage,omitempty" cborgen:"storage,omitempty"`
	Summary       *string           `json:"summary,omitempty" cborgen:"summary,omitempty"`
}

func (t *Defs_PlatformVersion) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_PlatformVersion) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ProfileSummaryView is a "profileSummaryView" in the games.gamesgamesgamesgames.defs schema.
type Defs_ProfileSummaryView struct {
	LexiconTypeID string    `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Avatar        *lex.Blob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	Did           string    `json:"did" cborgen:"did"`
	DisplayName   *string   `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	ProfileType   string    `json:"profileType" cborgen:"profileType"`
	Uri           string    `json:"uri" cborgen:"uri"`
}

func (t *Defs_ProfileSummaryView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ProfileSummaryView) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_Release is a "release" in the games.gamesgamesgamesgames.defs schema.
type Defs_Release struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	// platform: Free-text platform name, used when no platform record exists.
	Platform *string `json:"platform,omitempty" cborgen:"platform,omitempty"`
	// platformUri: AT URI of a platform record.
	PlatformUri  *string             `json:"platformUri,omitempty" cborgen:"platformUri,omitempty"`
	ReleaseDates []*Defs_ReleaseDate `json:"releaseDates,omitempty" cborgen:"releaseDates,omitempty"`
}

func (t *Defs_Release) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_Release) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ReleaseDate is a "releaseDate" in the games.gamesgamesgamesgames.defs schema.
type Defs_ReleaseDate struct {
	LexiconTypeID    string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Region           *string `json:"region,omitempty" cborgen:"region,omitempty"`
	ReleasedAt       *string `json:"releasedAt,omitempty" cborgen:"releasedAt,omitempty"`
	ReleasedAtFormat *string `json:"releasedAtFormat,omitempty" cborgen:"releasedAtFormat,omitempty"`
	Status           *string `json:"status,omitempty" cborgen:"status,omitempty"`
}

func (t *Defs_ReleaseDate) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ReleaseDate) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_Signature is a "signature" in the games.gamesgamesgamesgames.defs schema.
//
// An inline attestation signature.
type Defs_Signature struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	// key: DID key reference (e.g., did:web:example.com#signing1).
	Key string `json:"key" cborgen:"key"`
	// signature: The signature bytes.
	Signature lex.Bytes `json:"signature" cborgen:"signature"`
}

func (t *Defs_Signature) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_Signature) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_SkeletonGameFeedItem is a "skeletonGameFeedItem" in the games.gamesgamesgamesgames.defs schema.
type Defs_SkeletonGameFeedItem struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	FeedContext   *string `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	Game          string  `json:"game" cborgen:"game"`
}

func (t *Defs_SkeletonGameFeedItem) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_SkeletonGameFeedItem) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_SystemRequirements is a "systemRequirements" in the games.gamesgamesgamesgames.defs schema.
//
// System requirements for a game on a specific platform.
type Defs_SystemRequirements struct {
	LexiconTypeID string           `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Minimum       *Defs_SystemSpec `json:"minimum,omitempty" cborgen:"minimum,omitempty"`
	Platform      string           `json:"platform" cborgen:"platform"`
	Recommended   *Defs_SystemSpec `json:"recommended,omitempty" cborgen:"recommended,omitempty"`
}

func (t *Defs_SystemRequirements) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_SystemRequirements) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_SystemSpec is a "systemSpec" in the games.gamesgamesgamesgames.defs schema.
//
// Hardware/software specification for a platform.
type Defs_SystemSpec struct {
	LexiconTypeID   string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	AdditionalNotes *string `json:"additionalNotes,omitempty" cborgen:"additionalNotes,omitempty"`
	Directx         *string `json:"directx,omitempty" cborgen:"directx,omitempty"`
	Graphics        *string `json:"graphics,omitempty" cborgen:"graphics,omitempty"`
	Memory          *string `json:"memory,omitempty" cborgen:"memory,omitempty"`
	Os              *string `json:"os,omitempty" cborgen:"os,omitempty"`
	Processor       *string `json:"processor,omitempty" cborgen:"processor,omitempty"`
	SoundCard       *string `json:"soundCard,omitempty" cborgen:"soundCard,omitempty"`
	Storage         *string `json:"storage,omitempty" cborgen:"storage,omitempty"`
}

func (t *Defs_SystemSpec) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_SystemSpec) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_TimeToBeat is a "timeToBeat" in the games.gamesgamesgamesgames.defs schema.
type Defs_TimeToBeat struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Completely    *int64 `json:"completely,omitempty" cborgen:"completely,omitempty"`
	Hastily       *int64 `json:"hastily,omitempty" cborgen:"hastily,omitempty"`
	Normally      *int64 `json:"normally,omitempty" cborgen:"normally,omitempty"`
}

func (t *Defs_TimeToBeat) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_TimeToBeat) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_ViewerState is a "viewerState" in the games.gamesgamesgamesgames.defs schema.
type Defs_ViewerState struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Like          *string `json:"like,omitempty" cborgen:"like,omitempty"`
}

func (t *Defs_ViewerState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_ViewerState) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// Defs_Website is a "website" in the games.gamesgamesgamesgames.defs schema.
type Defs_Website struct {
	LexiconTypeID string  `json:"$type" cborgen:"$type,const=games.gamesgamesgamesgames.defs"`
	Type          *string `json:"type,omitempty" cborgen:"type,omitempty"`
	Url           string  `json:"url" cborgen:"url"`
}

func (t *Defs_Website) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "games.gamesgamesgamesgames.defs"
	return lex.MarshalCBOR(w, t)
}

func (t *Defs_Website) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
