#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
source "$ROOT/run/common.sh"

lerna --concurrency=1 exec "$ROOT/run/package-lint.sh"
filesToLint="$(git diff --cached --name-only | grep "\.js$")"
filesToLint="$filesToLint $(git diff --cached --name-only | grep "\.jsx$")"
if [[ -n "$filesToLint" ]]; then
  status="happy"
  for file in $filesToLint; do
    if [[ -n "$(git ls-files :$file)" ]]; then
      contents=$(git show :"$file")
      if [[ -n "$contents" ]]; then
        if (echo "$contents" | eslint --stdin --stdin-filename $file); then
          :
        else
          status="sad"
        fi
      fi
    fi
  done
  if [[ "$status" == "sad" ]]; then
    exit 1
  fi
else
  echo -en ""
fi
