package config

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestAdaptFlags(t *testing.T) {
	for _, pair := range pairs {
		assert.Equal(t, pair[1], ToSnakeCase(pair[0]))
	}
}

var pairs = [][]string{
	{"aiMinRunnerVersion", "ai-min-runner-version"},
	{"aiModels", "ai-models"},
	{"aiModelsDir", "ai-models-dir"},
	{"aiProcessingRetryTimeout", "ai-processing-retry-timeout"},
	{"aiRunnerContainersPerGPU", "ai-runner-containers-per-gpu"},
	{"aiRunnerImage", "ai-runner-image"},
	{"aiRunnerImageOverrides", "ai-runner-image-overrides"},
	{"aiServiceRegistry", "ai-service-registry"},
	{"aiVerboseLogs", "ai-verbose-logs"},
	{"aiWorker", "ai-worker"},
	{"authWebhookUrl", "auth-webhook-url"},
	{"autoAdjustPrice", "auto-adjust-price"},
	{"blockPollingInterval", "block-polling-interval"},
	{"broadcaster", "broadcaster"},
	{"cliAddr", "cli-addr"},
	{"currentManifest", "current-manifest"},
	{"dataDir", "data-dir"},
	{"datadir", "datadir"},
	{"depositMultiplier", "deposit-multiplier"},
	{"discoveryTimeout", "discovery-timeout"},
	{"ethAcctAddr", "eth-acct-addr"},
	{"ethController", "eth-controller"},
	{"ethKeystorePath", "eth-keystore-path"},
	{"ethOrchAddr", "eth-orch-addr"},
	{"ethPassword", "eth-password"},
	{"ethUrl", "eth-url"},
	{"gasLimit", "gas-limit"},
	{"gateway", "gateway"},
	{"gatewayHost", "gateway-host"},
	{"hevcDecoding", "hevc-decoding"},
	{"httpAddr", "http-addr"},
	{"httpIngest", "http-ingest"},
	{"ignoreMaxPriceIfNeeded", "ignore-max-price-if-needed"},
	{"initializeRound", "initialize-round"},
	{"initializeRoundMaxDelay", "initialize-round-max-delay"},
	{"kafkaBootstrapServers", "kafka-bootstrap-servers"},
	{"kafkaGatewayTopic", "kafka-gateway-topic"},
	{"kafkaPassword", "kafka-password"},
	{"kafkaUser", "kafka-user"},
	{"liveAIAuthApiKey", "live-ai-auth-api-key"},
	{"liveAIAuthWebhookUrl", "live-ai-auth-webhook-url"},
	{"liveAICapRefreshModels", "live-ai-cap-refresh-models"},
	{"liveAITrickleHostForRunner", "live-ai-trickle-host-for-runner"},
	{"liveOutSegmentTimeout", "live-out-segment-timeout"},
	{"livePaymentInterval", "live-payment-interval"},
	{"localVerify", "local-verify"},
	{"maxAttempts", "max-attempts"},
	{"maxFaceValue", "max-face-value"},
	{"maxGasPrice", "max-gas-price"},
	{"maxPricePerCapability", "max-price-per-capability"},
	{"maxPricePerUnit", "max-price-per-unit"},
	{"maxSessions", "max-sessions"},
	{"maxTicketEV", "max-ticket-ev"},
	{"maxTotalEV", "max-total-ev"},
	{"maxTransactionReplacements", "max-transaction-replacements"},
	{"mediaMTXApiPassword", "media-mtx-api-password"},
	{"metadataAmqpExchange", "metadata-amqp-exchange"},
	{"metadataPublishTimeout", "metadata-publish-timeout"},
	{"metadataQueueUri", "metadata-queue-uri"},
	{"metricsClientIP", "metrics-client-ip"},
	{"metricsPerStream", "metrics-per-stream"},
	{"minGasPrice", "min-gas-price"},
	{"minPerfScore", "min-perf-score"},
	{"monitor", "monitor"},
	{"netint", "netint"},
	{"network", "network"},
	{"nvidia", "nvidia"},
	{"objectStore", "object-store"},
	{"orchAddr", "orch-addr"},
	{"orchBlocklist", "orch-blocklist"},
	{"orchMinLivepeerVersion", "orch-min-livepeer-version"},
	{"orchPerfStatsUrl", "orch-perf-stats-url"},
	{"orchSecret", "orch-secret"},
	{"orchWebhookUrl", "orch-webhook-url"},
	{"orchestrator", "orchestrator"},
	{"pixelsPerUnit", "pixels-per-unit"},
	{"priceFeedAddr", "price-feed-addr"},
	{"pricePerBroadcaster", "price-per-broadcaster"},
	{"pricePerGateway", "price-per-gateway"},
	{"pricePerUnit", "price-per-unit"},
	{"recordStore", "record-store"},
	{"redeemer", "redeemer"},
	{"redeemerAddr", "redeemer-addr"},
	{"region", "region"},
	{"reward", "reward"},
	{"rtmpAddr", "rtmp-addr"},
	{"selectPriceExpFactor", "select-price-exp-factor"},
	{"selectPriceWeight", "select-price-weight"},
	{"selectRandFreq", "select-rand-freq"},
	{"selectStakeWeight", "select-stake-weight"},
	{"serviceAddr", "service-addr"},
	{"startupAvailabilityCheck", "startup-availability-check"},
	{"testTranscoder", "test-transcoder"},
	{"ticketEV", "ticket-ev"},
	{"transactionTimeout", "transaction-timeout"},
	{"transcoder", "transcoder"},
	{"transcodingOptions", "transcoding-options"},
	{"verifierPath", "verifier-path"},
	{"verifierUrl", "verifier-url"},
}
