// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: app.bsky.actor.getProfile

package appbsky

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// ActorGetProfile calls the XRPC method "app.bsky.actor.getProfile".
//
// Get detailed profile view of an actor. Does not require auth, but contains relevant metadata with auth.
//
// actor: Handle or DID of account to fetch profile of.
func ActorGetProfile(ctx context.Context, c lexutil.LexClient, actor string) (*ActorDefs_ProfileViewDetailed, error) {
	var out ActorDefs_ProfileViewDetailed

	params := map[string]interface{}{}
	params["actor"] = actor

	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.actor.getProfile", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
