// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: app.bsky.feed.postgate

package appbsky

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// Record defining interaction rules for a post. The record key (rkey) of the postgate record must match the record key of the post, and that record must be in the same repository.
type FeedPostgate struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=app.bsky.feed.postgate"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// detachedEmbeddingUris: List of AT-URIs embedding this post that the author has detached from.
	DetachedEmbeddingUris []string `json:"detachedEmbeddingUris,omitempty" cborgen:"detachedEmbeddingUris,omitempty"`
	// embeddingRules: List of rules defining who can embed this post. If value is an empty array or is undefined, no particular rules apply and anyone can embed.
	EmbeddingRules []FeedPostgate_EmbeddingRules_Elem `json:"embeddingRules,omitempty" cborgen:"embeddingRules,omitempty"`
	// post: Reference (AT-URI) to the post record.
	Post string `json:"post" cborgen:"post"`
}

type FeedPostgate_EmbeddingRules_Elem struct {
	FeedPostgate_DisableRule *FeedPostgate_DisableRule
}

func (t *FeedPostgate_EmbeddingRules_Elem) MarshalJSON() ([]byte, error) {
	if t.FeedPostgate_DisableRule != nil {
		t.FeedPostgate_DisableRule.LexiconTypeID = "app.bsky.feed.postgate#disableRule"
		return json.Marshal(t.FeedPostgate_DisableRule)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedPostgate_EmbeddingRules_Elem) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.postgate#disableRule":
		t.FeedPostgate_DisableRule = new(FeedPostgate_DisableRule)
		return json.Unmarshal(b, t.FeedPostgate_DisableRule)
	default:
		return nil
	}
}

// FeedPostgate_DisableRule is a "disableRule" in the app.bsky.feed.postgate schema.
//
// Disables embedding of this post.
type FeedPostgate_DisableRule struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=app.bsky.feed.postgate#disableRule,omitempty"`
}
