// Code generated by indigo lexgen tool. DO NOT EDIT MANUALLY.

// Lexicon schema: app.bsky.feed.getFeedSkeleton

package appbsky

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// FeedGetFeedSkeleton_Output is the output of a app.bsky.feed.getFeedSkeleton call.
type FeedGetFeedSkeleton_Output struct {
	Cursor *string                     `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Feed   []FeedDefs_SkeletonFeedPost `json:"feed" cborgen:"feed"`
}

// FeedGetFeedSkeleton calls the XRPC method "app.bsky.feed.getFeedSkeleton".
//
// Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service.
//
// feed: Reference to feed generator record describing the specific feed being requested.
func FeedGetFeedSkeleton(ctx context.Context, c lexutil.LexClient, cursor string, feed string, limit *int64) (*FeedGetFeedSkeleton_Output, error) {
	var out FeedGetFeedSkeleton_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	params["feed"] = feed

	if err := c.LexDo(ctx, lexutil.Query, "", "app.bsky.feed.getFeedSkeleton", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
