// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.account.defs

// AccountDefs_LoginResponse is a "loginResponse" in the place.stream.account.defs schema.
type AccountDefs_LoginResponse struct {
	RedirectUrl string `json:"redirectUrl" cborgen:"redirectUrl"`
}
