// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.beta.getStatus

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// BetaGetStatus_Output is the output of a place.stream.beta.getStatus call.
type BetaGetStatus_Output struct {
	// did: The account this status applies to.
	Did string `json:"did" cborgen:"did"`
	// feature: The feature this status applies to (echoes the request).
	Feature string `json:"feature" cborgen:"feature"`
	// status: granted: the account may use the feature. requested: no grant yet, but an access request is on file. none: no grant and no request.
	Status string `json:"status" cborgen:"status"`
}

func (t *BetaGetStatus_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *BetaGetStatus_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// BetaGetStatus calls the XRPC method "place.stream.beta.getStatus".
//
// did: Account to check. Defaults to the authenticated caller's DID when omitted.
// feature: Identifier of the beta feature to check (e.g. "vod").
func BetaGetStatus(ctx context.Context, c lexutil.LexClient, did string, feature string) (*BetaGetStatus_Output, error) {
	var out BetaGetStatus_Output

	params := map[string]interface{}{}
	if did != "" {
		params["did"] = did
	}
	params["feature"] = feature
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.beta.getStatus", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
