// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.bio.blocks.schedule

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.bio.blocks.schedule#main", &BioBlocksSchedule{})
}

// BioBlocksSchedule is a "main" in the place.stream.bio.blocks.schedule schema.
//
// A weekly streaming schedule, rendered as a grid.
type BioBlocksSchedule struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=place.stream.bio.blocks.schedule"`
	Slots         []*BioBlocksSchedule_Slot `json:"slots" cborgen:"slots"`
	// timezone: IANA timezone name in which slot times are expressed, e.g. 'America/New_York'.
	Timezone string `json:"timezone" cborgen:"timezone"`
}

// BioBlocksSchedule_Slot is a "slot" in the place.stream.bio.blocks.schedule schema.
type BioBlocksSchedule_Slot struct {
	DayOfWeek string `json:"dayOfWeek" cborgen:"dayOfWeek"`
	// endTime: Optional end time in 24-hour HH:MM format. Slots with no endTime are treated as open-ended.
	EndTime *string `json:"endTime,omitempty" cborgen:"endTime,omitempty"`
	// startTime: Start time in 24-hour HH:MM format, in the schedule's timezone.
	StartTime string `json:"startTime" cborgen:"startTime"`
	// title: Optional label for this slot, e.g. 'IRL walks' or 'Subathon'.
	Title *string `json:"title,omitempty" cborgen:"title,omitempty"`
}
