// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.bio.blocks.orderedList

package streamplace

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	lexutil.RegisterType("place.stream.bio.blocks.orderedList#main", &BioBlocksOrderedList{})
}

// BioBlocksOrderedList is a "main" in the place.stream.bio.blocks.orderedList schema.
type BioBlocksOrderedList struct {
	LexiconTypeID string                           `json:"$type" cborgen:"$type,const=place.stream.bio.blocks.orderedList"`
	Children      []*BioBlocksOrderedList_ListItem `json:"children" cborgen:"children"`
}

// BioBlocksOrderedList_ListItem is a "listItem" in the place.stream.bio.blocks.orderedList schema.
type BioBlocksOrderedList_ListItem struct {
	// children: Nested ordered list items. Mutually exclusive with unorderedListChildren; if both are present, children takes precedence.
	Children []*BioBlocksOrderedList_ListItem       `json:"children,omitempty" cborgen:"children,omitempty"`
	Content  *BioBlocksOrderedList_ListItem_Content `json:"content" cborgen:"content"`
	// unorderedListChildren: Nested unordered list items. Mutually exclusive with children; if both are present, children takes precedence.
	UnorderedListChildren *BioBlocksUnorderedList `json:"unorderedListChildren,omitempty" cborgen:"unorderedListChildren,omitempty"`
}

type BioBlocksOrderedList_ListItem_Content struct {
	BioBlocksText   *BioBlocksText
	BioBlocksHeader *BioBlocksHeader
	BioBlocksImage  *BioBlocksImage
}

func (t *BioBlocksOrderedList_ListItem_Content) MarshalJSON() ([]byte, error) {
	if t.BioBlocksText != nil {
		t.BioBlocksText.LexiconTypeID = "place.stream.bio.blocks.text"
		return json.Marshal(t.BioBlocksText)
	}
	if t.BioBlocksHeader != nil {
		t.BioBlocksHeader.LexiconTypeID = "place.stream.bio.blocks.header"
		return json.Marshal(t.BioBlocksHeader)
	}
	if t.BioBlocksImage != nil {
		t.BioBlocksImage.LexiconTypeID = "place.stream.bio.blocks.image"
		return json.Marshal(t.BioBlocksImage)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *BioBlocksOrderedList_ListItem_Content) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.bio.blocks.text":
		t.BioBlocksText = new(BioBlocksText)
		return json.Unmarshal(b, t.BioBlocksText)
	case "place.stream.bio.blocks.header":
		t.BioBlocksHeader = new(BioBlocksHeader)
		return json.Unmarshal(b, t.BioBlocksHeader)
	case "place.stream.bio.blocks.image":
		t.BioBlocksImage = new(BioBlocksImage)
		return json.Unmarshal(b, t.BioBlocksImage)
	default:
		return nil
	}
}

func (t *BioBlocksOrderedList_ListItem_Content) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.BioBlocksText != nil {
		return t.BioBlocksText.MarshalCBOR(w)
	}
	if t.BioBlocksHeader != nil {
		return t.BioBlocksHeader.MarshalCBOR(w)
	}
	if t.BioBlocksImage != nil {
		return t.BioBlocksImage.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *BioBlocksOrderedList_ListItem_Content) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := lexutil.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.bio.blocks.text":
		t.BioBlocksText = new(BioBlocksText)
		return t.BioBlocksText.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.bio.blocks.header":
		t.BioBlocksHeader = new(BioBlocksHeader)
		return t.BioBlocksHeader.UnmarshalCBOR(bytes.NewReader(b))
	case "place.stream.bio.blocks.image":
		t.BioBlocksImage = new(BioBlocksImage)
		return t.BioBlocksImage.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}
