// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.branding.getBranding

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// BrandingGetBranding_BrandingAsset is a "brandingAsset" in the place.stream.branding.getBranding schema.
type BrandingGetBranding_BrandingAsset struct {
	// data: Inline data for text assets
	Data *string `json:"data,omitempty" cborgen:"data,omitempty"`
	// height: Image height in pixels (optional, for images only)
	Height *int64 `json:"height,omitempty" cborgen:"height,omitempty"`
	// key: Asset key identifier
	Key string `json:"key" cborgen:"key"`
	// mimeType: MIME type of the asset
	MimeType string `json:"mimeType" cborgen:"mimeType"`
	// url: URL to fetch the asset blob (for images)
	Url *string `json:"url,omitempty" cborgen:"url,omitempty"`
	// width: Image width in pixels (optional, for images only)
	Width *int64 `json:"width,omitempty" cborgen:"width,omitempty"`
}

// BrandingGetBranding_Output is the output of a place.stream.branding.getBranding call.
type BrandingGetBranding_Output struct {
	// assets: List of available branding assets
	Assets []*BrandingGetBranding_BrandingAsset `json:"assets" cborgen:"assets"`
}

// BrandingGetBranding calls the XRPC method "place.stream.branding.getBranding".
//
// broadcaster: DID of the broadcaster. If not provided, uses the server's default broadcaster.
func BrandingGetBranding(ctx context.Context, c util.LexClient, broadcaster string) (*BrandingGetBranding_Output, error) {
	var out BrandingGetBranding_Output

	params := map[string]interface{}{}
	if broadcaster != "" {
		params["broadcaster"] = broadcaster
	}
	if err := c.LexDo(ctx, util.Query, "", "place.stream.branding.getBranding", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
