// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.broadcast.origin

package streamplace

import (
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.broadcast.origin", &BroadcastOrigin{})
}

// Record indicating a livestream is published and available for replication at a given address. By convention, the record key is streamer::server
type BroadcastOrigin struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.broadcast.origin"`
	// broadcaster: did of the broadcaster that operates the server syndicating the livestream
	Broadcaster *string `json:"broadcaster,omitempty" cborgen:"broadcaster,omitempty"`
	// irohTicket: Iroh ticket that can be used to access the livestream from the server
	IrohTicket *string `json:"irohTicket,omitempty" cborgen:"irohTicket,omitempty"`
	// server: did of the server that's currently rebroadcasting the livestream
	Server string `json:"server" cborgen:"server"`
	// streamer: DID of the streamer whose livestream is being published
	Streamer string `json:"streamer" cborgen:"streamer"`
	// updatedAt: Periodically updated timestamp when this origin last saw a livestream
	UpdatedAt string `json:"updatedAt" cborgen:"updatedAt"`
	// websocketURL: URL of the websocket endpoint for the livestream
	WebsocketURL *string `json:"websocketURL,omitempty" cborgen:"websocketURL,omitempty"`
}

func (t *BroadcastOrigin) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.broadcast.origin"
	return lex.MarshalCBOR(w, t)
}

func (t *BroadcastOrigin) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
