// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.chat.gate

package streamplace

import (
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.chat.gate", &ChatGate{})
}

type ChatGate struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.chat.gate"`
	// hiddenMessage: URI of the hidden chat message.
	HiddenMessage string `json:"hiddenMessage" cborgen:"hiddenMessage"`
}

func (t *ChatGate) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.chat.gate"
	return lex.MarshalCBOR(w, t)
}

func (t *ChatGate) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
