// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.chat.profile

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.chat.profile", &ChatProfile{})
}

type ChatProfile struct {
	LexiconTypeID string             `json:"$type" cborgen:"$type,const=place.stream.chat.profile"`
	Color         *ChatProfile_Color `json:"color,omitempty" cborgen:"color,omitempty"`
}

// ChatProfile_Color is a "color" in the place.stream.chat.profile schema.
//
// Customizations for the color of a user's name in chat
type ChatProfile_Color struct {
	Blue  int64 `json:"blue" cborgen:"blue"`
	Green int64 `json:"green" cborgen:"green"`
	Red   int64 `json:"red" cborgen:"red"`
}
