// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.emote.packDelegation

package streamplace

import (
	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.emote.packDelegation", &EmotePackDelegation{})
}

type EmotePackDelegation struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.emote.packDelegation"`
	// createdAt: Client-declared timestamp when this delegation was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// did: The DID of the user being granted access to use these emotes.
	Did string `json:"did" cborgen:"did"`
	// emotes: Specific emotes from the pack to delegate. If absent, all emotes in the pack are delegated.
	Emotes []*comatproto.RepoStrongRef `json:"emotes,omitempty" cborgen:"emotes,omitempty"`
	// pack: The pack the emotes come from. Must be owned by the record author.
	Pack *comatproto.RepoStrongRef `json:"pack" cborgen:"pack"`
}
