// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.graph.getFollowingUser

package streamplace

import (
	"context"
	"io"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type GraphGetFollowingUser_Output struct {
	LexiconTypeID string                    `json:"$type" cborgen:"$type,const=place.stream.graph.getFollowingUser#main"`
	Follow        *comatproto.RepoStrongRef `json:"follow,omitempty" cborgen:"follow,omitempty"`
}

func (t *GraphGetFollowingUser_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.graph.getFollowingUser#main"
	return lex.MarshalCBOR(w, t)
}

func (t *GraphGetFollowingUser_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// GraphGetFollowingUser calls the XRPC method "place.stream.graph.getFollowingUser".
//
// subjectDID: The DID of the user potentially being followed
// userDID: The DID of the potentially-following user
func GraphGetFollowingUser(ctx context.Context, c lexutil.LexClient, subjectDID string, userDID string) (*GraphGetFollowingUser_Output, error) {
	var out GraphGetFollowingUser_Output

	params := map[string]interface{}{}
	params["subjectDID"] = subjectDID
	params["userDID"] = userDID
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.graph.getFollowingUser", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
