// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.graph.getFollowingUser

package streamplace

import (
	"context"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GraphGetFollowingUser_Output is the output of a place.stream.graph.getFollowingUser call.
type GraphGetFollowingUser_Output struct {
	Follow *comatproto.RepoStrongRef `json:"follow,omitempty" cborgen:"follow,omitempty"`
}

// GraphGetFollowingUser calls the XRPC method "place.stream.graph.getFollowingUser".
//
// subjectDID: The DID of the user potentially being followed
// userDID: The DID of the potentially-following user
func GraphGetFollowingUser(ctx context.Context, c lexutil.LexClient, subjectDID string, userDID string) (*GraphGetFollowingUser_Output, error) {
	var out GraphGetFollowingUser_Output

	params := map[string]interface{}{}
	params["subjectDID"] = subjectDID
	params["userDID"] = userDID
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.graph.getFollowingUser", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
