// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.graph.getNotificationPreference

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// GraphGetNotificationPreference_Output is the output of a place.stream.graph.getNotificationPreference call.
type GraphGetNotificationPreference_Output struct {
	// enabled: Whether notifications are enabled. Defaults to true if no preference has been set.
	Enabled bool `json:"enabled" cborgen:"enabled"`
}

// GraphGetNotificationPreference calls the XRPC method "place.stream.graph.getNotificationPreference".
//
// repoDID: The DID of the streamer's repo.
func GraphGetNotificationPreference(ctx context.Context, c lexutil.LexClient, repoDID string) (*GraphGetNotificationPreference_Output, error) {
	var out GraphGetNotificationPreference_Output

	params := map[string]interface{}{}
	params["repoDID"] = repoDID
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.graph.getNotificationPreference", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
