// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.live.searchActorsTypeahead

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// LiveSearchActorsTypeahead_Actor is a "actor" in the place.stream.live.searchActorsTypeahead schema.
type LiveSearchActorsTypeahead_Actor struct {
	// did: The actor's DID
	Did string `json:"did" cborgen:"did"`
	// handle: The actor's handle
	Handle string `json:"handle" cborgen:"handle"`
}

// LiveSearchActorsTypeahead_Output is the output of a place.stream.live.searchActorsTypeahead call.
type LiveSearchActorsTypeahead_Output struct {
	Actors []*LiveSearchActorsTypeahead_Actor `json:"actors" cborgen:"actors"`
}

// LiveSearchActorsTypeahead calls the XRPC method "place.stream.live.searchActorsTypeahead".
//
// q: Search query prefix; not a full query string.
func LiveSearchActorsTypeahead(ctx context.Context, c lexutil.LexClient, limit int64, q string) (*LiveSearchActorsTypeahead_Output, error) {
	var out LiveSearchActorsTypeahead_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if q != "" {
		params["q"] = q
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.live.searchActorsTypeahead", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
