// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.media.getUploadStatus

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type MediaGetUploadStatus_Output struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.media.getUploadStatus#main"`
	// durationMs: Duration of the processed video in milliseconds. Present when status is 'done'.
	DurationMs *int64 `json:"durationMs,omitempty" cborgen:"durationMs,omitempty"`
	// error: Error message. Present when status is 'error'.
	Error *string `json:"error,omitempty" cborgen:"error,omitempty"`
	// progress: Processing progress percentage (0-100). Only meaningful when status is 'processing'.
	Progress *int64 `json:"progress,omitempty" cborgen:"progress,omitempty"`
	// status: Current processing status of the upload.
	Status string `json:"status" cborgen:"status"`
	// tracks: Published track records. Present when status is 'done'.
	Tracks []*MediaGetUploadStatus_TrackRef `json:"tracks,omitempty" cborgen:"tracks,omitempty"`
}

func (t *MediaGetUploadStatus_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.media.getUploadStatus#main"
	return lex.MarshalCBOR(w, t)
}

func (t *MediaGetUploadStatus_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaGetUploadStatus calls the XRPC method "place.stream.media.getUploadStatus".
//
// uploadId: The upload ID returned by place.stream.media.createUpload.
func MediaGetUploadStatus(ctx context.Context, c lexutil.LexClient, uploadId string) (*MediaGetUploadStatus_Output, error) {
	var out MediaGetUploadStatus_Output

	params := map[string]interface{}{}
	params["uploadId"] = uploadId
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.media.getUploadStatus", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// MediaGetUploadStatus_TrackRef is a "trackRef" in the place.stream.media.getUploadStatus schema.
type MediaGetUploadStatus_TrackRef struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.media.getUploadStatus"`
	Cid           string `json:"cid" cborgen:"cid"`
	Uri           string `json:"uri" cborgen:"uri"`
}

func (t *MediaGetUploadStatus_TrackRef) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.media.getUploadStatus"
	return lex.MarshalCBOR(w, t)
}

func (t *MediaGetUploadStatus_TrackRef) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
