// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.media.finalizeLivestream

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// MediaFinalizeLivestream_Input is the input argument to a place.stream.media.finalizeLivestream call.
type MediaFinalizeLivestream_Input struct {
	// livestream: AT-URI of the place.stream.livestream record to finalize into a VOD. Must belong to the authenticated user.
	Livestream string `json:"livestream" cborgen:"livestream"`
}

func (t *MediaFinalizeLivestream_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *MediaFinalizeLivestream_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaFinalizeLivestream_Output is the output of a place.stream.media.finalizeLivestream call.
type MediaFinalizeLivestream_Output struct {
	// draftUri: The ats:// URI of the draft VOD created for this finalize. The draft reaches status 'ready' when processing completes; the user publishes it from the Drafts tab via place.stream.vod.publishDraft.
	DraftUri string `json:"draftUri" cborgen:"draftUri"`
	// uploadId: Identifier for the finalize job. Retained for backwards compatibility; the draft flow no longer requires the client to poll getUploadStatus.
	UploadId string `json:"uploadId" cborgen:"uploadId"`
}

func (t *MediaFinalizeLivestream_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *MediaFinalizeLivestream_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaFinalizeLivestream calls the XRPC method "place.stream.media.finalizeLivestream".
func MediaFinalizeLivestream(ctx context.Context, c lexutil.LexClient, input *MediaFinalizeLivestream_Input) (*MediaFinalizeLivestream_Output, error) {
	var out MediaFinalizeLivestream_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.media.finalizeLivestream", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
