// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.media.viewCount

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.media.viewCount", &MediaViewCount{})
}

type MediaViewCount struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.media.viewCount"`
	// count: Number of distinct sessions that qualified as a view over [windowStart, windowEnd) by the stated methodology.
	Count int64 `json:"count" cborgen:"count"`
	// indexedAt: When the reporting node ran this aggregation. Useful for ordering successive reports.
	IndexedAt string `json:"indexedAt" cborgen:"indexedAt"`
	// methodology: Identifier for the counting algorithm. "any-segment" means: a distinct sid that fetched at least `thresholdSegments` segments for this video over the window. Future methodologies (e.g. "ms-from-metafile") will use new tags so older records remain interpretable.
	Methodology string `json:"methodology" cborgen:"methodology"`
	// thresholdSegments: Floor on segment_request count per (sid, video) for the "any-segment" methodology. Defaults to 1.
	ThresholdSegments *int64 `json:"thresholdSegments,omitempty" cborgen:"thresholdSegments,omitempty"`
	// tracks: Per-track totals of bytes + playback duration actually transferred over the window. Computed by intersecting each segment_request's HTTP Range with the metafile's per-track byte layout, so the numbers are objective regardless of the chosen view-counting methodology.
	Tracks []*MediaViewCount_TrackUsage `json:"tracks,omitempty" cborgen:"tracks,omitempty"`
	// video: AT-URI of the place.stream.video this count is for.
	Video string `json:"video" cborgen:"video"`
	// windowEnd: Exclusive upper bound of the aggregation window.
	WindowEnd string `json:"windowEnd" cborgen:"windowEnd"`
	// windowStart: Inclusive lower bound of the aggregation window.
	WindowStart string `json:"windowStart" cborgen:"windowStart"`
}

// MediaViewCount_TrackUsage is a "trackUsage" in the place.stream.media.viewCount schema.
//
// One row of the tracks array: bytes + duration transferred for a single muxlTrack inside the video's MUXL container over the window. trackId matches the muxlTrack record's `trackId` field.
type MediaViewCount_TrackUsage struct {
	// bytes: Total bytes served from this track's byte ranges over the window. Sum across attributed segment_requests' Range intersections with the track's segment offsets.
	Bytes int64 `json:"bytes" cborgen:"bytes"`
	// durationMs: Total playback duration served from this track, in milliseconds. Per HLS segment in the range: (overlap bytes / segment bytes) * segment duration, so partial-segment fetches credit a proportional share of duration.
	DurationMs int64 `json:"durationMs" cborgen:"durationMs"`
	// trackId: Stringified u32 matching the MUXL container's per-track id.
	TrackId string `json:"trackId" cborgen:"trackId"`
}
