// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.media.viewCount

package streamplace

import (
	"io"

	comatproto "github.com/bluesky-social/indigo/api/atproto"
	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.media.viewCount", &MediaViewCount{})
}

type MediaViewCount struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.media.viewCount"`
	// count: Number of distinct sessions the reporting node observed as a view over [windowStart, windowEnd).
	Count int64 `json:"count" cborgen:"count"`
	// indexedAt: When the reporting node ran this aggregation. Useful for ordering successive reports.
	IndexedAt string `json:"indexedAt" cborgen:"indexedAt"`
	// tracks: Per-track totals of bytes + playback duration the reporting node served over the window. Each entry references the place.stream.media.track record whose bytes were transferred, so user-contributed tracks (transcripts, transcodes published by other accounts) attribute naturally to their own records.
	Tracks []*MediaViewCount_TrackUsage `json:"tracks,omitempty" cborgen:"tracks,omitempty"`
	// video: AT-URI of the place.stream.video this count is for.
	Video string `json:"video" cborgen:"video"`
	// windowEnd: Exclusive upper bound of the aggregation window.
	WindowEnd string `json:"windowEnd" cborgen:"windowEnd"`
	// windowStart: Inclusive lower bound of the aggregation window.
	WindowStart string `json:"windowStart" cborgen:"windowStart"`
}

func (t *MediaViewCount) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.media.viewCount"
	return lex.MarshalCBOR(w, t)
}

func (t *MediaViewCount) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaViewCount_TrackUsage is a "trackUsage" in the place.stream.media.viewCount schema.
//
// One row of the tracks array: bytes + duration transferred for a single place.stream.media.track record over the window.
type MediaViewCount_TrackUsage struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=place.stream.media.viewCount#trackUsage,omitempty"`
	// bytes: Total bytes served from this track over the window. Sum across attributed segment_requests' Range intersections with the track's segment offsets in the metafile.
	Bytes int64 `json:"bytes" cborgen:"bytes"`
	// durationMs: Total playback duration served from this track, in milliseconds. Per HLS segment in the range: (overlap bytes / segment bytes) * segment duration, so partial-segment fetches credit a proportional share of duration.
	DurationMs int64 `json:"durationMs" cborgen:"durationMs"`
	// track: Strong reference to the place.stream.media.track record whose bytes were transferred.
	Track *comatproto.RepoStrongRef `json:"track" cborgen:"track"`
}

func (t *MediaViewCount_TrackUsage) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.media.viewCount#trackUsage"
	return lex.MarshalCBOR(w, t)
}

func (t *MediaViewCount_TrackUsage) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
