// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.media.publishVideo

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// MediaPublishVideo_Input is the input argument to a place.stream.media.publishVideo call.
type MediaPublishVideo_Input struct {
	// record: A place.stream.video record. The server overrides `source` and `durationMs` from the processed upload, and fills in `thumb` with a generated thumbnail when the supplied record has none.
	Record *Video `json:"record" cborgen:"record"`
	// uploadId: The upload ID returned by place.stream.media.createUpload. Its processing must be complete (status 'done').
	UploadId string `json:"uploadId" cborgen:"uploadId"`
}

func (t *MediaPublishVideo_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *MediaPublishVideo_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaPublishVideo_Output is the output of a place.stream.media.publishVideo call.
type MediaPublishVideo_Output struct {
	// cid: CID of the created place.stream.video record.
	Cid string `json:"cid" cborgen:"cid"`
	// uri: AT-URI of the created place.stream.video record.
	Uri string `json:"uri" cborgen:"uri"`
}

func (t *MediaPublishVideo_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *MediaPublishVideo_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// MediaPublishVideo calls the XRPC method "place.stream.media.publishVideo".
func MediaPublishVideo(ctx context.Context, c lexutil.LexClient, input *MediaPublishVideo_Input) (*MediaPublishVideo_Output, error) {
	var out MediaPublishVideo_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.media.publishVideo", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
