// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.media.origin

package streamplace

// MediaOrigin is a "main" in the place.stream.media.origin schema.
//
// A MUXL blob in one of the MUXL-supported formats.
type MediaOrigin struct {
	// muxlType: MUXL type of the archive (mp4, fmp4).
	MuxlType string `json:"muxlType" cborgen:"muxlType"`
	// ref: BLAKE-3 content hash (BDASL CID) of the archive.
	Ref string `json:"ref" cborgen:"ref"`
	// size: Size of the file in bytes.
	Size int64 `json:"size" cborgen:"size"`
}
