// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.media.createUpload

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// MediaCreateUpload_Input is the input argument to a place.stream.media.createUpload call.
type MediaCreateUpload_Input struct {
	// filename: Optional filename hint to attach as upload metadata.
	Filename *string `json:"filename,omitempty" cborgen:"filename,omitempty"`
	// mimeType: MIME type of the content being uploaded (e.g. video/mp4).
	MimeType string `json:"mimeType" cborgen:"mimeType"`
	// size: Total size of the upload in bytes.
	Size int64 `json:"size" cborgen:"size"`
}

// MediaCreateUpload_Output is the output of a place.stream.media.createUpload call.
type MediaCreateUpload_Output struct {
	// expiresAt: When the upload token expires.
	ExpiresAt string `json:"expiresAt" cborgen:"expiresAt"`
	// uploadId: Server-side identifier for this upload.
	UploadId string `json:"uploadId" cborgen:"uploadId"`
	// uploadToken: Short-lived bearer token bound to this upload. Send as 'Authorization: Bearer <token>' on TUS requests.
	UploadToken string `json:"uploadToken" cborgen:"uploadToken"`
	// uploadUrl: Absolute URL to PATCH/HEAD per the TUS protocol.
	UploadUrl string `json:"uploadUrl" cborgen:"uploadUrl"`
}

// MediaCreateUpload calls the XRPC method "place.stream.media.createUpload".
func MediaCreateUpload(ctx context.Context, c lexutil.LexClient, input *MediaCreateUpload_Input) (*MediaCreateUpload_Output, error) {
	var out MediaCreateUpload_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.media.createUpload", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
