// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.metadata.contentWarnings

package streamplace

// MetadataContentWarnings is a "main" in the place.stream.metadata.contentWarnings schema.
//
// Content warnings for a stream.
type MetadataContentWarnings struct {
	Warnings []string `json:"warnings,omitempty" cborgen:"warnings,omitempty"`
}
