// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.metadata.distributionPolicy

package streamplace

// MetadataDistributionPolicy is a "main" in the place.stream.metadata.distributionPolicy schema.
//
// Distribution and rebroadcast policy.
type MetadataDistributionPolicy struct {
	// allowedBroadcasters: List of did:webs of the broadcasters you want to allow to distribute your content. "*" allows anyone. Starting a line with a "!" bans that broadcaster.
	AllowedBroadcasters []string `json:"allowedBroadcasters,omitempty" cborgen:"allowedBroadcasters,omitempty"`
	// deleteAfter: Duration in seconds after which segments should be deleted. Each segment will expire N seconds after its creation time. -1 to allow indefinite archival.
	DeleteAfter *int64 `json:"deleteAfter,omitempty" cborgen:"deleteAfter,omitempty"`
}
