// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.metadata.contentWarnings

package streamplace

import (
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.metadata.contentWarnings#main", &MetadataContentWarnings{})
}

// Content warnings for a stream.
type MetadataContentWarnings struct {
	LexiconTypeID string   `json:"$type" cborgen:"$type,const=place.stream.metadata.contentWarnings"`
	Warnings      []string `json:"warnings,omitempty" cborgen:"warnings,omitempty"`
}

func (t *MetadataContentWarnings) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.metadata.contentWarnings"
	return lex.MarshalCBOR(w, t)
}

func (t *MetadataContentWarnings) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
