// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.metadata.configuration

package streamplace

import (
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.metadata.configuration", &MetadataConfiguration{})
}

type MetadataConfiguration struct {
	LexiconTypeID      string                      `json:"$type" cborgen:"$type,const=place.stream.metadata.configuration"`
	ContentRights      *MetadataContentRights      `json:"contentRights,omitempty" cborgen:"contentRights,omitempty"`
	ContentWarnings    *MetadataContentWarnings    `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	DistributionPolicy *MetadataDistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
}

func (t *MetadataConfiguration) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.metadata.configuration"
	return lex.MarshalCBOR(w, t)
}

func (t *MetadataConfiguration) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
