// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.permission

package streamplace

import (
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

func init() {
	lexutil.RegisterType("place.stream.moderation.permission", &ModerationPermission{})
}

// Record granting moderation permissions to a user for this streamer's content.
type ModerationPermission struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.permission"`
	// createdAt: Client-declared timestamp when this moderator was added.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// expirationTime: Optional expiration time for this delegation. If set, the delegation is invalid after this time.
	ExpirationTime *string `json:"expirationTime,omitempty" cborgen:"expirationTime,omitempty"`
	// moderator: The DID of the user granted moderator permissions.
	Moderator string `json:"moderator" cborgen:"moderator"`
	// permissions: Array of permissions granted to this moderator. 'ban' covers blocks/bans (with optional expiration), 'hide' covers message gates, 'livestream.manage' allows updating livestream metadata.
	Permissions []string `json:"permissions" cborgen:"permissions"`
}

func (t *ModerationPermission) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.permission"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationPermission) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}
