// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.deletePin

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type ModerationDeletePin_Input struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.deletePin#main"`
	// pinUri: The AT-URI of the pinned record to delete.
	PinUri string `json:"pinUri" cborgen:"pinUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
}

func (t *ModerationDeletePin_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.deletePin#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeletePin_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

type ModerationDeletePin_Output struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.deletePin#main"`
}

func (t *ModerationDeletePin_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.deletePin#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeletePin_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationDeletePin calls the XRPC method "place.stream.moderation.deletePin".
func ModerationDeletePin(ctx context.Context, c lexutil.LexClient, input *ModerationDeletePin_Input) (*ModerationDeletePin_Output, error) {
	var out ModerationDeletePin_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.deletePin", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
