// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.updateLivestream

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ModerationUpdateLivestream_Input is the input argument to a place.stream.moderation.updateLivestream call.
type ModerationUpdateLivestream_Input struct {
	// livestreamUri: The AT-URI of the livestream record to update.
	LivestreamUri string `json:"livestreamUri" cborgen:"livestreamUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
	// title: New title for the livestream.
	Title *string `json:"title,omitempty" cborgen:"title,omitempty"`
}

func (t *ModerationUpdateLivestream_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationUpdateLivestream_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationUpdateLivestream_Output is the output of a place.stream.moderation.updateLivestream call.
type ModerationUpdateLivestream_Output struct {
	// cid: The CID of the updated livestream record.
	Cid string `json:"cid" cborgen:"cid"`
	// uri: The AT-URI of the updated livestream record.
	Uri string `json:"uri" cborgen:"uri"`
}

func (t *ModerationUpdateLivestream_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationUpdateLivestream_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationUpdateLivestream calls the XRPC method "place.stream.moderation.updateLivestream".
func ModerationUpdateLivestream(ctx context.Context, c lexutil.LexClient, input *ModerationUpdateLivestream_Input) (*ModerationUpdateLivestream_Output, error) {
	var out ModerationUpdateLivestream_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.updateLivestream", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
