// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.createVodGate

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type ModerationCreateVodGate_Input struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.createVodGate#main"`
	// commentUri: The AT-URI of the VOD comment to hide.
	CommentUri string `json:"commentUri" cborgen:"commentUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
}

func (t *ModerationCreateVodGate_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.createVodGate#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationCreateVodGate_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

type ModerationCreateVodGate_Output struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.createVodGate#main"`
	// cid: The CID of the created gate record.
	Cid string `json:"cid" cborgen:"cid"`
	// uri: The AT-URI of the created gate record.
	Uri string `json:"uri" cborgen:"uri"`
}

func (t *ModerationCreateVodGate_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.createVodGate#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationCreateVodGate_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationCreateVodGate calls the XRPC method "place.stream.moderation.createVodGate".
func ModerationCreateVodGate(ctx context.Context, c lexutil.LexClient, input *ModerationCreateVodGate_Input) (*ModerationCreateVodGate_Output, error) {
	var out ModerationCreateVodGate_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.createVodGate", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
