// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.deleteVodGate

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ModerationDeleteVodGate_Input is the input argument to a place.stream.moderation.deleteVodGate call.
type ModerationDeleteVodGate_Input struct {
	// gateUri: The AT-URI of the gate record to delete.
	GateUri string `json:"gateUri" cborgen:"gateUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
}

func (t *ModerationDeleteVodGate_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeleteVodGate_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationDeleteVodGate_Output is the output of a place.stream.moderation.deleteVodGate call.
type ModerationDeleteVodGate_Output struct {
}

func (t *ModerationDeleteVodGate_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeleteVodGate_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationDeleteVodGate calls the XRPC method "place.stream.moderation.deleteVodGate".
func ModerationDeleteVodGate(ctx context.Context, c lexutil.LexClient, input *ModerationDeleteVodGate_Input) (*ModerationDeleteVodGate_Output, error) {
	var out ModerationDeleteVodGate_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.deleteVodGate", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
