// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.moderation.deleteGate

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type ModerationDeleteGate_Input struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.deleteGate#main"`
	// gateUri: The AT-URI of the gate record to delete.
	GateUri string `json:"gateUri" cborgen:"gateUri"`
	// streamer: The DID of the streamer.
	Streamer string `json:"streamer" cborgen:"streamer"`
}

func (t *ModerationDeleteGate_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.deleteGate#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeleteGate_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

type ModerationDeleteGate_Output struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.moderation.deleteGate#main"`
}

func (t *ModerationDeleteGate_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.moderation.deleteGate#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ModerationDeleteGate_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ModerationDeleteGate calls the XRPC method "place.stream.moderation.deleteGate".
func ModerationDeleteGate(ctx context.Context, c lexutil.LexClient, input *ModerationDeleteGate_Input) (*ModerationDeleteGate_Output, error) {
	var out ModerationDeleteGate_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.moderation.deleteGate", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
