// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.multistream.createTarget

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// MultistreamCreateTarget_Input is the input argument to a place.stream.multistream.createTarget call.
type MultistreamCreateTarget_Input struct {
	MultistreamTarget *MultistreamTarget `json:"multistreamTarget" cborgen:"multistreamTarget"`
}

// MultistreamCreateTarget calls the XRPC method "place.stream.multistream.createTarget".
func MultistreamCreateTarget(ctx context.Context, c util.LexClient, input *MultistreamCreateTarget_Input) (*MultistreamDefs_TargetView, error) {
	var out MultistreamDefs_TargetView
	if err := c.LexDo(ctx, util.Procedure, "application/json", "place.stream.multistream.createTarget", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
