// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.multistream.target

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.multistream.target", &MultistreamTarget{})
}

type MultistreamTarget struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.multistream.target"`
	// active: Whether this target is currently active.
	Active bool `json:"active" cborgen:"active"`
	// createdAt: When this target was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// name: A user-friendly name for this target.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// url: The rtmp:// or rtmps:// url of the target server.
	Url string `json:"url" cborgen:"url"`
}
