// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.muxl.defs

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// MuxlDefs_Archive is a "archive" in the place.stream.muxl.defs schema.
//
// A MUXL archive fMP4 file, identified by its BLAKE-3 content hash.
type MuxlDefs_Archive struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.muxl.defs#archive"`
	// data: Blob ref to the MUXL archive fMP4. The CID is the BLAKE-3 hash of the file.
	Data *lexutil.LexBlob `json:"data" cborgen:"data"`
}

// MuxlDefs_ArchiveBlob is a "archiveBlob" in the place.stream.muxl.defs schema.
//
// A MUXL archive fMP4 file referenced by CID without requiring the blob on the PDS.
type MuxlDefs_ArchiveBlob struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.muxl.defs#archiveBlob"`
	// mimeType: MIME type of the archive (video/mp4).
	MimeType string `json:"mimeType" cborgen:"mimeType"`
	// ref: BLAKE-3 content hash (CID) of the archive.
	Ref string `json:"ref" cborgen:"ref"`
	// size: Size of the archive in bytes.
	Size int64 `json:"size" cborgen:"size"`
}

// MuxlDefs_AudioTrack is a "audioTrack" in the place.stream.muxl.defs schema.
type MuxlDefs_AudioTrack struct {
	// channels: Number of audio channels.
	Channels int64 `json:"channels" cborgen:"channels"`
	// codec: WebCodecs codec string, e.g. 'opus', 'mp4a.40.2'.
	Codec string `json:"codec" cborgen:"codec"`
	// sampleRate: Sample rate in Hz.
	SampleRate int64 `json:"sampleRate" cborgen:"sampleRate"`
	// timescale: Media timescale (ticks per second).
	Timescale int64 `json:"timescale" cborgen:"timescale"`
	// trackId: MP4 track ID.
	TrackId int64 `json:"trackId" cborgen:"trackId"`
}

// MuxlDefs_Catalog is a "catalog" in the place.stream.muxl.defs schema.
//
// Track configuration describing all media tracks.
type MuxlDefs_Catalog struct {
	Audio []*MuxlDefs_AudioTrack `json:"audio,omitempty" cborgen:"audio,omitempty"`
	Video []*MuxlDefs_VideoTrack `json:"video,omitempty" cborgen:"video,omitempty"`
}

// MuxlDefs_VideoTrack is a "videoTrack" in the place.stream.muxl.defs schema.
type MuxlDefs_VideoTrack struct {
	// codec: WebCodecs codec string, e.g. 'avc1.64002A'.
	Codec string `json:"codec" cborgen:"codec"`
	// height: Coded pixel height.
	Height int64 `json:"height" cborgen:"height"`
	// timescale: Media timescale (ticks per second).
	Timescale int64 `json:"timescale" cborgen:"timescale"`
	// trackId: MP4 track ID.
	TrackId int64 `json:"trackId" cborgen:"trackId"`
	// width: Coded pixel width.
	Width int64 `json:"width" cborgen:"width"`
}
