// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.playback.getLivePlaylist

package streamplace

import (
	"bytes"
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// PlaybackGetLivePlaylist calls the XRPC method "place.stream.playback.getLivePlaylist".
//
// sid: Opaque playback session identifier. Omit on the master playlist request; the server generates one and threads it through the sub-playlist + segment URLs it returns, for view-count correlation.
// streamer: The streamer to play back: a DID (did:plc/did:web/did:key) or a Bluesky handle, which is resolved to its DID.
// track: Track ID (stringified u32 matching the MUXL container) for a single-track media playlist. Omit for the master playlist.
func PlaybackGetLivePlaylist(ctx context.Context, c lexutil.LexClient, sid string, streamer string, track string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if sid != "" {
		params["sid"] = sid
	}
	params["streamer"] = streamer
	if track != "" {
		params["track"] = track
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.playback.getLivePlaylist", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
