// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.playback.getVideoBlob

package streamplace

import (
	"bytes"
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// PlaybackGetVideoBlob calls the XRPC method "place.stream.playback.getVideoBlob".
//
// cid: Optional CID of a specific segment blob. If provided, returns the segment data directly instead of resolving from the virtual archive.
// did: DID of the video creator.
// rkey: Record key of the place.stream.video record.
func PlaybackGetVideoBlob(ctx context.Context, c lexutil.LexClient, cid string, did string, rkey string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if cid != "" {
		params["cid"] = cid
	}
	params["did"] = did
	params["rkey"] = rkey
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.playback.getVideoBlob", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
