// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.playback.getVideoBlob

package streamplace

import (
	"bytes"
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// PlaybackGetVideoBlob calls the XRPC method "place.stream.playback.getVideoBlob".
//
// cid: BLAKE-3 BDASL CID of the requested blob.
// did: DID of the account that owns the record this blob is being served for. Used for egress/usage accounting, not for access control — the blob is served purely by CID.
// sid: Opaque playback session identifier, propagated unmodified from the media playlist that referenced this blob. Logged for view-count correlation; not used for access control.
func PlaybackGetVideoBlob(ctx context.Context, c lexutil.LexClient, cid string, did string, sid string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if sid != "" {
		params["sid"] = sid
	}
	params["cid"] = cid
	params["did"] = did
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.playback.getVideoBlob", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
