// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.playback.whep

package streamplace

import (
	"bytes"
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// PlaybackWhep calls the XRPC method "place.stream.playback.whep".
//
// rendition: The rendition of the stream to play.
// streamer: The DID of the streamer to play.
func PlaybackWhep(ctx context.Context, c lexutil.LexClient, input io.Reader, rendition string, streamer string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	params["rendition"] = rendition
	params["streamer"] = streamer
	if err := c.LexDo(ctx, lexutil.Procedure, "*/*", "place.stream.playback.whep", params, input, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
