// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.server.settings

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.server.settings", &ServerSettings{})
}

type ServerSettings struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.server.settings"`
	// debugRecording: Whether this node may archive your livestream for improving the service
	DebugRecording *bool `json:"debugRecording,omitempty" cborgen:"debugRecording,omitempty"`
	// livestreamRecording: Whether this node should record your livestreams into VODs that you can publish
	LivestreamRecording *bool `json:"livestreamRecording,omitempty" cborgen:"livestreamRecording,omitempty"`
}
