// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.server.getStorage

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ServerGetStorage_Output is the output of a place.stream.server.getStorage call.
type ServerGetStorage_Output struct {
	Storage *ServerDefs_Storage `json:"storage,omitempty" cborgen:"storage,omitempty"`
}

func (t *ServerGetStorage_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ServerGetStorage_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ServerGetStorage calls the XRPC method "place.stream.server.getStorage".
func ServerGetStorage(ctx context.Context, c lexutil.LexClient) (*ServerGetStorage_Output, error) {
	var out ServerGetStorage_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.server.getStorage", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
