// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.server.getStorage

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// ServerGetStorage_Output is the output of a place.stream.server.getStorage call.
type ServerGetStorage_Output struct {
	Storage *ServerDefs_Storage `json:"storage,omitempty" cborgen:"storage,omitempty"`
}

// ServerGetStorage calls the XRPC method "place.stream.server.getStorage".
func ServerGetStorage(ctx context.Context, c lexutil.LexClient) (*ServerGetStorage_Output, error) {
	var out ServerGetStorage_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.server.getStorage", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
