// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.server.deleteStorage

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ServerDeleteStorage_Output is the output of a place.stream.server.deleteStorage call.
type ServerDeleteStorage_Output struct {
	Success bool `json:"success" cborgen:"success"`
}

func (t *ServerDeleteStorage_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ServerDeleteStorage_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ServerDeleteStorage calls the XRPC method "place.stream.server.deleteStorage".
func ServerDeleteStorage(ctx context.Context, c lexutil.LexClient) (*ServerDeleteStorage_Output, error) {
	var out ServerDeleteStorage_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "", "place.stream.server.deleteStorage", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
