// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.server.getServerTime

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ServerGetServerTime_Output is the output of a place.stream.server.getServerTime call.
type ServerGetServerTime_Output struct {
	// serverTime: Current server time in RFC3339 format
	ServerTime string `json:"serverTime" cborgen:"serverTime"`
}

func (t *ServerGetServerTime_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ServerGetServerTime_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ServerGetServerTime calls the XRPC method "place.stream.server.getServerTime".
func ServerGetServerTime(ctx context.Context, c lexutil.LexClient) (*ServerGetServerTime_Output, error) {
	var out ServerGetServerTime_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.server.getServerTime", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
