// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.server.deleteWebhook

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type ServerDeleteWebhook_Input struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.server.deleteWebhook#main"`
	// id: The ID of the webhook to delete.
	Id string `json:"id" cborgen:"id"`
}

func (t *ServerDeleteWebhook_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.server.deleteWebhook#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ServerDeleteWebhook_Input) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

type ServerDeleteWebhook_Output struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=place.stream.server.deleteWebhook#main"`
	// success: Whether the webhook was successfully deleted.
	Success bool `json:"success" cborgen:"success"`
}

func (t *ServerDeleteWebhook_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.server.deleteWebhook#main"
	return lex.MarshalCBOR(w, t)
}

func (t *ServerDeleteWebhook_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ServerDeleteWebhook calls the XRPC method "place.stream.server.deleteWebhook".
func ServerDeleteWebhook(ctx context.Context, c lexutil.LexClient, input *ServerDeleteWebhook_Input) (*ServerDeleteWebhook_Output, error) {
	var out ServerDeleteWebhook_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.server.deleteWebhook", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
