// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.server.defs

// ServerDefs_RewriteRule is a "rewriteRule" in the place.stream.server.defs schema.
type ServerDefs_RewriteRule struct {
	// from: Text to search for and replace.
	From string `json:"from" cborgen:"from"`
	// to: Text to replace with.
	To string `json:"to" cborgen:"to"`
}

// ServerDefs_Webhook is a "webhook" in the place.stream.server.defs schema.
//
// A webhook configuration for receiving Streamplace events.
type ServerDefs_Webhook struct {
	// active: Whether this webhook is currently active.
	Active bool `json:"active" cborgen:"active"`
	// createdAt: When this webhook was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// description: A description of what this webhook is used for.
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	// errorCount: Number of consecutive errors for this webhook.
	ErrorCount *int64 `json:"errorCount,omitempty" cborgen:"errorCount,omitempty"`
	// events: The types of events this webhook should receive.
	Events []string `json:"events" cborgen:"events"`
	// id: Unique identifier for this webhook.
	Id string `json:"id" cborgen:"id"`
	// lastTriggered: When this webhook was last triggered.
	LastTriggered *string `json:"lastTriggered,omitempty" cborgen:"lastTriggered,omitempty"`
	// name: A user-friendly name for this webhook.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// prefix: Text to prepend to webhook messages.
	Prefix *string `json:"prefix,omitempty" cborgen:"prefix,omitempty"`
	// rewrite: Text replacement rules for webhook messages.
	Rewrite []*ServerDefs_RewriteRule `json:"rewrite,omitempty" cborgen:"rewrite,omitempty"`
	// suffix: Text to append to webhook messages.
	Suffix *string `json:"suffix,omitempty" cborgen:"suffix,omitempty"`
	// updatedAt: When this webhook was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" cborgen:"updatedAt,omitempty"`
	// url: The webhook URL where events will be sent.
	Url string `json:"url" cborgen:"url"`
}
