// Code generated by streamplace/cobalt lexgen (see Makefile's go-lexicons); DO NOT EDIT.

// Lexicon schema: place.stream.server.getWebhook

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

// ServerGetWebhook_Output is the output of a place.stream.server.getWebhook call.
type ServerGetWebhook_Output struct {
	Webhook *ServerDefs_Webhook `json:"webhook" cborgen:"webhook"`
}

func (t *ServerGetWebhook_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	return lex.MarshalCBOR(w, t)
}

func (t *ServerGetWebhook_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// ServerGetWebhook calls the XRPC method "place.stream.server.getWebhook".
//
// id: The ID of the webhook to retrieve.
func ServerGetWebhook(ctx context.Context, c lexutil.LexClient, id string) (*ServerGetWebhook_Output, error) {
	var out ServerGetWebhook_Output

	params := map[string]interface{}{}
	params["id"] = id
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.server.getWebhook", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
