// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.segment

package streamplace

import (
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

func init() {
	lexutil.RegisterType("place.stream.segment", &Segment{})
}

type Segment struct {
	LexiconTypeID      string                      `json:"$type" cborgen:"$type,const=place.stream.segment"`
	Audio              []*Segment_Audio            `json:"audio,omitempty" cborgen:"audio,omitempty"`
	ContentRights      *MetadataContentRights      `json:"contentRights,omitempty" cborgen:"contentRights,omitempty"`
	ContentWarnings    *MetadataContentWarnings    `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	Creator            string                      `json:"creator" cborgen:"creator"`
	DistributionPolicy *MetadataDistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
	// duration: The duration of the segment in nanoseconds
	Duration *int64 `json:"duration,omitempty" cborgen:"duration,omitempty"`
	// id: Unique identifier for the segment
	Id string `json:"id" cborgen:"id"`
	// signingKey: The DID of the signing key used for this segment
	SigningKey string `json:"signingKey" cborgen:"signingKey"`
	// size: The size of the segment in bytes
	Size *int64 `json:"size,omitempty" cborgen:"size,omitempty"`
	// startTime: When this segment started
	StartTime string           `json:"startTime" cborgen:"startTime"`
	Video     []*Segment_Video `json:"video,omitempty" cborgen:"video,omitempty"`
}

// Segment_Audio is a "audio" in the place.stream.segment schema.
type Segment_Audio struct {
	Channels int64  `json:"channels" cborgen:"channels"`
	Codec    string `json:"codec" cborgen:"codec"`
	Rate     int64  `json:"rate" cborgen:"rate"`
}

// Segment_Framerate is a "framerate" in the place.stream.segment schema.
type Segment_Framerate struct {
	Den int64 `json:"den" cborgen:"den"`
	Num int64 `json:"num" cborgen:"num"`
}

// Segment_SegmentView is a "segmentView" in the place.stream.segment schema.
type Segment_SegmentView struct {
	Cid    string                      `json:"cid" cborgen:"cid"`
	Record *lexutil.LexiconTypeDecoder `json:"record" cborgen:"record"`
}

// Segment_Video is a "video" in the place.stream.segment schema.
type Segment_Video struct {
	Bframes   *bool              `json:"bframes,omitempty" cborgen:"bframes,omitempty"`
	Codec     string             `json:"codec" cborgen:"codec"`
	Framerate *Segment_Framerate `json:"framerate,omitempty" cborgen:"framerate,omitempty"`
	Height    int64              `json:"height" cborgen:"height"`
	Width     int64              `json:"width" cborgen:"width"`
}
