// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.segment

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.segment", &Segment{})
} //
// RECORDTYPE: Segment
type Segment struct {
	LexiconTypeID string           `json:"$type,const=place.stream.segment" cborgen:"$type,const=place.stream.segment"`
	Audio         []*Segment_Audio `json:"audio,omitempty" cborgen:"audio,omitempty"`
	Creator       string           `json:"creator" cborgen:"creator"`
	// id: Unique identifier for the segment
	Id string `json:"id" cborgen:"id"`
	// signingKey: The DID of the signing key used for this segment
	SigningKey string `json:"signingKey" cborgen:"signingKey"`
	// startTime: When this segment started
	StartTime string           `json:"startTime" cborgen:"startTime"`
	Video     []*Segment_Video `json:"video,omitempty" cborgen:"video,omitempty"`
}

// Segment_Audio is a "audio" in the place.stream.segment schema.
type Segment_Audio struct {
	Channels int64  `json:"channels" cborgen:"channels"`
	Codec    string `json:"codec" cborgen:"codec"`
	Rate     int64  `json:"rate" cborgen:"rate"`
}

// Segment_Video is a "video" in the place.stream.segment schema.
type Segment_Video struct {
	Codec  string `json:"codec" cborgen:"codec"`
	Height int64  `json:"height" cborgen:"height"`
	Width  int64  `json:"width" cborgen:"width"`
}
