// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.vod.defs

package streamplace

import (
	"encoding/json"
	"fmt"

	appbsky "github.com/bluesky-social/indigo/api/bsky"
	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// VodDefs_CommentView is a "commentView" in the place.stream.vod.defs schema.
type VodDefs_CommentView struct {
	LexiconTypeID string                              `json:"$type" cborgen:"$type,const=place.stream.vod.defs#commentView"`
	Author        *appbsky.ActorDefs_ProfileViewBasic `json:"author" cborgen:"author"`
	Cid           string                              `json:"cid" cborgen:"cid"`
	IndexedAt     string                              `json:"indexedAt" cborgen:"indexedAt"`
	// likeCount: Number of likes on this comment.
	LikeCount int64                        `json:"likeCount" cborgen:"likeCount"`
	Record    *lexutil.LexiconTypeDecoder  `json:"record" cborgen:"record"`
	ReplyTo   *VodDefs_CommentView_ReplyTo `json:"replyTo,omitempty" cborgen:"replyTo,omitempty"`
	Uri       string                       `json:"uri" cborgen:"uri"`
}

type VodDefs_CommentView_ReplyTo struct {
	VodDefs_CommentView *VodDefs_CommentView
}

func (t *VodDefs_CommentView_ReplyTo) MarshalJSON() ([]byte, error) {
	if t.VodDefs_CommentView != nil {
		t.VodDefs_CommentView.LexiconTypeID = "place.stream.vod.defs#commentView"
		return json.Marshal(t.VodDefs_CommentView)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *VodDefs_CommentView_ReplyTo) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.vod.defs#commentView":
		t.VodDefs_CommentView = new(VodDefs_CommentView)
		return json.Unmarshal(b, t.VodDefs_CommentView)
	default:
		return nil
	}
}
