// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.vod.getComments

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// VodGetComments_Output is the output of a place.stream.vod.getComments call.
type VodGetComments_Output struct {
	Comments []*VodDefs_CommentView `json:"comments" cborgen:"comments"`
	Cursor   *string                `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
}

// VodGetComments calls the XRPC method "place.stream.vod.getComments".
//
// cursor: Optional pagination cursor.
// limit: Maximum number of comments to return.
// video: AT-URI of the place.stream.video record.
func VodGetComments(ctx context.Context, c lexutil.LexClient, cursor string, limit int64, video string) (*VodGetComments_Output, error) {
	var out VodGetComments_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["video"] = video
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.vod.getComments", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
