// Code generated by glex (legacy mode); DO NOT EDIT.

// Lexicon schema: place.stream.vod.getDraft

package streamplace

import (
	"context"
	"io"

	lexutil "github.com/bluesky-social/indigo/lex/util"
	cbg "github.com/whyrusleeping/cbor-gen"
	lex "stream.place/streamplace/pkg/lex"
)

type VodGetDraft_Output struct {
	LexiconTypeID string                  `json:"$type" cborgen:"$type,const=place.stream.vod.getDraft#main"`
	Draft         *VodDraftDefs_DraftView `json:"draft" cborgen:"draft"`
}

func (t *VodGetDraft_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "place.stream.vod.getDraft#main"
	return lex.MarshalCBOR(w, t)
}

func (t *VodGetDraft_Output) UnmarshalCBOR(r io.Reader) error {
	return lex.UnmarshalCBOR(r, t)
}

// VodGetDraft calls the XRPC method "place.stream.vod.getDraft".
//
// uri: The ats:// URI of the draft record.
func VodGetDraft(ctx context.Context, c lexutil.LexClient, uri string) (*VodGetDraft_Output, error) {
	var out VodGetDraft_Output

	params := map[string]interface{}{}
	params["uri"] = uri
	if err := c.LexDo(ctx, lexutil.Query, "", "place.stream.vod.getDraft", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
