// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: place.stream.vod.publishDraft

package streamplace

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// VodPublishDraft_Input is the input argument to a place.stream.vod.publishDraft call.
type VodPublishDraft_Input struct {
	// uri: The ats:// URI of the draft to publish. Must have status 'ready'.
	Uri string `json:"uri" cborgen:"uri"`
}

// VodPublishDraft_Output is the output of a place.stream.vod.publishDraft call.
type VodPublishDraft_Output struct {
	// videoCid: CID of the created place.stream.video record.
	VideoCid string `json:"videoCid" cborgen:"videoCid"`
	// videoUri: AT-URI of the created place.stream.video record.
	VideoUri string `json:"videoUri" cborgen:"videoUri"`
}

// VodPublishDraft calls the XRPC method "place.stream.vod.publishDraft".
func VodPublishDraft(ctx context.Context, c lexutil.LexClient, input *VodPublishDraft_Input) (*VodPublishDraft_Output, error) {
	var out VodPublishDraft_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "place.stream.vod.publishDraft", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
