// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.actor.status

package appbsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("app.bsky.actor.status", &ActorStatus{})
}

// A declaration of a Bluesky account status.
type ActorStatus struct {
	LexiconTypeID string `json:"$type,omitempty"`
	CreatedAt     string `json:"createdAt"`
	// durationMinutes: The duration of the status in minutes. Applications can choose to impose minimum and maximum limits.
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`
	// embed: An optional embed associated with the status.
	Embed *ActorStatus_Embed `json:"embed,omitempty"`
	// status: The status for the account.
	Status string `json:"status"`
}

// RecordTypeID implements glex.Record.
func (t *ActorStatus) RecordTypeID() string { return "app.bsky.actor.status" }

// MarshalJSON stamps the $type field, like MarshalCBOR does.
func (t *ActorStatus) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "app.bsky.actor.status"
	type alias ActorStatus
	return json.Marshal((*alias)(t))
}

func (t *ActorStatus) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.actor.status"
	return glex.MarshalCBOR(w, t)
}

func (t *ActorStatus) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// An optional embed associated with the status.
type ActorStatus_Embed struct {
	EmbedExternal *EmbedExternal
}

func (t *ActorStatus_Embed) MarshalJSON() ([]byte, error) {
	if t.EmbedExternal != nil {
		t.EmbedExternal.LexiconTypeID = "app.bsky.embed.external"
		return json.Marshal(t.EmbedExternal)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *ActorStatus_Embed) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external":
		t.EmbedExternal = new(EmbedExternal)
		return json.Unmarshal(b, t.EmbedExternal)
	default:
		return nil
	}
}

func (t *ActorStatus_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedExternal != nil {
		return t.EmbedExternal.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *ActorStatus_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glex.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external":
		t.EmbedExternal = new(EmbedExternal)
		return t.EmbedExternal.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}
