// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.actor.getProfiles

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type ActorGetProfiles_Output struct {
	LexiconTypeID string                          `json:"$type"`
	Profiles      []ActorDefs_ProfileViewDetailed `json:"profiles"`
}

func (t *ActorGetProfiles_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.actor.getProfiles#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *ActorGetProfiles_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// ActorGetProfiles calls the XRPC method "app.bsky.actor.getProfiles".
//
// Get detailed profile views of multiple actors.
func ActorGetProfiles(ctx context.Context, c glexrt.LexClient, actors []string) (*ActorGetProfiles_Output, error) {
	var out ActorGetProfiles_Output

	params := map[string]interface{}{}
	params["actors"] = actors

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.actor.getProfiles", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
