// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.ageassurance.defs

package appbsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

// AgeassuranceDefs_Config is a "config" in the app.bsky.ageassurance.defs schema.
type AgeassuranceDefs_Config struct {
	LexiconTypeID string `json:"$type"`
	// regions: The per-region Age Assurance configuration.
	Regions []AgeassuranceDefs_ConfigRegion `json:"regions"`
}

func (t *AgeassuranceDefs_Config) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_Config) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegion is a "configRegion" in the app.bsky.ageassurance.defs schema.
//
// The Age Assurance configuration for a specific region.
type AgeassuranceDefs_ConfigRegion struct {
	LexiconTypeID string `json:"$type"`
	// countryCode: The ISO 3166-1 alpha-2 country code this configuration applies to.
	CountryCode string `json:"countryCode"`
	// regionCode: The ISO 3166-2 region code this configuration applies to. If omitted, the configuration applies to the entire country.
	RegionCode *string `json:"regionCode,omitempty"`
	// rules: The ordered list of Age Assurance rules that apply to this region. Rules should be applied in order, and the first matching rule determines the access level granted. The rules array should always include a default rule as the last item.
	Rules []AgeassuranceDefs_ConfigRegion_Rules_Elem `json:"rules"`
}

func (t *AgeassuranceDefs_ConfigRegion) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegion) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type AgeassuranceDefs_ConfigRegion_Rules_Elem struct {
	AgeassuranceDefs_ConfigRegionRuleDefault            *AgeassuranceDefs_ConfigRegionRuleDefault
	AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan *AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan
	AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan *AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan
	AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge   *AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge
	AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge  *AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge
	AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge  *AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge
	AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge *AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) MarshalJSON() ([]byte, error) {
	if t.AgeassuranceDefs_ConfigRegionRuleDefault != nil {
		t.AgeassuranceDefs_ConfigRegionRuleDefault.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleDefault"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleDefault)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge != nil {
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge.LexiconTypeID = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge"
		return json.Marshal(t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.ageassurance.defs#configRegionRuleDefault":
		t.AgeassuranceDefs_ConfigRegionRuleDefault = new(AgeassuranceDefs_ConfigRegionRuleDefault)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleDefault)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
		return json.Unmarshal(b, t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
	default:
		return nil
	}
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.AgeassuranceDefs_ConfigRegionRuleDefault != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleDefault.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge.MarshalCBOR(w)
	}
	if t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge != nil {
		return t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *AgeassuranceDefs_ConfigRegion_Rules_Elem) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.ageassurance.defs#configRegionRuleDefault":
		t.AgeassuranceDefs_ConfigRegionRuleDefault = new(AgeassuranceDefs_ConfigRegionRuleDefault)
		return t.AgeassuranceDefs_ConfigRegionRuleDefault.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountNewerThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan)
		return t.AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfAccountOlderThan":
		t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan = new(AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan)
		return t.AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge)
		return t.AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfAssuredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge)
		return t.AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredOverAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge)
		return t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge":
		t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge = new(AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge)
		return t.AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// AgeassuranceDefs_ConfigRegionRuleDefault is a "configRegionRuleDefault" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies by default.
type AgeassuranceDefs_ConfigRegionRuleDefault struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleDefault) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleDefault) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan is a "configRegionRuleIfAccountNewerThan" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the account is equal-to or newer than a certain date.
type AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// date: The date threshold as a datetime string.
	Date string `json:"date"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAccountNewerThan) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan is a "configRegionRuleIfAccountOlderThan" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the account is older than a certain date.
type AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// date: The date threshold as a datetime string.
	Date string `json:"date"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAccountOlderThan) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge is a "configRegionRuleIfAssuredOverAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has been assured to be equal-to or over a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAssuredOverAge) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge is a "configRegionRuleIfAssuredUnderAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has been assured to be under a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfAssuredUnderAge) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge is a "configRegionRuleIfDeclaredOverAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has declared themselves equal-to or over a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfDeclaredOverAge) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge is a "configRegionRuleIfDeclaredUnderAge" in the app.bsky.ageassurance.defs schema.
//
// Age Assurance rule that applies if the user has declared themselves under a certain age.
type AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// age: The age threshold as a whole integer.
	Age int64 `json:"age"`
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_ConfigRegionRuleIfDeclaredUnderAge) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_Event is a "event" in the app.bsky.ageassurance.defs schema.
//
// Object used to store Age Assurance data in stash.
type AgeassuranceDefs_Event struct {
	LexiconTypeID string `json:"$type"`
	// access: The access level granted based on Age Assurance data we've processed.
	Access string `json:"access"`
	// attemptId: The unique identifier for this instance of the Age Assurance flow, in UUID format.
	AttemptId string `json:"attemptId"`
	// completeIp: The IP address used when completing the Age Assurance flow.
	CompleteIp *string `json:"completeIp,omitempty"`
	// completeUa: The user agent used when completing the Age Assurance flow.
	CompleteUa *string `json:"completeUa,omitempty"`
	// countryCode: The ISO 3166-1 alpha-2 country code provided when beginning the Age Assurance flow.
	CountryCode string `json:"countryCode"`
	// createdAt: The date and time of this write operation.
	CreatedAt string `json:"createdAt"`
	// email: The email used for Age Assurance.
	Email *string `json:"email,omitempty"`
	// initIp: The IP address used when initiating the Age Assurance flow.
	InitIp *string `json:"initIp,omitempty"`
	// initUa: The user agent used when initiating the Age Assurance flow.
	InitUa *string `json:"initUa,omitempty"`
	// regionCode: The ISO 3166-2 region code provided when beginning the Age Assurance flow.
	RegionCode *string `json:"regionCode,omitempty"`
	// status: The status of the Age Assurance process.
	Status string `json:"status"`
}

func (t *AgeassuranceDefs_Event) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_Event) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_State is a "state" in the app.bsky.ageassurance.defs schema.
//
// The user's computed Age Assurance state.
type AgeassuranceDefs_State struct {
	LexiconTypeID string `json:"$type"`
	Access        string `json:"access"`
	// lastInitiatedAt: The timestamp when this state was last updated.
	LastInitiatedAt *string `json:"lastInitiatedAt,omitempty"`
	Status          string  `json:"status"`
}

func (t *AgeassuranceDefs_State) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_State) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// AgeassuranceDefs_StateMetadata is a "stateMetadata" in the app.bsky.ageassurance.defs schema.
//
// Additional metadata needed to compute Age Assurance state client-side.
type AgeassuranceDefs_StateMetadata struct {
	LexiconTypeID string `json:"$type"`
	// accountCreatedAt: The account creation timestamp.
	AccountCreatedAt *string `json:"accountCreatedAt,omitempty"`
}

func (t *AgeassuranceDefs_StateMetadata) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.ageassurance.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *AgeassuranceDefs_StateMetadata) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
