// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.embed.record

package appbsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	comatproto "stream.place/streamplace/pkg/comatproto"
)

func init() {
	glex.RegisterType("app.bsky.embed.record#main", &EmbedRecord{})
}

type EmbedRecord struct {
	LexiconTypeID string                   `json:"$type,omitempty"`
	Record        comatproto.RepoStrongRef `json:"record"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord) RecordTypeID() string { return "app.bsky.embed.record" }

// MarshalJSON stamps the $type field, like MarshalCBOR does.
func (t *EmbedRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "app.bsky.embed.record"
	type alias EmbedRecord
	return json.Marshal((*alias)(t))
}

func (t *EmbedRecord) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// EmbedRecord_View is a "view" in the app.bsky.embed.record schema.
type EmbedRecord_View struct {
	LexiconTypeID string                  `json:"$type,omitempty"`
	Record        EmbedRecord_View_Record `json:"record"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord_View) RecordTypeID() string { return "app.bsky.embed.record#view" }

func (t *EmbedRecord_View) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record#view"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord_View) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type EmbedRecord_View_Record struct {
	EmbedRecord_ViewBlocked        *EmbedRecord_ViewBlocked
	EmbedRecord_ViewDetached       *EmbedRecord_ViewDetached
	EmbedRecord_ViewNotFound       *EmbedRecord_ViewNotFound
	EmbedRecord_ViewRecord         *EmbedRecord_ViewRecord
	FeedDefs_GeneratorView         *FeedDefs_GeneratorView
	GraphDefs_ListView             *GraphDefs_ListView
	GraphDefs_StarterPackViewBasic *GraphDefs_StarterPackViewBasic
	LabelerDefs_LabelerView        *LabelerDefs_LabelerView
}

func (t *EmbedRecord_View_Record) MarshalJSON() ([]byte, error) {
	if t.EmbedRecord_ViewBlocked != nil {
		t.EmbedRecord_ViewBlocked.LexiconTypeID = "app.bsky.embed.record#viewBlocked"
		return json.Marshal(t.EmbedRecord_ViewBlocked)
	}
	if t.EmbedRecord_ViewDetached != nil {
		t.EmbedRecord_ViewDetached.LexiconTypeID = "app.bsky.embed.record#viewDetached"
		return json.Marshal(t.EmbedRecord_ViewDetached)
	}
	if t.EmbedRecord_ViewNotFound != nil {
		t.EmbedRecord_ViewNotFound.LexiconTypeID = "app.bsky.embed.record#viewNotFound"
		return json.Marshal(t.EmbedRecord_ViewNotFound)
	}
	if t.EmbedRecord_ViewRecord != nil {
		t.EmbedRecord_ViewRecord.LexiconTypeID = "app.bsky.embed.record#viewRecord"
		return json.Marshal(t.EmbedRecord_ViewRecord)
	}
	if t.FeedDefs_GeneratorView != nil {
		t.FeedDefs_GeneratorView.LexiconTypeID = "app.bsky.feed.defs#generatorView"
		return json.Marshal(t.FeedDefs_GeneratorView)
	}
	if t.GraphDefs_ListView != nil {
		t.GraphDefs_ListView.LexiconTypeID = "app.bsky.graph.defs#listView"
		return json.Marshal(t.GraphDefs_ListView)
	}
	if t.GraphDefs_StarterPackViewBasic != nil {
		t.GraphDefs_StarterPackViewBasic.LexiconTypeID = "app.bsky.graph.defs#starterPackViewBasic"
		return json.Marshal(t.GraphDefs_StarterPackViewBasic)
	}
	if t.LabelerDefs_LabelerView != nil {
		t.LabelerDefs_LabelerView.LexiconTypeID = "app.bsky.labeler.defs#labelerView"
		return json.Marshal(t.LabelerDefs_LabelerView)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *EmbedRecord_View_Record) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.record#viewBlocked":
		t.EmbedRecord_ViewBlocked = new(EmbedRecord_ViewBlocked)
		return json.Unmarshal(b, t.EmbedRecord_ViewBlocked)
	case "app.bsky.embed.record#viewDetached":
		t.EmbedRecord_ViewDetached = new(EmbedRecord_ViewDetached)
		return json.Unmarshal(b, t.EmbedRecord_ViewDetached)
	case "app.bsky.embed.record#viewNotFound":
		t.EmbedRecord_ViewNotFound = new(EmbedRecord_ViewNotFound)
		return json.Unmarshal(b, t.EmbedRecord_ViewNotFound)
	case "app.bsky.embed.record#viewRecord":
		t.EmbedRecord_ViewRecord = new(EmbedRecord_ViewRecord)
		return json.Unmarshal(b, t.EmbedRecord_ViewRecord)
	case "app.bsky.feed.defs#generatorView":
		t.FeedDefs_GeneratorView = new(FeedDefs_GeneratorView)
		return json.Unmarshal(b, t.FeedDefs_GeneratorView)
	case "app.bsky.graph.defs#listView":
		t.GraphDefs_ListView = new(GraphDefs_ListView)
		return json.Unmarshal(b, t.GraphDefs_ListView)
	case "app.bsky.graph.defs#starterPackViewBasic":
		t.GraphDefs_StarterPackViewBasic = new(GraphDefs_StarterPackViewBasic)
		return json.Unmarshal(b, t.GraphDefs_StarterPackViewBasic)
	case "app.bsky.labeler.defs#labelerView":
		t.LabelerDefs_LabelerView = new(LabelerDefs_LabelerView)
		return json.Unmarshal(b, t.LabelerDefs_LabelerView)
	default:
		return nil
	}
}

func (t *EmbedRecord_View_Record) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedRecord_ViewBlocked != nil {
		return t.EmbedRecord_ViewBlocked.MarshalCBOR(w)
	}
	if t.EmbedRecord_ViewDetached != nil {
		return t.EmbedRecord_ViewDetached.MarshalCBOR(w)
	}
	if t.EmbedRecord_ViewNotFound != nil {
		return t.EmbedRecord_ViewNotFound.MarshalCBOR(w)
	}
	if t.EmbedRecord_ViewRecord != nil {
		return t.EmbedRecord_ViewRecord.MarshalCBOR(w)
	}
	if t.FeedDefs_GeneratorView != nil {
		return t.FeedDefs_GeneratorView.MarshalCBOR(w)
	}
	if t.GraphDefs_ListView != nil {
		return t.GraphDefs_ListView.MarshalCBOR(w)
	}
	if t.GraphDefs_StarterPackViewBasic != nil {
		return t.GraphDefs_StarterPackViewBasic.MarshalCBOR(w)
	}
	if t.LabelerDefs_LabelerView != nil {
		return t.LabelerDefs_LabelerView.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *EmbedRecord_View_Record) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glex.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.record#viewBlocked":
		t.EmbedRecord_ViewBlocked = new(EmbedRecord_ViewBlocked)
		return t.EmbedRecord_ViewBlocked.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record#viewDetached":
		t.EmbedRecord_ViewDetached = new(EmbedRecord_ViewDetached)
		return t.EmbedRecord_ViewDetached.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record#viewNotFound":
		t.EmbedRecord_ViewNotFound = new(EmbedRecord_ViewNotFound)
		return t.EmbedRecord_ViewNotFound.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record#viewRecord":
		t.EmbedRecord_ViewRecord = new(EmbedRecord_ViewRecord)
		return t.EmbedRecord_ViewRecord.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#generatorView":
		t.FeedDefs_GeneratorView = new(FeedDefs_GeneratorView)
		return t.FeedDefs_GeneratorView.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.graph.defs#listView":
		t.GraphDefs_ListView = new(GraphDefs_ListView)
		return t.GraphDefs_ListView.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.graph.defs#starterPackViewBasic":
		t.GraphDefs_StarterPackViewBasic = new(GraphDefs_StarterPackViewBasic)
		return t.GraphDefs_StarterPackViewBasic.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.labeler.defs#labelerView":
		t.LabelerDefs_LabelerView = new(LabelerDefs_LabelerView)
		return t.LabelerDefs_LabelerView.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// EmbedRecord_ViewBlocked is a "viewBlocked" in the app.bsky.embed.record schema.
type EmbedRecord_ViewBlocked struct {
	LexiconTypeID string                 `json:"$type,omitempty"`
	Author        FeedDefs_BlockedAuthor `json:"author"`
	Blocked       bool                   `json:"blocked"`
	Uri           string                 `json:"uri"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord_ViewBlocked) RecordTypeID() string { return "app.bsky.embed.record#viewBlocked" }

func (t *EmbedRecord_ViewBlocked) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record#viewBlocked"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord_ViewBlocked) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// EmbedRecord_ViewDetached is a "viewDetached" in the app.bsky.embed.record schema.
type EmbedRecord_ViewDetached struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Detached      bool   `json:"detached"`
	Uri           string `json:"uri"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord_ViewDetached) RecordTypeID() string { return "app.bsky.embed.record#viewDetached" }

func (t *EmbedRecord_ViewDetached) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record#viewDetached"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord_ViewDetached) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// EmbedRecord_ViewNotFound is a "viewNotFound" in the app.bsky.embed.record schema.
type EmbedRecord_ViewNotFound struct {
	LexiconTypeID string `json:"$type,omitempty"`
	NotFound      bool   `json:"notFound"`
	Uri           string `json:"uri"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord_ViewNotFound) RecordTypeID() string { return "app.bsky.embed.record#viewNotFound" }

func (t *EmbedRecord_ViewNotFound) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record#viewNotFound"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord_ViewNotFound) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// EmbedRecord_ViewRecord is a "viewRecord" in the app.bsky.embed.record schema.
type EmbedRecord_ViewRecord struct {
	LexiconTypeID string                               `json:"$type,omitempty"`
	Author        ActorDefs_ProfileViewBasic           `json:"author"`
	Cid           string                               `json:"cid"`
	Embeds        []EmbedRecord_ViewRecord_Embeds_Elem `json:"embeds,omitempty"`
	IndexedAt     string                               `json:"indexedAt"`
	Labels        []comatproto.LabelDefs_Label         `json:"labels,omitempty"`
	LikeCount     *int64                               `json:"likeCount,omitempty"`
	QuoteCount    *int64                               `json:"quoteCount,omitempty"`
	ReplyCount    *int64                               `json:"replyCount,omitempty"`
	RepostCount   *int64                               `json:"repostCount,omitempty"`
	Uri           string                               `json:"uri"`
	// value: The record data itself.
	Value *glex.LexiconTypeDecoder `json:"value"`
}

// RecordTypeID implements glex.Record.
func (t *EmbedRecord_ViewRecord) RecordTypeID() string { return "app.bsky.embed.record#viewRecord" }

func (t *EmbedRecord_ViewRecord) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.embed.record#viewRecord"
	return glex.MarshalCBOR(w, t)
}

func (t *EmbedRecord_ViewRecord) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type EmbedRecord_ViewRecord_Embeds_Elem struct {
	EmbedExternal_View        *EmbedExternal_View
	EmbedGallery_View         *EmbedGallery_View
	EmbedImages_View          *EmbedImages_View
	EmbedRecordWithMedia_View *EmbedRecordWithMedia_View
	EmbedRecord_View          *EmbedRecord_View
	EmbedVideo_View           *EmbedVideo_View
}

func (t *EmbedRecord_ViewRecord_Embeds_Elem) MarshalJSON() ([]byte, error) {
	if t.EmbedExternal_View != nil {
		t.EmbedExternal_View.LexiconTypeID = "app.bsky.embed.external#view"
		return json.Marshal(t.EmbedExternal_View)
	}
	if t.EmbedGallery_View != nil {
		t.EmbedGallery_View.LexiconTypeID = "app.bsky.embed.gallery#view"
		return json.Marshal(t.EmbedGallery_View)
	}
	if t.EmbedImages_View != nil {
		t.EmbedImages_View.LexiconTypeID = "app.bsky.embed.images#view"
		return json.Marshal(t.EmbedImages_View)
	}
	if t.EmbedRecordWithMedia_View != nil {
		t.EmbedRecordWithMedia_View.LexiconTypeID = "app.bsky.embed.recordWithMedia#view"
		return json.Marshal(t.EmbedRecordWithMedia_View)
	}
	if t.EmbedRecord_View != nil {
		t.EmbedRecord_View.LexiconTypeID = "app.bsky.embed.record#view"
		return json.Marshal(t.EmbedRecord_View)
	}
	if t.EmbedVideo_View != nil {
		t.EmbedVideo_View.LexiconTypeID = "app.bsky.embed.video#view"
		return json.Marshal(t.EmbedVideo_View)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *EmbedRecord_ViewRecord_Embeds_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external#view":
		t.EmbedExternal_View = new(EmbedExternal_View)
		return json.Unmarshal(b, t.EmbedExternal_View)
	case "app.bsky.embed.gallery#view":
		t.EmbedGallery_View = new(EmbedGallery_View)
		return json.Unmarshal(b, t.EmbedGallery_View)
	case "app.bsky.embed.images#view":
		t.EmbedImages_View = new(EmbedImages_View)
		return json.Unmarshal(b, t.EmbedImages_View)
	case "app.bsky.embed.recordWithMedia#view":
		t.EmbedRecordWithMedia_View = new(EmbedRecordWithMedia_View)
		return json.Unmarshal(b, t.EmbedRecordWithMedia_View)
	case "app.bsky.embed.record#view":
		t.EmbedRecord_View = new(EmbedRecord_View)
		return json.Unmarshal(b, t.EmbedRecord_View)
	case "app.bsky.embed.video#view":
		t.EmbedVideo_View = new(EmbedVideo_View)
		return json.Unmarshal(b, t.EmbedVideo_View)
	default:
		return nil
	}
}

func (t *EmbedRecord_ViewRecord_Embeds_Elem) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedExternal_View != nil {
		return t.EmbedExternal_View.MarshalCBOR(w)
	}
	if t.EmbedGallery_View != nil {
		return t.EmbedGallery_View.MarshalCBOR(w)
	}
	if t.EmbedImages_View != nil {
		return t.EmbedImages_View.MarshalCBOR(w)
	}
	if t.EmbedRecordWithMedia_View != nil {
		return t.EmbedRecordWithMedia_View.MarshalCBOR(w)
	}
	if t.EmbedRecord_View != nil {
		return t.EmbedRecord_View.MarshalCBOR(w)
	}
	if t.EmbedVideo_View != nil {
		return t.EmbedVideo_View.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *EmbedRecord_ViewRecord_Embeds_Elem) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glex.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external#view":
		t.EmbedExternal_View = new(EmbedExternal_View)
		return t.EmbedExternal_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.gallery#view":
		t.EmbedGallery_View = new(EmbedGallery_View)
		return t.EmbedGallery_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.images#view":
		t.EmbedImages_View = new(EmbedImages_View)
		return t.EmbedImages_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.recordWithMedia#view":
		t.EmbedRecordWithMedia_View = new(EmbedRecordWithMedia_View)
		return t.EmbedRecordWithMedia_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record#view":
		t.EmbedRecord_View = new(EmbedRecord_View)
		return t.EmbedRecord_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.video#view":
		t.EmbedVideo_View = new(EmbedVideo_View)
		return t.EmbedVideo_View.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}
