// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.getFeedSkeleton

package appbsky

import (
	"context"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type FeedGetFeedSkeleton_Output struct {
	LexiconTypeID string                      `json:"$type,omitempty"`
	Cursor        *string                     `json:"cursor,omitempty"`
	Feed          []FeedDefs_SkeletonFeedPost `json:"feed"`
	// reqId: Unique identifier per request that may be passed back alongside interactions.
	ReqId *string `json:"reqId,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *FeedGetFeedSkeleton_Output) RecordTypeID() string { return "app.bsky.feed.getFeedSkeleton" }

func (t *FeedGetFeedSkeleton_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "app.bsky.feed.getFeedSkeleton"
	return glex.MarshalCBOR(w, &cp)
}

func (t *FeedGetFeedSkeleton_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// FeedGetFeedSkeleton calls the XRPC method "app.bsky.feed.getFeedSkeleton".
//
// Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service.
//
// feed: Reference to feed generator record describing the specific feed being requested.
func FeedGetFeedSkeleton(ctx context.Context, c glex.LexClient, cursor string, feed string, limit *int64) (*FeedGetFeedSkeleton_Output, error) {
	var out FeedGetFeedSkeleton_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	params["feed"] = feed

	if err := c.LexDo(ctx, glex.Query, "", "app.bsky.feed.getFeedSkeleton", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
