// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.getFeedGenerators

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type FeedGetFeedGenerators_Output struct {
	LexiconTypeID string                   `json:"$type"`
	Feeds         []FeedDefs_GeneratorView `json:"feeds"`
}

func (t *FeedGetFeedGenerators_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.getFeedGenerators#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedGetFeedGenerators_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedGetFeedGenerators calls the XRPC method "app.bsky.feed.getFeedGenerators".
//
// Get information about a list of feed generators.
func FeedGetFeedGenerators(ctx context.Context, c glexrt.LexClient, feeds []string) (*FeedGetFeedGenerators_Output, error) {
	var out FeedGetFeedGenerators_Output

	params := map[string]interface{}{}
	params["feeds"] = feeds

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.feed.getFeedGenerators", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
