// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.defs

package appbsky

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	comatproto "stream.place/streamplace/pkg/comatproto"
)

// FeedDefs_BlockedAuthor is a "blockedAuthor" in the app.bsky.feed.defs schema.
type FeedDefs_BlockedAuthor struct {
	LexiconTypeID string                 `json:"$type"`
	Did           string                 `json:"did"`
	Viewer        *ActorDefs_ViewerState `json:"viewer,omitempty"`
}

func (t *FeedDefs_BlockedAuthor) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_BlockedAuthor) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_BlockedPost is a "blockedPost" in the app.bsky.feed.defs schema.
type FeedDefs_BlockedPost struct {
	LexiconTypeID string                 `json:"$type"`
	Author        FeedDefs_BlockedAuthor `json:"author"`
	Blocked       bool                   `json:"blocked"`
	Uri           string                 `json:"uri"`
}

func (t *FeedDefs_BlockedPost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_BlockedPost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_FeedViewPost is a "feedViewPost" in the app.bsky.feed.defs schema.
type FeedDefs_FeedViewPost struct {
	LexiconTypeID string `json:"$type"`
	// feedContext: Context provided by feed generator that may be passed back alongside interactions.
	FeedContext *string                       `json:"feedContext,omitempty"`
	Post        FeedDefs_PostView             `json:"post"`
	Reason      *FeedDefs_FeedViewPost_Reason `json:"reason,omitempty"`
	Reply       *FeedDefs_ReplyRef            `json:"reply,omitempty"`
	// reqId: Unique identifier per request that may be passed back alongside interactions.
	ReqId *string `json:"reqId,omitempty"`
}

func (t *FeedDefs_FeedViewPost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_FeedViewPost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type FeedDefs_FeedViewPost_Reason struct {
	FeedDefs_ReasonPin    *FeedDefs_ReasonPin
	FeedDefs_ReasonRepost *FeedDefs_ReasonRepost
}

func (t *FeedDefs_FeedViewPost_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_ReasonPin != nil {
		t.FeedDefs_ReasonPin.LexiconTypeID = "app.bsky.feed.defs#reasonPin"
		return json.Marshal(t.FeedDefs_ReasonPin)
	}
	if t.FeedDefs_ReasonRepost != nil {
		t.FeedDefs_ReasonRepost.LexiconTypeID = "app.bsky.feed.defs#reasonRepost"
		return json.Marshal(t.FeedDefs_ReasonRepost)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_FeedViewPost_Reason) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#reasonPin":
		t.FeedDefs_ReasonPin = new(FeedDefs_ReasonPin)
		return json.Unmarshal(b, t.FeedDefs_ReasonPin)
	case "app.bsky.feed.defs#reasonRepost":
		t.FeedDefs_ReasonRepost = new(FeedDefs_ReasonRepost)
		return json.Unmarshal(b, t.FeedDefs_ReasonRepost)
	default:
		return nil
	}
}

func (t *FeedDefs_FeedViewPost_Reason) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_ReasonPin != nil {
		return t.FeedDefs_ReasonPin.MarshalCBOR(w)
	}
	if t.FeedDefs_ReasonRepost != nil {
		return t.FeedDefs_ReasonRepost.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_FeedViewPost_Reason) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#reasonPin":
		t.FeedDefs_ReasonPin = new(FeedDefs_ReasonPin)
		return t.FeedDefs_ReasonPin.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#reasonRepost":
		t.FeedDefs_ReasonRepost = new(FeedDefs_ReasonRepost)
		return t.FeedDefs_ReasonRepost.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedDefs_GeneratorView is a "generatorView" in the app.bsky.feed.defs schema.
type FeedDefs_GeneratorView struct {
	LexiconTypeID       string                         `json:"$type"`
	AcceptsInteractions *bool                          `json:"acceptsInteractions,omitempty"`
	Avatar              *string                        `json:"avatar,omitempty"`
	Cid                 string                         `json:"cid"`
	ContentMode         *string                        `json:"contentMode,omitempty"`
	Creator             ActorDefs_ProfileView          `json:"creator"`
	Description         *string                        `json:"description,omitempty"`
	DescriptionFacets   []RichtextFacet                `json:"descriptionFacets,omitempty"`
	Did                 string                         `json:"did"`
	DisplayName         string                         `json:"displayName"`
	IndexedAt           string                         `json:"indexedAt"`
	Labels              []comatproto.LabelDefs_Label   `json:"labels,omitempty"`
	LikeCount           *int64                         `json:"likeCount,omitempty"`
	Uri                 string                         `json:"uri"`
	Viewer              *FeedDefs_GeneratorViewerState `json:"viewer,omitempty"`
}

func (t *FeedDefs_GeneratorView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_GeneratorView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_GeneratorViewerState is a "generatorViewerState" in the app.bsky.feed.defs schema.
type FeedDefs_GeneratorViewerState struct {
	LexiconTypeID string  `json:"$type"`
	Like          *string `json:"like,omitempty"`
}

func (t *FeedDefs_GeneratorViewerState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_GeneratorViewerState) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_Interaction is a "interaction" in the app.bsky.feed.defs schema.
type FeedDefs_Interaction struct {
	LexiconTypeID string  `json:"$type"`
	Event         *string `json:"event,omitempty"`
	// feedContext: Context on a feed item that was originally supplied by the feed generator on getFeedSkeleton.
	FeedContext *string `json:"feedContext,omitempty"`
	Item        *string `json:"item,omitempty"`
	// reqId: Unique identifier per request that may be passed back alongside interactions.
	ReqId *string `json:"reqId,omitempty"`
}

func (t *FeedDefs_Interaction) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_Interaction) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_NotFoundPost is a "notFoundPost" in the app.bsky.feed.defs schema.
type FeedDefs_NotFoundPost struct {
	LexiconTypeID string `json:"$type"`
	NotFound      bool   `json:"notFound"`
	Uri           string `json:"uri"`
}

func (t *FeedDefs_NotFoundPost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_NotFoundPost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_PostView is a "postView" in the app.bsky.feed.defs schema.
type FeedDefs_PostView struct {
	LexiconTypeID string                     `json:"$type"`
	Author        ActorDefs_ProfileViewBasic `json:"author"`
	BookmarkCount *int64                     `json:"bookmarkCount,omitempty"`
	Cid           string                     `json:"cid"`
	// debug: Debug information for internal development
	Debug       *glexrt.LexiconTypeDecoder   `json:"debug,omitempty"`
	Embed       *FeedDefs_PostView_Embed     `json:"embed,omitempty"`
	IndexedAt   string                       `json:"indexedAt"`
	Labels      []comatproto.LabelDefs_Label `json:"labels,omitempty"`
	LikeCount   *int64                       `json:"likeCount,omitempty"`
	QuoteCount  *int64                       `json:"quoteCount,omitempty"`
	Record      *glexrt.LexiconTypeDecoder   `json:"record"`
	ReplyCount  *int64                       `json:"replyCount,omitempty"`
	RepostCount *int64                       `json:"repostCount,omitempty"`
	Threadgate  *FeedDefs_ThreadgateView     `json:"threadgate,omitempty"`
	Uri         string                       `json:"uri"`
	Viewer      *FeedDefs_ViewerState        `json:"viewer,omitempty"`
}

func (t *FeedDefs_PostView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_PostView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type FeedDefs_PostView_Embed struct {
	EmbedExternal_View        *EmbedExternal_View
	EmbedImages_View          *EmbedImages_View
	EmbedRecordWithMedia_View *EmbedRecordWithMedia_View
	EmbedRecord_View          *EmbedRecord_View
	EmbedVideo_View           *EmbedVideo_View
}

func (t *FeedDefs_PostView_Embed) MarshalJSON() ([]byte, error) {
	if t.EmbedExternal_View != nil {
		t.EmbedExternal_View.LexiconTypeID = "app.bsky.embed.external#view"
		return json.Marshal(t.EmbedExternal_View)
	}
	if t.EmbedImages_View != nil {
		t.EmbedImages_View.LexiconTypeID = "app.bsky.embed.images#view"
		return json.Marshal(t.EmbedImages_View)
	}
	if t.EmbedRecordWithMedia_View != nil {
		t.EmbedRecordWithMedia_View.LexiconTypeID = "app.bsky.embed.recordWithMedia#view"
		return json.Marshal(t.EmbedRecordWithMedia_View)
	}
	if t.EmbedRecord_View != nil {
		t.EmbedRecord_View.LexiconTypeID = "app.bsky.embed.record#view"
		return json.Marshal(t.EmbedRecord_View)
	}
	if t.EmbedVideo_View != nil {
		t.EmbedVideo_View.LexiconTypeID = "app.bsky.embed.video#view"
		return json.Marshal(t.EmbedVideo_View)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_PostView_Embed) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external#view":
		t.EmbedExternal_View = new(EmbedExternal_View)
		return json.Unmarshal(b, t.EmbedExternal_View)
	case "app.bsky.embed.images#view":
		t.EmbedImages_View = new(EmbedImages_View)
		return json.Unmarshal(b, t.EmbedImages_View)
	case "app.bsky.embed.recordWithMedia#view":
		t.EmbedRecordWithMedia_View = new(EmbedRecordWithMedia_View)
		return json.Unmarshal(b, t.EmbedRecordWithMedia_View)
	case "app.bsky.embed.record#view":
		t.EmbedRecord_View = new(EmbedRecord_View)
		return json.Unmarshal(b, t.EmbedRecord_View)
	case "app.bsky.embed.video#view":
		t.EmbedVideo_View = new(EmbedVideo_View)
		return json.Unmarshal(b, t.EmbedVideo_View)
	default:
		return nil
	}
}

func (t *FeedDefs_PostView_Embed) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.EmbedExternal_View != nil {
		return t.EmbedExternal_View.MarshalCBOR(w)
	}
	if t.EmbedImages_View != nil {
		return t.EmbedImages_View.MarshalCBOR(w)
	}
	if t.EmbedRecordWithMedia_View != nil {
		return t.EmbedRecordWithMedia_View.MarshalCBOR(w)
	}
	if t.EmbedRecord_View != nil {
		return t.EmbedRecord_View.MarshalCBOR(w)
	}
	if t.EmbedVideo_View != nil {
		return t.EmbedVideo_View.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_PostView_Embed) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.embed.external#view":
		t.EmbedExternal_View = new(EmbedExternal_View)
		return t.EmbedExternal_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.images#view":
		t.EmbedImages_View = new(EmbedImages_View)
		return t.EmbedImages_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.recordWithMedia#view":
		t.EmbedRecordWithMedia_View = new(EmbedRecordWithMedia_View)
		return t.EmbedRecordWithMedia_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.record#view":
		t.EmbedRecord_View = new(EmbedRecord_View)
		return t.EmbedRecord_View.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.embed.video#view":
		t.EmbedVideo_View = new(EmbedVideo_View)
		return t.EmbedVideo_View.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedDefs_ReasonPin is a "reasonPin" in the app.bsky.feed.defs schema.
type FeedDefs_ReasonPin struct {
	LexiconTypeID string `json:"$type"`
}

func (t *FeedDefs_ReasonPin) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ReasonPin) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_ReasonRepost is a "reasonRepost" in the app.bsky.feed.defs schema.
type FeedDefs_ReasonRepost struct {
	LexiconTypeID string                     `json:"$type"`
	By            ActorDefs_ProfileViewBasic `json:"by"`
	Cid           *string                    `json:"cid,omitempty"`
	IndexedAt     string                     `json:"indexedAt"`
	Uri           *string                    `json:"uri,omitempty"`
}

func (t *FeedDefs_ReasonRepost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ReasonRepost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_ReplyRef is a "replyRef" in the app.bsky.feed.defs schema.
type FeedDefs_ReplyRef struct {
	LexiconTypeID string `json:"$type"`
	// grandparentAuthor: When parent is a reply to another post, this is the author of that post.
	GrandparentAuthor *ActorDefs_ProfileViewBasic `json:"grandparentAuthor,omitempty"`
	Parent            FeedDefs_ReplyRef_Parent    `json:"parent"`
	Root              FeedDefs_ReplyRef_Root      `json:"root"`
}

func (t *FeedDefs_ReplyRef) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ReplyRef) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type FeedDefs_ReplyRef_Parent struct {
	FeedDefs_BlockedPost  *FeedDefs_BlockedPost
	FeedDefs_NotFoundPost *FeedDefs_NotFoundPost
	FeedDefs_PostView     *FeedDefs_PostView
}

func (t *FeedDefs_ReplyRef_Parent) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_BlockedPost != nil {
		t.FeedDefs_BlockedPost.LexiconTypeID = "app.bsky.feed.defs#blockedPost"
		return json.Marshal(t.FeedDefs_BlockedPost)
	}
	if t.FeedDefs_NotFoundPost != nil {
		t.FeedDefs_NotFoundPost.LexiconTypeID = "app.bsky.feed.defs#notFoundPost"
		return json.Marshal(t.FeedDefs_NotFoundPost)
	}
	if t.FeedDefs_PostView != nil {
		t.FeedDefs_PostView.LexiconTypeID = "app.bsky.feed.defs#postView"
		return json.Marshal(t.FeedDefs_PostView)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_ReplyRef_Parent) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return json.Unmarshal(b, t.FeedDefs_BlockedPost)
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return json.Unmarshal(b, t.FeedDefs_NotFoundPost)
	case "app.bsky.feed.defs#postView":
		t.FeedDefs_PostView = new(FeedDefs_PostView)
		return json.Unmarshal(b, t.FeedDefs_PostView)
	default:
		return nil
	}
}

func (t *FeedDefs_ReplyRef_Parent) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_BlockedPost != nil {
		return t.FeedDefs_BlockedPost.MarshalCBOR(w)
	}
	if t.FeedDefs_NotFoundPost != nil {
		return t.FeedDefs_NotFoundPost.MarshalCBOR(w)
	}
	if t.FeedDefs_PostView != nil {
		return t.FeedDefs_PostView.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_ReplyRef_Parent) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return t.FeedDefs_BlockedPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return t.FeedDefs_NotFoundPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#postView":
		t.FeedDefs_PostView = new(FeedDefs_PostView)
		return t.FeedDefs_PostView.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

type FeedDefs_ReplyRef_Root struct {
	FeedDefs_BlockedPost  *FeedDefs_BlockedPost
	FeedDefs_NotFoundPost *FeedDefs_NotFoundPost
	FeedDefs_PostView     *FeedDefs_PostView
}

func (t *FeedDefs_ReplyRef_Root) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_BlockedPost != nil {
		t.FeedDefs_BlockedPost.LexiconTypeID = "app.bsky.feed.defs#blockedPost"
		return json.Marshal(t.FeedDefs_BlockedPost)
	}
	if t.FeedDefs_NotFoundPost != nil {
		t.FeedDefs_NotFoundPost.LexiconTypeID = "app.bsky.feed.defs#notFoundPost"
		return json.Marshal(t.FeedDefs_NotFoundPost)
	}
	if t.FeedDefs_PostView != nil {
		t.FeedDefs_PostView.LexiconTypeID = "app.bsky.feed.defs#postView"
		return json.Marshal(t.FeedDefs_PostView)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_ReplyRef_Root) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return json.Unmarshal(b, t.FeedDefs_BlockedPost)
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return json.Unmarshal(b, t.FeedDefs_NotFoundPost)
	case "app.bsky.feed.defs#postView":
		t.FeedDefs_PostView = new(FeedDefs_PostView)
		return json.Unmarshal(b, t.FeedDefs_PostView)
	default:
		return nil
	}
}

func (t *FeedDefs_ReplyRef_Root) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_BlockedPost != nil {
		return t.FeedDefs_BlockedPost.MarshalCBOR(w)
	}
	if t.FeedDefs_NotFoundPost != nil {
		return t.FeedDefs_NotFoundPost.MarshalCBOR(w)
	}
	if t.FeedDefs_PostView != nil {
		return t.FeedDefs_PostView.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_ReplyRef_Root) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return t.FeedDefs_BlockedPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return t.FeedDefs_NotFoundPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#postView":
		t.FeedDefs_PostView = new(FeedDefs_PostView)
		return t.FeedDefs_PostView.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedDefs_SkeletonFeedPost is a "skeletonFeedPost" in the app.bsky.feed.defs schema.
type FeedDefs_SkeletonFeedPost struct {
	LexiconTypeID string `json:"$type"`
	// feedContext: Context that will be passed through to client and may be passed to feed generator back alongside interactions.
	FeedContext *string                           `json:"feedContext,omitempty"`
	Post        string                            `json:"post"`
	Reason      *FeedDefs_SkeletonFeedPost_Reason `json:"reason,omitempty"`
}

func (t *FeedDefs_SkeletonFeedPost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_SkeletonFeedPost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type FeedDefs_SkeletonFeedPost_Reason struct {
	FeedDefs_SkeletonReasonPin    *FeedDefs_SkeletonReasonPin
	FeedDefs_SkeletonReasonRepost *FeedDefs_SkeletonReasonRepost
}

func (t *FeedDefs_SkeletonFeedPost_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_SkeletonReasonPin != nil {
		t.FeedDefs_SkeletonReasonPin.LexiconTypeID = "app.bsky.feed.defs#skeletonReasonPin"
		return json.Marshal(t.FeedDefs_SkeletonReasonPin)
	}
	if t.FeedDefs_SkeletonReasonRepost != nil {
		t.FeedDefs_SkeletonReasonRepost.LexiconTypeID = "app.bsky.feed.defs#skeletonReasonRepost"
		return json.Marshal(t.FeedDefs_SkeletonReasonRepost)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_SkeletonFeedPost_Reason) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#skeletonReasonPin":
		t.FeedDefs_SkeletonReasonPin = new(FeedDefs_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonPin)
	case "app.bsky.feed.defs#skeletonReasonRepost":
		t.FeedDefs_SkeletonReasonRepost = new(FeedDefs_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonRepost)
	default:
		return nil
	}
}

func (t *FeedDefs_SkeletonFeedPost_Reason) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_SkeletonReasonPin != nil {
		return t.FeedDefs_SkeletonReasonPin.MarshalCBOR(w)
	}
	if t.FeedDefs_SkeletonReasonRepost != nil {
		return t.FeedDefs_SkeletonReasonRepost.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_SkeletonFeedPost_Reason) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#skeletonReasonPin":
		t.FeedDefs_SkeletonReasonPin = new(FeedDefs_SkeletonReasonPin)
		return t.FeedDefs_SkeletonReasonPin.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#skeletonReasonRepost":
		t.FeedDefs_SkeletonReasonRepost = new(FeedDefs_SkeletonReasonRepost)
		return t.FeedDefs_SkeletonReasonRepost.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedDefs_SkeletonReasonPin is a "skeletonReasonPin" in the app.bsky.feed.defs schema.
type FeedDefs_SkeletonReasonPin struct {
	LexiconTypeID string `json:"$type"`
}

func (t *FeedDefs_SkeletonReasonPin) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_SkeletonReasonPin) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_SkeletonReasonRepost is a "skeletonReasonRepost" in the app.bsky.feed.defs schema.
type FeedDefs_SkeletonReasonRepost struct {
	LexiconTypeID string `json:"$type"`
	Repost        string `json:"repost"`
}

func (t *FeedDefs_SkeletonReasonRepost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_SkeletonReasonRepost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_ThreadContext is a "threadContext" in the app.bsky.feed.defs schema.
//
// Metadata about this post within the context of the thread it is in.
type FeedDefs_ThreadContext struct {
	LexiconTypeID  string  `json:"$type"`
	RootAuthorLike *string `json:"rootAuthorLike,omitempty"`
}

func (t *FeedDefs_ThreadContext) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ThreadContext) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_ThreadViewPost is a "threadViewPost" in the app.bsky.feed.defs schema.
type FeedDefs_ThreadViewPost struct {
	LexiconTypeID string                                 `json:"$type"`
	Parent        *FeedDefs_ThreadViewPost_Parent        `json:"parent,omitempty"`
	Post          FeedDefs_PostView                      `json:"post"`
	Replies       []FeedDefs_ThreadViewPost_Replies_Elem `json:"replies,omitempty"`
	ThreadContext *FeedDefs_ThreadContext                `json:"threadContext,omitempty"`
}

func (t *FeedDefs_ThreadViewPost) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ThreadViewPost) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type FeedDefs_ThreadViewPost_Parent struct {
	FeedDefs_BlockedPost    *FeedDefs_BlockedPost
	FeedDefs_NotFoundPost   *FeedDefs_NotFoundPost
	FeedDefs_ThreadViewPost *FeedDefs_ThreadViewPost
}

func (t *FeedDefs_ThreadViewPost_Parent) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_BlockedPost != nil {
		t.FeedDefs_BlockedPost.LexiconTypeID = "app.bsky.feed.defs#blockedPost"
		return json.Marshal(t.FeedDefs_BlockedPost)
	}
	if t.FeedDefs_NotFoundPost != nil {
		t.FeedDefs_NotFoundPost.LexiconTypeID = "app.bsky.feed.defs#notFoundPost"
		return json.Marshal(t.FeedDefs_NotFoundPost)
	}
	if t.FeedDefs_ThreadViewPost != nil {
		t.FeedDefs_ThreadViewPost.LexiconTypeID = "app.bsky.feed.defs#threadViewPost"
		return json.Marshal(t.FeedDefs_ThreadViewPost)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_ThreadViewPost_Parent) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return json.Unmarshal(b, t.FeedDefs_BlockedPost)
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return json.Unmarshal(b, t.FeedDefs_NotFoundPost)
	case "app.bsky.feed.defs#threadViewPost":
		t.FeedDefs_ThreadViewPost = new(FeedDefs_ThreadViewPost)
		return json.Unmarshal(b, t.FeedDefs_ThreadViewPost)
	default:
		return nil
	}
}

func (t *FeedDefs_ThreadViewPost_Parent) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_BlockedPost != nil {
		return t.FeedDefs_BlockedPost.MarshalCBOR(w)
	}
	if t.FeedDefs_NotFoundPost != nil {
		return t.FeedDefs_NotFoundPost.MarshalCBOR(w)
	}
	if t.FeedDefs_ThreadViewPost != nil {
		return t.FeedDefs_ThreadViewPost.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_ThreadViewPost_Parent) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return t.FeedDefs_BlockedPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return t.FeedDefs_NotFoundPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#threadViewPost":
		t.FeedDefs_ThreadViewPost = new(FeedDefs_ThreadViewPost)
		return t.FeedDefs_ThreadViewPost.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

type FeedDefs_ThreadViewPost_Replies_Elem struct {
	FeedDefs_BlockedPost    *FeedDefs_BlockedPost
	FeedDefs_NotFoundPost   *FeedDefs_NotFoundPost
	FeedDefs_ThreadViewPost *FeedDefs_ThreadViewPost
}

func (t *FeedDefs_ThreadViewPost_Replies_Elem) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_BlockedPost != nil {
		t.FeedDefs_BlockedPost.LexiconTypeID = "app.bsky.feed.defs#blockedPost"
		return json.Marshal(t.FeedDefs_BlockedPost)
	}
	if t.FeedDefs_NotFoundPost != nil {
		t.FeedDefs_NotFoundPost.LexiconTypeID = "app.bsky.feed.defs#notFoundPost"
		return json.Marshal(t.FeedDefs_NotFoundPost)
	}
	if t.FeedDefs_ThreadViewPost != nil {
		t.FeedDefs_ThreadViewPost.LexiconTypeID = "app.bsky.feed.defs#threadViewPost"
		return json.Marshal(t.FeedDefs_ThreadViewPost)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_ThreadViewPost_Replies_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return json.Unmarshal(b, t.FeedDefs_BlockedPost)
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return json.Unmarshal(b, t.FeedDefs_NotFoundPost)
	case "app.bsky.feed.defs#threadViewPost":
		t.FeedDefs_ThreadViewPost = new(FeedDefs_ThreadViewPost)
		return json.Unmarshal(b, t.FeedDefs_ThreadViewPost)
	default:
		return nil
	}
}

func (t *FeedDefs_ThreadViewPost_Replies_Elem) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.FeedDefs_BlockedPost != nil {
		return t.FeedDefs_BlockedPost.MarshalCBOR(w)
	}
	if t.FeedDefs_NotFoundPost != nil {
		return t.FeedDefs_NotFoundPost.MarshalCBOR(w)
	}
	if t.FeedDefs_ThreadViewPost != nil {
		return t.FeedDefs_ThreadViewPost.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *FeedDefs_ThreadViewPost_Replies_Elem) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.feed.defs#blockedPost":
		t.FeedDefs_BlockedPost = new(FeedDefs_BlockedPost)
		return t.FeedDefs_BlockedPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#notFoundPost":
		t.FeedDefs_NotFoundPost = new(FeedDefs_NotFoundPost)
		return t.FeedDefs_NotFoundPost.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.feed.defs#threadViewPost":
		t.FeedDefs_ThreadViewPost = new(FeedDefs_ThreadViewPost)
		return t.FeedDefs_ThreadViewPost.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// FeedDefs_ThreadgateView is a "threadgateView" in the app.bsky.feed.defs schema.
type FeedDefs_ThreadgateView struct {
	LexiconTypeID string                     `json:"$type"`
	Cid           *string                    `json:"cid,omitempty"`
	Lists         []GraphDefs_ListViewBasic  `json:"lists,omitempty"`
	Record        *glexrt.LexiconTypeDecoder `json:"record,omitempty"`
	Uri           *string                    `json:"uri,omitempty"`
}

func (t *FeedDefs_ThreadgateView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ThreadgateView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDefs_ViewerState is a "viewerState" in the app.bsky.feed.defs schema.
//
// Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.
type FeedDefs_ViewerState struct {
	LexiconTypeID     string  `json:"$type"`
	Bookmarked        *bool   `json:"bookmarked,omitempty"`
	EmbeddingDisabled *bool   `json:"embeddingDisabled,omitempty"`
	Like              *string `json:"like,omitempty"`
	Pinned            *bool   `json:"pinned,omitempty"`
	ReplyDisabled     *bool   `json:"replyDisabled,omitempty"`
	Repost            *string `json:"repost,omitempty"`
	ThreadMuted       *bool   `json:"threadMuted,omitempty"`
}

func (t *FeedDefs_ViewerState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.defs"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDefs_ViewerState) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
