// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.getLikes

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type FeedGetLikes_Output struct {
	LexiconTypeID string              `json:"$type"`
	Cid           *string             `json:"cid,omitempty"`
	Cursor        *string             `json:"cursor,omitempty"`
	Likes         []FeedGetLikes_Like `json:"likes"`
	Uri           string              `json:"uri"`
}

func (t *FeedGetLikes_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.getLikes#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedGetLikes_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedGetLikes calls the XRPC method "app.bsky.feed.getLikes".
//
// Get like records which reference a subject (by AT-URI and CID).
//
// cid: CID of the subject record (aka, specific version of record), to filter likes.
// uri: AT-URI of the subject (eg, a post record).
func FeedGetLikes(ctx context.Context, c glexrt.LexClient, cid string, cursor string, limit *int64, uri string) (*FeedGetLikes_Output, error) {
	var out FeedGetLikes_Output

	params := map[string]interface{}{}
	if cid != "" {
		params["cid"] = cid
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	params["uri"] = uri

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.feed.getLikes", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// FeedGetLikes_Like is a "like" in the app.bsky.feed.getLikes schema.
type FeedGetLikes_Like struct {
	LexiconTypeID string                `json:"$type"`
	Actor         ActorDefs_ProfileView `json:"actor"`
	CreatedAt     string                `json:"createdAt"`
	IndexedAt     string                `json:"indexedAt"`
}

func (t *FeedGetLikes_Like) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.getLikes"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedGetLikes_Like) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
