// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.describeFeedGenerator

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type FeedDescribeFeedGenerator_Output struct {
	LexiconTypeID string                           `json:"$type"`
	Did           string                           `json:"did"`
	Feeds         []FeedDescribeFeedGenerator_Feed `json:"feeds"`
	Links         *FeedDescribeFeedGenerator_Links `json:"links,omitempty"`
}

func (t *FeedDescribeFeedGenerator_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.describeFeedGenerator#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDescribeFeedGenerator_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDescribeFeedGenerator calls the XRPC method "app.bsky.feed.describeFeedGenerator".
//
// Get information about a feed generator, including policies and offered feed URIs. Does not require auth; implemented by Feed Generator services (not App View).
func FeedDescribeFeedGenerator(ctx context.Context, c glexrt.LexClient) (*FeedDescribeFeedGenerator_Output, error) {
	var out FeedDescribeFeedGenerator_Output

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.feed.describeFeedGenerator", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// FeedDescribeFeedGenerator_Feed is a "feed" in the app.bsky.feed.describeFeedGenerator schema.
type FeedDescribeFeedGenerator_Feed struct {
	LexiconTypeID string `json:"$type"`
	Uri           string `json:"uri"`
}

func (t *FeedDescribeFeedGenerator_Feed) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.describeFeedGenerator"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDescribeFeedGenerator_Feed) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedDescribeFeedGenerator_Links is a "links" in the app.bsky.feed.describeFeedGenerator schema.
type FeedDescribeFeedGenerator_Links struct {
	LexiconTypeID  string  `json:"$type"`
	PrivacyPolicy  *string `json:"privacyPolicy,omitempty"`
	TermsOfService *string `json:"termsOfService,omitempty"`
}

func (t *FeedDescribeFeedGenerator_Links) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.describeFeedGenerator"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedDescribeFeedGenerator_Links) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
