// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.feed.getActorLikes

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type FeedGetActorLikes_Output struct {
	LexiconTypeID string                  `json:"$type"`
	Cursor        *string                 `json:"cursor,omitempty"`
	Feed          []FeedDefs_FeedViewPost `json:"feed"`
}

func (t *FeedGetActorLikes_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.feed.getActorLikes#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *FeedGetActorLikes_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// FeedGetActorLikes calls the XRPC method "app.bsky.feed.getActorLikes".
//
// Get a list of posts liked by an actor. Requires auth, actor must be the requesting account.
func FeedGetActorLikes(ctx context.Context, c glexrt.LexClient, actor string, cursor string, limit *int64) (*FeedGetActorLikes_Output, error) {
	var out FeedGetActorLikes_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	params["actor"] = actor

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.feed.getActorLikes", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
