// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.graph.getListsWithMembership

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type GraphGetListsWithMembership_Output struct {
	LexiconTypeID       string                                           `json:"$type"`
	Cursor              *string                                          `json:"cursor,omitempty"`
	ListsWithMembership []GraphGetListsWithMembership_ListWithMembership `json:"listsWithMembership"`
}

func (t *GraphGetListsWithMembership_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.getListsWithMembership#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GraphGetListsWithMembership_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// GraphGetListsWithMembership calls the XRPC method "app.bsky.graph.getListsWithMembership".
//
// Enumerates the lists created by the session user, and includes membership information about `actor` in those lists. Only supports curation and moderation lists (no reference lists, used in starter packs). Requires auth.
//
// actor: The account (actor) to check for membership.
// purposes[]: Optional filter by list purpose. If not specified, all supported types are returned.
func GraphGetListsWithMembership(ctx context.Context, c glexrt.LexClient, actor string, cursor string, limit *int64, purposes []string) (*GraphGetListsWithMembership_Output, error) {
	var out GraphGetListsWithMembership_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	if len(purposes) != 0 {
		params["purposes"] = purposes
	}
	params["actor"] = actor

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.graph.getListsWithMembership", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GraphGetListsWithMembership_ListWithMembership is a "listWithMembership" in the app.bsky.graph.getListsWithMembership schema.
//
// A list and an optional list item indicating membership of a target user to that list.
type GraphGetListsWithMembership_ListWithMembership struct {
	LexiconTypeID string                  `json:"$type"`
	List          GraphDefs_ListView      `json:"list"`
	ListItem      *GraphDefs_ListItemView `json:"listItem,omitempty"`
}

func (t *GraphGetListsWithMembership_ListWithMembership) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.getListsWithMembership"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GraphGetListsWithMembership_ListWithMembership) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
