// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.graph.getStarterPacks

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type GraphGetStarterPacks_Output struct {
	LexiconTypeID string                           `json:"$type"`
	StarterPacks  []GraphDefs_StarterPackViewBasic `json:"starterPacks"`
}

func (t *GraphGetStarterPacks_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.getStarterPacks#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GraphGetStarterPacks_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// GraphGetStarterPacks calls the XRPC method "app.bsky.graph.getStarterPacks".
//
// Get views for a list of starter packs.
func GraphGetStarterPacks(ctx context.Context, c glexrt.LexClient, uris []string) (*GraphGetStarterPacks_Output, error) {
	var out GraphGetStarterPacks_Output

	params := map[string]interface{}{}
	params["uris"] = uris

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.graph.getStarterPacks", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
