// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.graph.unmuteThread

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type GraphUnmuteThread_Input struct {
	LexiconTypeID string `json:"$type"`
	Root          string `json:"root"`
}

func (t *GraphUnmuteThread_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.unmuteThread#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GraphUnmuteThread_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// GraphUnmuteThread calls the XRPC method "app.bsky.graph.unmuteThread".
//
// Unmutes the specified thread. Requires auth.
func GraphUnmuteThread(ctx context.Context, c glexrt.LexClient, input *GraphUnmuteThread_Input) error {

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "app.bsky.graph.unmuteThread", nil, input, nil); err != nil {
		return err
	}
	return nil
}
