// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.graph.listitem

package appbsky

import (
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glexrt.RegisterType("app.bsky.graph.listitem", &GraphListitem{})
}

// Record representing an account's inclusion on a specific list. The AppView will ignore duplicate listitem records.
type GraphListitem struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt"`
	// list: Reference (AT-URI) to the list record (app.bsky.graph.list).
	List string `json:"list"`
	// subject: The account which is included on the list.
	Subject string `json:"subject"`
}

func (t *GraphListitem) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.listitem"
	return glexrt.MarshalCBOR(w, t)
}

func (t *GraphListitem) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
