// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.graph.block

package appbsky

import (
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("app.bsky.graph.block", &GraphBlock{})
}

// Record declaring a 'block' relationship against another account. NOTE: blocks are public in Bluesky; see blog posts for details.
type GraphBlock struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt"`
	// subject: DID of the account to be blocked.
	Subject string `json:"subject"`
}

// RecordTypeID implements glex.Record.
func (t *GraphBlock) RecordTypeID() string { return "app.bsky.graph.block" }

func (t *GraphBlock) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.graph.block"
	return glex.MarshalCBOR(w, t)
}

func (t *GraphBlock) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
