// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.labeler.getServices

package appbsky

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type LabelerGetServices_Output struct {
	LexiconTypeID string                                 `json:"$type"`
	Views         []LabelerGetServices_Output_Views_Elem `json:"views"`
}

func (t *LabelerGetServices_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.labeler.getServices#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *LabelerGetServices_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

type LabelerGetServices_Output_Views_Elem struct {
	LabelerDefs_LabelerView         *LabelerDefs_LabelerView
	LabelerDefs_LabelerViewDetailed *LabelerDefs_LabelerViewDetailed
}

func (t *LabelerGetServices_Output_Views_Elem) MarshalJSON() ([]byte, error) {
	if t.LabelerDefs_LabelerView != nil {
		t.LabelerDefs_LabelerView.LexiconTypeID = "app.bsky.labeler.defs#labelerView"
		return json.Marshal(t.LabelerDefs_LabelerView)
	}
	if t.LabelerDefs_LabelerViewDetailed != nil {
		t.LabelerDefs_LabelerViewDetailed.LexiconTypeID = "app.bsky.labeler.defs#labelerViewDetailed"
		return json.Marshal(t.LabelerDefs_LabelerViewDetailed)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *LabelerGetServices_Output_Views_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glexrt.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.labeler.defs#labelerView":
		t.LabelerDefs_LabelerView = new(LabelerDefs_LabelerView)
		return json.Unmarshal(b, t.LabelerDefs_LabelerView)
	case "app.bsky.labeler.defs#labelerViewDetailed":
		t.LabelerDefs_LabelerViewDetailed = new(LabelerDefs_LabelerViewDetailed)
		return json.Unmarshal(b, t.LabelerDefs_LabelerViewDetailed)
	default:
		return nil
	}
}

func (t *LabelerGetServices_Output_Views_Elem) MarshalCBOR(w io.Writer) error {

	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if t.LabelerDefs_LabelerView != nil {
		return t.LabelerDefs_LabelerView.MarshalCBOR(w)
	}
	if t.LabelerDefs_LabelerViewDetailed != nil {
		return t.LabelerDefs_LabelerViewDetailed.MarshalCBOR(w)
	}
	return fmt.Errorf("can not marshal empty union as CBOR")
}

func (t *LabelerGetServices_Output_Views_Elem) UnmarshalCBOR(r io.Reader) error {
	typ, b, err := glexrt.CborTypeExtractReader(r)
	if err != nil {
		return err
	}

	switch typ {
	case "app.bsky.labeler.defs#labelerView":
		t.LabelerDefs_LabelerView = new(LabelerDefs_LabelerView)
		return t.LabelerDefs_LabelerView.UnmarshalCBOR(bytes.NewReader(b))
	case "app.bsky.labeler.defs#labelerViewDetailed":
		t.LabelerDefs_LabelerViewDetailed = new(LabelerDefs_LabelerViewDetailed)
		return t.LabelerDefs_LabelerViewDetailed.UnmarshalCBOR(bytes.NewReader(b))
	default:
		return nil
	}
}

// LabelerGetServices calls the XRPC method "app.bsky.labeler.getServices".
//
// Get information about a list of labeler services.
func LabelerGetServices(ctx context.Context, c glexrt.LexClient, detailed *bool, dids []string) (*LabelerGetServices_Output, error) {
	var out LabelerGetServices_Output

	params := map[string]interface{}{}
	if detailed != nil {
		params["detailed"] = *detailed
	}
	params["dids"] = dids

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.labeler.getServices", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
