// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.notification.putPreferences

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type NotificationPutPreferences_Input struct {
	LexiconTypeID string `json:"$type"`
	Priority      bool   `json:"priority"`
}

func (t *NotificationPutPreferences_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.notification.putPreferences#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *NotificationPutPreferences_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// NotificationPutPreferences calls the XRPC method "app.bsky.notification.putPreferences".
//
// Set notification-related preferences for an account. Requires auth.
func NotificationPutPreferences(ctx context.Context, c glexrt.LexClient, input *NotificationPutPreferences_Input) error {

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "app.bsky.notification.putPreferences", nil, input, nil); err != nil {
		return err
	}
	return nil
}
