// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getSuggestionsSkeleton

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type UnspeccedGetSuggestionsSkeleton_Output struct {
	LexiconTypeID string                              `json:"$type"`
	Actors        []UnspeccedDefs_SkeletonSearchActor `json:"actors"`
	Cursor        *string                             `json:"cursor,omitempty"`
	// recId: Snowflake for this recommendation, use when submitting recommendation events.
	RecId *int64 `json:"recId,omitempty"`
	// relativeToDid: DID of the account these suggestions are relative to. If this is returned undefined, suggestions are based on the viewer.
	RelativeToDid *string `json:"relativeToDid,omitempty"`
}

func (t *UnspeccedGetSuggestionsSkeleton_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.unspecced.getSuggestionsSkeleton#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *UnspeccedGetSuggestionsSkeleton_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// UnspeccedGetSuggestionsSkeleton calls the XRPC method "app.bsky.unspecced.getSuggestionsSkeleton".
//
// Get a skeleton of suggested actors. Intended to be called and then hydrated through app.bsky.actor.getSuggestions
//
// relativeToDid: DID of the account to get suggestions relative to. If not provided, suggestions will be based on the viewer.
// viewer: DID of the account making the request (not included for public/unauthenticated queries). Used to boost followed accounts in ranking.
func UnspeccedGetSuggestionsSkeleton(ctx context.Context, c glexrt.LexClient, cursor string, limit *int64, relativeToDid string, viewer string) (*UnspeccedGetSuggestionsSkeleton_Output, error) {
	var out UnspeccedGetSuggestionsSkeleton_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != nil {
		params["limit"] = *limit
	}
	if relativeToDid != "" {
		params["relativeToDid"] = relativeToDid
	}
	if viewer != "" {
		params["viewer"] = viewer
	}

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.unspecced.getSuggestionsSkeleton", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
