// Code generated by glex; DO NOT EDIT.

// Lexicon schema: app.bsky.unspecced.getTaggedSuggestions

package appbsky

import (
	"context"
	"io"

	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type UnspeccedGetTaggedSuggestions_Output struct {
	LexiconTypeID string                                     `json:"$type"`
	Suggestions   []UnspeccedGetTaggedSuggestions_Suggestion `json:"suggestions"`
}

func (t *UnspeccedGetTaggedSuggestions_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.unspecced.getTaggedSuggestions#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *UnspeccedGetTaggedSuggestions_Output) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// UnspeccedGetTaggedSuggestions calls the XRPC method "app.bsky.unspecced.getTaggedSuggestions".
//
// Get a list of suggestions (feeds and users) tagged with categories
func UnspeccedGetTaggedSuggestions(ctx context.Context, c glexrt.LexClient) (*UnspeccedGetTaggedSuggestions_Output, error) {
	var out UnspeccedGetTaggedSuggestions_Output

	if err := c.LexDo(ctx, glexrt.Query, "", "app.bsky.unspecced.getTaggedSuggestions", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UnspeccedGetTaggedSuggestions_Suggestion is a "suggestion" in the app.bsky.unspecced.getTaggedSuggestions schema.
type UnspeccedGetTaggedSuggestions_Suggestion struct {
	LexiconTypeID string `json:"$type"`
	Subject       string `json:"subject"`
	SubjectType   string `json:"subjectType"`
	Tag           string `json:"tag"`
}

func (t *UnspeccedGetTaggedSuggestions_Suggestion) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "app.bsky.unspecced.getTaggedSuggestions"
	return glexrt.MarshalCBOR(w, t)
}

func (t *UnspeccedGetTaggedSuggestions_Suggestion) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
