#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

prettylog() {
  name="$1"
  color="$2"
  while IFS= read -r line; do
    echo -en "\e[38;05;${color}m[${name}]\e[38;05;231m "
    echo "$line"
  done
}

function run() {
  name="$1"
  path="$2"
  color="$3"
  cd "$DIR/../$path" && npm run dev 2>&1 | prettylog "$name" "$color" &
  sleep 2
}
export NODE_PATH="$(realpath "$DIR/../lib")"
# export DEBUG_LEVEL="debug"
run sk-schema lib/sk-schema 4
run sk-client lib/sk-client 196
run bellamie bellamie 201
run gort gort 6
run pipeland pipeland 40
wait

# for i in {0..255}; do echo -e "\e[38;05;${i}m\\\e[38;05;${i}m"; done
