#!/bin/bash

set -o pipefail
set -o nounset

drone secret add streamplace/streamplace --name WH_S3_ACCESS_KEY_ID --value "$(cat /keybase/team/streamplace_team/secrets/ibm/access-key-id.txt)"
drone secret add streamplace/streamplace --name WH_S3_SECRET_ACCESS_KEY --value "$(cat /keybase/team/streamplace_team/secrets/ibm/secret-access-key.txt)"
drone secret add streamplace/streamplace --name WH_S3_URL --value "https://s3-api.us-geo.objectstorage.softlayer.net/blobtown.stream.place"
drone secret add streamplace/streamplace --name WH_DOCKER_AUTH --value "$(cat /keybase/team/streamplace_team/secrets/docker-config.json | openssl base64)"
drone secret add streamplace/streamplace --name slack_webhook --value "$(cat /keybase/team/streamplace_team/secrets/drone-slack-webhook.txt)"
drone secret add streamplace/streamplace --name npm_token --value "$(cat /keybase/team/streamplace_team/secrets/npm_token)"
drone secret add streamplace/streamplace --name values_secret_yaml --value "$(cat /keybase/team/streamplace_team/secrets/values.secret.yaml)"
drone secret add streamplace/streamplace --name kubeconfig_content --value "$(cat /keybase/team/streamplace_team/secrets/clusters/snorlax/kubeconfig)"
