#!/bin/bash

set -o pipefail
set -o nounset

SECRETS="/keybase/team/streamplace_team/secrets"

drone secret add streamplace/streamplace --name WH_S3_ACCESS_KEY_ID --value "$(cat $SECRETS/ibm/access-key-id.txt)"
drone secret add streamplace/streamplace --name WH_S3_SECRET_ACCESS_KEY --value "$(cat $SECRETS/ibm/secret-access-key.txt)"
drone secret add streamplace/streamplace --name WH_S3_URL --value "https://s3-api.us-geo.objectstorage.softlayer.net/blobtown.stream.place"
drone secret add streamplace/streamplace --name WH_DOCKER_AUTH --value "$(cat $SECRETS/docker-config.json | openssl base64)"
drone secret add streamplace/streamplace --name slack_webhook --value "$(cat $SECRETS/drone-slack-webhook.txt)"
drone secret add streamplace/streamplace --name npm_token --value "$(cat $SECRETS/npm_token)"
drone secret add streamplace/streamplace --name values_secret_yaml --value "$(cat $SECRETS/values.secret.yaml | openssl base64 -A)"
drone secret add streamplace/streamplace --name kubeconfig_content --value "$(cat $SECRETS/clusters/snorlax/kubeconfig | openssl base64 -A)"
drone secret add streamplace/streamplace --name travis_token --value "$(cat $SECRETS/travis_token)"
