// Code generated by glex; DO NOT EDIT.

// Lexicon schema: games.gamesgamesgamesgames.search

package gamesgamesgamesgamesgames

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

type Search_Output struct {
	LexiconTypeID string                       `json:"$type,omitempty"`
	Cursor        *string                      `json:"cursor,omitempty"`
	Results       []Search_Output_Results_Elem `json:"results"`
	// totalResults: Total number of results matching the query above the relevance threshold.
	TotalResults *int64 `json:"totalResults,omitempty"`
}

// RecordTypeID implements glex.Record.
func (t *Search_Output) RecordTypeID() string { return "games.gamesgamesgamesgames.search" }

func (t *Search_Output) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "games.gamesgamesgamesgames.search"
	return glex.MarshalCBOR(w, &cp)
}

func (t *Search_Output) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type Search_Output_Results_Elem struct {
	Defs_CollectionSummaryView *Defs_CollectionSummaryView
	Defs_EngineSummaryView     *Defs_EngineSummaryView
	Defs_GameSummaryView       *Defs_GameSummaryView
	Defs_PlatformSummaryView   *Defs_PlatformSummaryView
	Defs_ProfileSummaryView    *Defs_ProfileSummaryView
	// Raw preserves a variant whose $type is not in this union's generated
	// set, so unrecognized variants still round-trip losslessly through
	// decode/re-encode. Nil when a known variant is set.
	Raw *glex.RawRecord
}

// MarshalJSON emits the set variant, stamped with its $type, per the atproto
// union wire format. The value receiver stamps a copy, so the variant is
// never mutated and both Search_Output_Results_Elem and *Search_Output_Results_Elem marshal correctly.
func (t Search_Output_Results_Elem) MarshalJSON() ([]byte, error) {
	if t.Defs_CollectionSummaryView != nil {
		cp := *t.Defs_CollectionSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#collectionSummaryView"
		return json.Marshal(&cp)
	}
	if t.Defs_EngineSummaryView != nil {
		cp := *t.Defs_EngineSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#engineSummaryView"
		return json.Marshal(&cp)
	}
	if t.Defs_GameSummaryView != nil {
		cp := *t.Defs_GameSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#gameSummaryView"
		return json.Marshal(&cp)
	}
	if t.Defs_PlatformSummaryView != nil {
		cp := *t.Defs_PlatformSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#platformSummaryView"
		return json.Marshal(&cp)
	}
	if t.Defs_ProfileSummaryView != nil {
		cp := *t.Defs_ProfileSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#profileSummaryView"
		return json.Marshal(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "json" {
			return nil, fmt.Errorf("cannot marshal raw %s record as JSON in union Search_Output_Results_Elem", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Search_Output_Results_Elem as JSON")
}

func (t *Search_Output_Results_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "games.gamesgamesgamesgames.defs#collectionSummaryView":
		t.Defs_CollectionSummaryView = new(Defs_CollectionSummaryView)
		return json.Unmarshal(b, t.Defs_CollectionSummaryView)
	case "games.gamesgamesgamesgames.defs#engineSummaryView":
		t.Defs_EngineSummaryView = new(Defs_EngineSummaryView)
		return json.Unmarshal(b, t.Defs_EngineSummaryView)
	case "games.gamesgamesgamesgames.defs#gameSummaryView":
		t.Defs_GameSummaryView = new(Defs_GameSummaryView)
		return json.Unmarshal(b, t.Defs_GameSummaryView)
	case "games.gamesgamesgamesgames.defs#platformSummaryView":
		t.Defs_PlatformSummaryView = new(Defs_PlatformSummaryView)
		return json.Unmarshal(b, t.Defs_PlatformSummaryView)
	case "games.gamesgamesgamesgames.defs#profileSummaryView":
		t.Defs_ProfileSummaryView = new(Defs_ProfileSummaryView)
		return json.Unmarshal(b, t.Defs_ProfileSummaryView)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "json", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// MarshalCBOR implements drisl.Marshaler, emitting the set variant (stamped
// with its $type) per the atproto union wire format. go-dasl invokes this
// when the union appears inside another record, so nested unions serialize
// correctly.
func (t Search_Output_Results_Elem) MarshalCBOR() ([]byte, error) {
	if t.Defs_CollectionSummaryView != nil {
		cp := *t.Defs_CollectionSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#collectionSummaryView"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Defs_EngineSummaryView != nil {
		cp := *t.Defs_EngineSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#engineSummaryView"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Defs_GameSummaryView != nil {
		cp := *t.Defs_GameSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#gameSummaryView"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Defs_PlatformSummaryView != nil {
		cp := *t.Defs_PlatformSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#platformSummaryView"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Defs_ProfileSummaryView != nil {
		cp := *t.Defs_ProfileSummaryView
		cp.LexiconTypeID = "games.gamesgamesgamesgames.defs#profileSummaryView"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "cbor" {
			return nil, fmt.Errorf("cannot marshal raw %s record as CBOR in union Search_Output_Results_Elem", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Search_Output_Results_Elem as CBOR")
}

func (t *Search_Output_Results_Elem) UnmarshalCBOR(b []byte) error {
	typ, err := glex.CborTypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "games.gamesgamesgamesgames.defs#collectionSummaryView":
		t.Defs_CollectionSummaryView = new(Defs_CollectionSummaryView)
		return glex.UnmarshalCBORBytes(b, t.Defs_CollectionSummaryView)
	case "games.gamesgamesgamesgames.defs#engineSummaryView":
		t.Defs_EngineSummaryView = new(Defs_EngineSummaryView)
		return glex.UnmarshalCBORBytes(b, t.Defs_EngineSummaryView)
	case "games.gamesgamesgamesgames.defs#gameSummaryView":
		t.Defs_GameSummaryView = new(Defs_GameSummaryView)
		return glex.UnmarshalCBORBytes(b, t.Defs_GameSummaryView)
	case "games.gamesgamesgamesgames.defs#platformSummaryView":
		t.Defs_PlatformSummaryView = new(Defs_PlatformSummaryView)
		return glex.UnmarshalCBORBytes(b, t.Defs_PlatformSummaryView)
	case "games.gamesgamesgamesgames.defs#profileSummaryView":
		t.Defs_ProfileSummaryView = new(Defs_ProfileSummaryView)
		return glex.UnmarshalCBORBytes(b, t.Defs_ProfileSummaryView)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "cbor", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// Search calls the XRPC method "games.gamesgamesgamesgames.search".
//
// Search across all entity types (games, profiles, platforms, collections, engines).
//
// ageRatings[]: Filter game results by age rating in 'organization:rating' format (e.g. esrb:M, pegi:Eighteen).
// applicationTypes[]: Filter game results by application type (e.g. game, dlc, bundle). Only applies when types includes game.
// includeUnrated: When age rating filters are active, also include games with no age ratings.
func Search(ctx context.Context, c glex.LexClient, ageRatings []string, applicationTypes []string, cursor string, genres []string, includeCancelled *bool, includeUnrated *bool, limit *int64, modes []string, playerPerspectives []string, q string, sort string, themes []string, types []string) (*Search_Output, error) {
	var out Search_Output

	params := map[string]interface{}{}
	if len(ageRatings) != 0 {
		params["ageRatings"] = ageRatings
	}
	if len(applicationTypes) != 0 {
		params["applicationTypes"] = applicationTypes
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if len(genres) != 0 {
		params["genres"] = genres
	}
	if includeCancelled != nil {
		params["includeCancelled"] = *includeCancelled
	}
	if includeUnrated != nil {
		params["includeUnrated"] = *includeUnrated
	}
	if limit != nil {
		params["limit"] = *limit
	}
	if len(modes) != 0 {
		params["modes"] = modes
	}
	if len(playerPerspectives) != 0 {
		params["playerPerspectives"] = playerPerspectives
	}
	if sort != "" {
		params["sort"] = sort
	}
	if len(themes) != 0 {
		params["themes"] = themes
	}
	if len(types) != 0 {
		params["types"] = types
	}
	params["q"] = q

	if err := c.LexDo(ctx, glex.Query, "", "games.gamesgamesgamesgames.search", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
