name: build

on:
  pull_request:
  push:
    branches:
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: linux-amd64
            cmd: "make && (make test || make test) && make check"
          - name: linux-arm64
            cmd: "make app && make linux-arm64"
          - name: windows-amd64
            cmd: "make app && make windows-amd64"
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: docker/build.Dockerfile
          push: false
          tags: "ghcr.io/streamplace/streamplace:build"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: builder
          load: true

      - name: make node
        run: |
          make in-container DOCKER_BIN=docker DOCKER_OPTS="-e STREAMPLACE_TEST_COUNT=1" DOCKER_REF=ghcr.io/streamplace/streamplace:build IN_CONTAINER_CMD="${{ matrix.cmd }}"

  darwin:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - name: darwin-arm64
            runs-on: macos-latest
            cmd: make && make test && make check
          - name: darwin-amd64
            runs-on: macos-13
            cmd: make
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Streamplace
        env:
          STREAMPLACE_TEST_COUNT: "1"
        run: |
          export GOTOOLCHAIN=go1.23.6 \
          && brew install go \
          && python -m pip install virtualenv \
          && python -m virtualenv ~/venv \
          && source ~/venv/bin/activate \
          && python -m pip install meson \
          && ${{ matrix.cmd }}
